import { ART_BY_FORMAT, ART_BY_GENRE, BAND_LABELS, CONCEPT_ANGLES, DEMOS, DAYS, FORMAT_NEEDS, SLOT_MULT, STORY_TEMPLATES, STAGE_TYPES, THEME_NOVELTY, slotBand } from './constants.js';
import { addDays, affinity, avg, clamp, dateObj, dayIndex, deepClone, seeded, uid } from './utils.js';
import { makeProgramDraft, rolesFor } from './seed.js';

export const getIP=(s,id)=>s.ips.find(x=>x.id===id);
export const getProgram=(s,id)=>s.programs.find(x=>x.id===id);
export const getEmployee=(s,id)=>s.employees.find(x=>x.id===id);
export const getPerson=(s,id)=>getEmployee(s,id)||s.candidateMarket?.find(x=>x.id===id);
export const getStage=(s,id)=>s.stages?.find(x=>x.id===id);
export const researched=(s,id)=>!!s.tech.find(t=>t.id===id)?.researched;
export const homeState=s=>s.states.find(x=>x.code===s.network.home);
export const networkReachHouseholds=s=>s.states.reduce((sum,st)=>sum+(st.areas||[]).reduce((a,x)=>a+x.households*(x.reachPct||0),0),0);
export const totalPotentialHouseholds=s=>s.states.reduce((sum,x)=>sum+x.households,0);

function sendMail(s,from,subject,body,category='info',meta={}){s.emails=s.emails||[];s.emails.unshift({id:uid('mail'),date:s.date,from,subject,body,read:false,category,...meta});s.emails=s.emails.slice(0,300);}
export function markMailRead(state,id){const s=deepClone(state),m=s.emails.find(x=>x.id===id);if(m)m.read=true;return s;}
export function markAllMailRead(state){const s=deepClone(state);s.emails.forEach(m=>m.read=true);return s;}

export function ipSeasonEffect(ip,change){const flexibility=ip.flexibility||50,sweet=clamp(18+flexibility*.25,18,48),noveltyGain=change<=sweet?change*.58:sweet*.58+(change-sweet)*.82,identityPenalty=change<=sweet?Math.max(0,change-sweet*.65)*.08:(change-sweet)*(1.18-flexibility/180),familiarityLoss=Math.max(0,sweet*.45-change)*.09,retainedPopularity=clamp(ip.popularity-identityPenalty-familiarityLoss,0,100),newNovelty=clamp(ip.novelty*.74+noveltyGain-(ip.fatigue||0)*.15,0,100),fatigueChange=change<12?5:change>75?-2:-Math.min(4,change/22);return {retainedPopularity,newNovelty,newFatigue:clamp((ip.fatigue||0)+fatigueChange,0,100),sweet,identityPenalty};}
export function effectiveAppeal(program,ip){const pop=ip?.popularity||8,nov=ip?.novelty||35,fatigue=ip?.fatigue||0,popNov=pop*.52+nov*.28+Math.min(pop,nov)*.20,quality=program.quality||((program.scriptStars||2.5)*16),viewer=program.premiered?(program.viewer||50):quality,critic=program.premiered?(program.critic||50):quality,reception=viewer*.52+critic*.18+quality*.30,marketing=Math.min(15,(program.marketing||0)*.12);return clamp(popNov*.48+reception*.42+(program.momentum||0)*.25-fatigue*.22+marketing,5,100);}
function weightedAffinity(program,ip){return avg(DEMOS.map(([k])=>(program.target?.[k]||45)*.58+(ip?.affinity?.[k]||45)*.42));}

export function calcAudience(s,program,slotKeyOrTime,date){
  const ip=getIP(s,program.ipId),reach=networkReachHouseholds(s),band=SLOT_MULT[slotKeyOrTime]?slotKeyOrTime:slotBand(slotKeyOrTime||'20:00'),rand=seeded(`${date}-${program.id}-${slotKeyOrTime}-${program.airings||0}`),demoFit=weightedAffinity(program,ip),appeal=effectiveAppeal(program,ip),awareness=clamp((program.awareness||8)+(s.network.prestige||5)*.22+(s.network.trust||5)*.08,3,100),threat=competitionThreat(s,band),competition=clamp(1.05-threat*.0025+rand()*.18,.68,1.08),slot=SLOT_MULT[band]||.6,adPenalty=clamp(1-(Math.max(0,(program.adLoad??12)-12)*.012),.72,1),networkScale=clamp(.48+(s.network.prestige||5)*.015,.5,1.08),conversion=clamp((demoFit*.0021+appeal*.00255+awareness*.0012)*slot*competition*adPenalty*networkScale,0.003,.44),audience=reach*conversion,demoShares={},weights=DEMOS.map(([k])=>Math.max(1,(program.target?.[k]||40)*.58+(ip?.affinity?.[k]||40)*.42),),sum=weights.reduce((a,b)=>a+b,0);DEMOS.forEach(([k],i)=>demoShares[k]=audience*weights[i]/sum);
  const hs=homeState(s),homeReach=(hs?.areas||[]).reduce((a,x)=>a+x.households*(x.reachPct||0),0),localReach=(hs?.areas?.[0]?.households||0)*(hs?.areas?.[0]?.reachPct||0),stateShare=reach?homeReach/reach:1,localShare=reach?localReach/reach:1;
  return {audience,demoShares,conversion,appeal,demoFit,scopes:{national:audience,state:audience*stateShare,local:audience*localShare}};
}
function competitionThreat(s,band){const vals=(s.competitors||[]).map(c=>c.strength+(c.specialty==='Sports'&&band==='prime'?8:0)+(c.specialty==='News'&&band==='morning'?8:0));return avg(vals)||55;}

export function executionQuality(s,p){
  const needs=FORMAT_NEEDS[p.genre]||FORMAT_NEEDS.default,alloc=p.productionAllocation||{};let weighted=0,total=0;
  Object.entries(needs).filter(([k])=>k!=='writing').forEach(([k,w])=>{let points=2;if(k==='cast')points=alloc.extras??2;else if(k==='design'){const costumeWeight=['Historical','Fantasy'].includes(p.genre)?.5:.3;points=(alloc.set??2)*(1-costumeWeight)+(alloc.costume??1)*costumeWeight;}else if(k==='image')points=alloc.camera??2;else points=alloc[k]??1;weighted+=clamp(points*20,0,100)*w;total+=w});const dept=weighted/Math.max(1,total);
  const sr=getEmployee(s,p.team?.showrunner),wr=getEmployee(s,p.team?.leadWriter),director=getEmployee(s,p.team?.director),castPeople=(p.cast||[]).map(id=>getPerson(s,id)).filter(Boolean),castQuality=castPeople.length?avg(castPeople.map(t=>t.skills?.acting||t.skills?.charisma||t.overall)):48,team=(sr?.skills?.vision||sr?.overall||45)*.22+(wr?.skills?.writing||wr?.overall||45)*.18+castQuality*.19+(director?.skills?.direction||director?.overall||45)*.12,scripts=(p.scriptStars||2.5)*6.4,chemistry=(p.chemistry||50)*.08,budgetRatio=(p.budgetPerEpisode||1)/Math.max(1,p.suggestedBudgetPerEpisode||p.baseBudgetPerEpisode||1),budgetFit=clamp((budgetRatio-1)*12,-10,7),stagePenalty=(1-(p.stageFit||1))*24;
  let tech=0;if(p.technical?.resolution==='4K')tech+=2.5;if(p.technical?.hdr)tech+=1.7;if(p.technical?.audio==='5.1')tech+=1;if(p.technical?.audio==='Immersive')tech+=2;if(researched(s,'t_vfx')&&(needs.vfx||0)>.9)tech+=3.2;
  return clamp(dept*.48+team+scripts+chemistry+tech+budgetFit-stagePenalty-23,20,97);
}
function formatBaseNovelty(format,genre){if(format==='News')return 5;if(format==='Sports')return genre==='Live Sports'?3:10;if(format==='Documentaries')return 18;if(format==='Contests')return 20;if(format==='Reality')return genre==='Survival'?22:genre==='Social Experiment'?30:18;if(format==='Scripted')return ['Science Fiction','Fantasy'].includes(genre)?28:['Medical','Crime'].includes(genre)?14:20;if(format==='Live')return 12;return 16;}
function conceptNovelty(s,d,writer){const base=formatBaseNovelty(d.format,d.genre),theme=(THEME_NOVELTY[d.theme]??0)*.65,angle=(CONCEPT_ANGLES[d.angle]?.novelty??0)*.65,originality=(writer?.skills?.originality||writer?.skills?.writing||writer?.overall||50)-50,craft=(writer?.skills?.writing||writer?.overall||50)-60,expertise=(s.network.expertise?.[d.format]||0)-4,r=seeded(`novelty-${d.id}-${s.date}`)();return clamp(base+theme+angle+originality*.58+craft*.16+expertise*.4+(r-.5)*10,4,96);}
function scriptRating(s,d,writer){const writing=writer?.skills?.writing||writer?.overall||45,plot=writer?.skills?.plotting||writing,dialogue=writer?.skills?.dialogue||writing,originality=writer?.skills?.originality||writing,expertise=s.network.expertise?.[d.format]||0,r=seeded(`script-${d.id}-${s.date}`)(),angleRisk=CONCEPT_ANGLES[d.angle]?.risk??0,raw=(writing*.42+plot*.25+dialogue*.18+originality*.15)+expertise*1.2-angleRisk*.18+(r-.5)*16;return Math.round(clamp(1+(raw-38)/15,1,5)*2)/2;}

function conceptPitch(d,writer){
  const pool=STORY_TEMPLATES[d.genre]||STORY_TEMPLATES[d.format]||[];
  const r=seeded(`pitch-${d.id}-${writer?.id||'writer'}`);
  if(!pool.length){
    const first=['Open','Electric','Last','Golden','Hidden','Midnight','Wild','Bright','Final','Inside','American','Second','Secret','Live','True','Beyond'];
    const second=['Stage','Hour','Line','House','Arena','Desk','Road','Signal','Room','Challenge','Voices','City','Chance','Story','Edge','Spotlight'];
    const title=`${first[Math.floor(r()*first.length)]} ${second[Math.floor(r()*second.length)]}`;
    const hook=d.topic?.trim()||d.theme.toLowerCase();
    return [title,`A ${d.genre.toLowerCase()} program centered on ${hook}, shaped for ${d.format.toLowerCase()} television by ${writer?.name||'the writing team'}.`];
  }
  const pick=pool[Math.floor(r()*pool.length)]||pool[0];
  return pick;
}
function episodeScriptRating(s,d,writer,episode){
  const base=scriptRating(s,d,writer),r=seeded(`episode-script-${d.id}-${episode}`)();
  return Math.round(clamp(base+(r-.5)*.9,1,5)*2)/2;
}
function suggestedEpisodeBudget(d){
  const base={Scripted:430000,Reality:230000,Sports:150000,News:55000,Documentaries:190000,Live:120000,Contests:185000}[d.format]||150000;
  const genreMult=['Fantasy','Science Fiction','Historical'].includes(d.genre)?1.75:['Survival','Physical','Music'].includes(d.genre)?1.3:['Local News','Morning News'].includes(d.genre)?.62:1;
  const durationMult=Number(d.duration||60)/60;
  const qualityMult=.78+(Number(d.scriptStars||2.5)/5)*.44;
  return Math.round(base*genreMult*durationMult*qualityMult/10000)*10000;
}
function syncDevelopmentToProgram(s,d){
  if(!d.programId)return;
  const p=getProgram(s,d.programId);if(!p)return;
  p.scripts=(d.scripts||[]).map(x=>({...x}));
  p.pipeline.scripted=d.scriptedEpisodes||0;
  p.scriptStars=d.scriptStars||p.scriptStars;
  p.suggestedBudgetPerEpisode=d.suggestedBudgetPerEpisode||p.suggestedBudgetPerEpisode;
}
function completeEpisodeScript(s,d,writer,episode){
  if((d.scripts||[]).some(x=>x.episode===episode))return;
  if(!d.summary){const [title,summary]=conceptPitch(d,writer);if(!d.titleLocked)d.title=title;d.summary=summary;}
  const stars=episodeScriptRating(s,d,writer,episode);
  d.scripts=d.scripts||[];d.scripts.push({episode,title:`Episode ${episode}`,stars,notes:episode===1?'Pilot / premiere draft':'Production draft',status:'Ready'});d.scripts.sort((a,b)=>a.episode-b.episode);
  d.scriptedEpisodes=d.scripts.length;d.scriptStars=avg(d.scripts.map(x=>x.stars));
  if(d.novelty==null)d.novelty=conceptNovelty(s,d,writer);
  d.suggestedBudgetPerEpisode=suggestedEpisodeBudget(d);
  syncDevelopmentToProgram(s,d);
  if(episode===1)sendMail(s,writer?.name||'Writers Room',`First script ready: ${d.title}`,`${d.title}\n\n${d.summary}\n\nEpisode 1 is ready for production.\nEpisode script rating: ${stars.toFixed(1)} / 5 stars\nSeason currently commissioned: ${d.episodes} × ${d.duration} minutes\nSuggested episode budget: $${d.suggestedBudgetPerEpisode.toLocaleString()}\n\nYou may greenlight now while the remaining scripts continue to arrive.`, 'script',{developmentId:d.id});
}

export function commissionScript(state,form){
  const s=deepClone(state),writer=getEmployee(s,form.writerId);if(!writer||!writer.role.includes('Writer')||form.genre==='Live Sports')return s;
  const episodes=Number(form.episodes),duration=Number(form.duration),speed=writer.skills.speed||65,totalDays=Math.max(episodes,Math.round(episodes*(duration/30)*(8.5-speed/18)*(form.format==='Scripted'?1:form.format==='Reality'?.72:form.format==='News'?.30:form.format==='Live'?.38:form.format==='Contests'?.55:.65))),cost=Math.round(episodes*(duration/30)*(form.format==='Scripted'?13000:form.format==='Reality'?7500:form.format==='Documentaries'?9500:form.format==='Contests'?7000:4500));
  if(s.cash<cost*.25)return s;
  const d={id:uid('dev'),title:form.title?.trim()||`Untitled ${form.genre}`,titleLocked:!!form.title?.trim(),summary:'',format:form.format,genre:form.genre,theme:form.theme||'Contemporary',topic:form.topic||'',angle:form.angle||'Fresh',episodes,duration,writerId:writer.id,status:'Writing',daysRemaining:totalDays,totalDays,elapsedDays:0,episodeInterval:Math.max(1,Math.round(totalDays/episodes)),scriptedEpisodes:0,scripts:[],cost,spent:cost*.25,scriptStars:null,novelty:null,suggestedBudgetPerEpisode:null,target:form.target||affinity(),art:form.art||ART_BY_GENRE[form.genre]||ART_BY_FORMAT[form.format]||'cinematic',font:form.font,p1:form.p1,p2:form.p2,ipId:form.ipId||'new',created:s.date,greenlit:false,refined:false};
  s.developments.push(d);s.cash-=cost*.25;s.totalExpense+=cost*.25;
  sendMail(s,'Development Office',`Writing started: ${d.genre} project`,`${writer.name} has started a ${episodes}-episode, ${duration}-minute ${d.genre} project. A script should become available roughly every ${d.episodeInterval} day${d.episodeInterval===1?'':'s'}; the full season is expected in about ${totalDays} days.`, 'development',{developmentId:d.id});return s;
}
export function rewriteDevelopment(state,id){
  const s=deepClone(state),d=s.developments.find(x=>x.id===id),writer=d&&getEmployee(s,d.writerId);if(!d||d.status!=='Complete'||!writer)return s;const cost=Math.max(12000,d.cost*.18);if(s.cash<cost)return s;
  d.status='Rewrite';d.daysRemaining=7;d.totalDays=7;d.rewriteCount=(d.rewriteCount||0)+1;s.cash-=cost;s.totalExpense+=cost;d.spent+=cost;sendMail(s,'Development Office',`Season rewrite started: ${d.title}`,`${writer.name} will spend one week rewriting the completed season package.`, 'development',{developmentId:d.id});return s;
}
export function refineDevelopment(state,id){
  const s=deepClone(state),d=s.developments.find(x=>x.id===id),writer=d&&getEmployee(s,d.writerId);if(!d||d.status!=='Complete'||d.refined||!writer)return s;const cost=Math.max(10000,Math.round(d.cost*.08));if(s.cash<cost)return s;
  d.status='Refining';d.daysRemaining=7;d.totalDays=7;d.refineCost=cost;s.cash-=cost;s.totalExpense+=cost;d.spent+=cost;sendMail(s,'Development Office',`Season refinement started: ${d.title}`,`${writer.name} is spending seven days polishing continuity, pacing and season-level structure. Production can continue using already-ready scripts.`, 'development',{developmentId:d.id});return s;
}
function developmentDay(s){
  s.developments.forEach(d=>{
    const writer=getEmployee(s,d.writerId);if(!writer)return;
    if(d.status==='Writing'){
      d.elapsedDays=(d.elapsedDays||0)+1;d.daysRemaining=Math.max(0,d.daysRemaining-1);
      const target=d.daysRemaining===0?d.episodes:Math.min(d.episodes,Math.floor(d.elapsedDays/Math.max(1,d.episodeInterval||1)));
      while((d.scriptedEpisodes||0)<target)completeEpisodeScript(s,d,writer,(d.scriptedEpisodes||0)+1);
      if(d.daysRemaining===0){while((d.scriptedEpisodes||0)<d.episodes)completeEpisodeScript(s,d,writer,(d.scriptedEpisodes||0)+1);d.status='Complete';const remaining=Math.max(0,d.cost-(d.spent||0));s.cash-=remaining;s.totalExpense+=remaining;d.spent=(d.spent||0)+remaining;sendMail(s,writer.name,`Season scripts complete: ${d.title}`,`${d.title}\n\n${d.summary}\n\nEpisodes: ${d.episodes}\nDuration: ${d.duration} minutes\nWriter: ${writer.name}\nSeason script rating: ${d.scriptStars.toFixed(1)} / 5 stars\nSuggested episode budget: $${d.suggestedBudgetPerEpisode.toLocaleString()}\n\nYou can proceed immediately or spend one additional week refining the completed season package.`, 'script',{developmentId:d.id});}
    }else if(d.status==='Rewrite'||d.status==='Refining'){
      d.daysRemaining=Math.max(0,d.daysRemaining-1);if(d.daysRemaining>0)return;
      const lift=d.status==='Refining'?clamp(.12+((writer.skills.writing||writer.overall)-60)/180, .08,.42):clamp(.22+((writer.skills.writing||writer.overall)-60)/130,.15,.6);
      d.scripts=(d.scripts||[]).map(sc=>({...sc,stars:Math.round(clamp(sc.stars+lift,1,5)*2)/2,notes:d.status==='Refining'?'Season-refined draft':'Rewritten draft'}));d.scriptStars=avg(d.scripts.map(x=>x.stars));d.refined=d.refined||d.status==='Refining';d.status='Complete';d.suggestedBudgetPerEpisode=suggestedEpisodeBudget(d);syncDevelopmentToProgram(s,d);sendMail(s,writer.name,`${d.refined?'Season refinement':'Rewrite'} complete: ${d.title}`,`Updated season script rating: ${d.scriptStars.toFixed(1)} / 5 stars.`, 'script',{developmentId:d.id,programId:d.programId});
    }
  });
}


export function productionPointBudget(p){return clamp(Math.round(12*((p?.budgetPerEpisode||1)/Math.max(1,p?.suggestedBudgetPerEpisode||p?.baseBudgetPerEpisode||1))),7,20);}
export function availableCastingPool(s,p){const hasCastingDirector=s.employees.some(e=>e.role==='Casting Director'),contracted=s.employees.filter(e=>e.dept==='Talent'),freelance=(s.candidateMarket||[]).filter(e=>e.dept==='Talent'&&(hasCastingDirector||e.overall<=78)).sort((a,b)=>b.overall-a.overall).slice(0,hasCastingDirector?14:6);return [...contracted.map(x=>({...x,source:'Contracted'})),...freelance.map(x=>({...x,source:'Freelance'}))].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);}
export function renameDevelopment(state,id,title){const s=deepClone(state),d=s.developments.find(x=>x.id===id);if(!d||!title?.trim())return s;d.title=title.trim();d.titleLocked=true;if(d.programId){const p=getProgram(s,d.programId);if(p)p.title=d.title;const ip=p&&getIP(s,p.ipId);if(ip&&ip.origin==='Original')ip.name=d.title;}return s;}
function recommendedStageFor(d){
  if(['Fantasy','Science Fiction','Historical'].includes(d.genre))return 'large';
  if(['Survival','Travel','Nature'].includes(d.genre))return 'exterior';
  if(['Comedy','Talk Show','Local News','National News','Sports Talk','Pregame','Postgame'].includes(d.genre))return 'small';
  return 'regular';
}
export function greenlightDevelopment(state,id,{showrunnerId=null,directorId=null,budgetPerEpisode=null}={}){
  const s=deepClone(state),d=s.developments.find(x=>x.id===id);if(!d||(d.scriptedEpisodes||0)<1||d.greenlit)return s;
  let ipId=d.ipId;
  if(!ipId||ipId==='new'){
    const ip={id:uid('ip'),name:d.title,origin:'Original',genre:d.genre,popularity:4,novelty:d.novelty??20,fatigue:0,prestige:5,fandom:3,flexibility:50,value:Math.max(150000,d.cost*1.4),affinity:{...d.target},seasons:1,identity:[d.genre,d.theme,d.angle],merchPotential:d.format==='Scripted'?40:d.format==='Reality'?35:10};s.ips.push(ip);ipId=ip.id;
  }
  const p=makeProgramDraft({title:d.title,format:d.format,genre:d.genre,episodes:d.episodes,duration:d.duration,target:d.target,art:d.art||ART_BY_FORMAT[d.format],font:d.font,p1:d.p1,p2:d.p2,ipId});
  p.scriptStars=d.scriptStars||2.5;p.scripts=(d.scripts||[]).map(x=>({...x}));p.pipeline.scripted=d.scriptedEpisodes||0;p.team.leadWriter=d.writerId;p.team.showrunner=showrunnerId;p.team.director=directorId;p.suggestedBudgetPerEpisode=d.suggestedBudgetPerEpisode||suggestedEpisodeBudget(d);p.budgetPerEpisode=Number(budgetPerEpisode)||p.suggestedBudgetPerEpisode;p.baseBudgetPerEpisode=p.suggestedBudgetPerEpisode;p.developmentId=d.id;p.recommendedStage=recommendedStageFor(d);p.productionNoveltyBoost=0;p.preProductionFinalized=false;p.status='Pre-production';
  d.greenlit=true;d.programId=p.id;s.programs.push(p);syncDevelopmentToProgram(s,d);sendMail(s,'Studio Office',`Greenlight approved: ${p.title}`,`${p.title} is now in pre-production. Build the production plan, cast the roles, select a stage and finalize promotion before filming begins.`, 'production',{programId:p.id});return s;
}
export function assignCreativeTeam(state,programId,{showrunnerId,directorId}={}){const s=deepClone(state),p=getProgram(s,programId);if(!p)return s;if(showrunnerId)p.team.showrunner=showrunnerId;if(directorId)p.team.director=directorId;return s;}
function stageFitFor(recommended,actual){if(!recommended||recommended===actual)return 1;if(recommended==='exterior'||actual==='exterior')return .76;const order=['small','regular','large'],a=order.indexOf(recommended),b=order.indexOf(actual),dist=Math.abs(a-b);if(dist===1)return actual==='large'?.93:.86;return .78;}
export function assignStage(state,programId,stageId){const s=deepClone(state),p=getProgram(s,programId),stage=getStage(s,stageId);if(!p||!stage||stage.occupiedBy)return s;p.stageId=stage.id;p.stageFit=stageFitFor(p.recommendedStage||'regular',stage.type);return s;}
export function setPreProductionPlan(state,programId,{allocation,technical,commercialsEnabled,promotionPlan,showrunnerId,directorId,stageId}={}){const s=deepClone(state),p=getProgram(s,programId);if(!p)return s;if(allocation){const used=Object.values(allocation).reduce((a,b)=>a+Number(b||0),0);if(used>productionPointBudget(p))return s;p.productionAllocation={...allocation};}if(technical)p.technical={...technical};if(typeof commercialsEnabled==='boolean')p.commercialsEnabled=commercialsEnabled;if(promotionPlan)p.promotionPlan=promotionPlan;if(showrunnerId)p.team.showrunner=showrunnerId;if(directorId)p.team.director=directorId;if(stageId){const stage=getStage(s,stageId);if(stage&&!stage.occupiedBy){p.stageId=stageId;p.stageFit=stageFitFor(p.recommendedStage||'regular',stage.type);}}p.preProductionFinalized=true;return s;}
export function canStartProduction(s,p){if(!p||p.status!=='Pre-production')return {ok:false,reason:'Not in pre-production'};if(!p.preProductionFinalized)return {ok:false,reason:'Finish the pre-production plan'};if((p.pipeline.scripted||0)<1)return {ok:false,reason:'Wait for at least one script'};if(!getEmployee(s,p.team?.showrunner))return {ok:false,reason:'Assign a showrunner'};if(!getEmployee(s,p.team?.director))return {ok:false,reason:'Assign a director'};const stage=getStage(s,p.stageId);if(!stage)return {ok:false,reason:`Select a ${p.recommendedStage||'regular'} stage`};if(stage.occupiedBy&&stage.occupiedBy!==p.id)return {ok:false,reason:`${stage.name} is already occupied`};const missing=(p.roles||[]).filter(r=>!p.castAssignments?.[r.id]);if(missing.length)return {ok:false,reason:`Cast ${missing.map(x=>x.name).join(', ')}`};return {ok:true,reason:'Ready'};}
export function beginProduction(state,programId){const s=deepClone(state),p=getProgram(s,programId),check=canStartProduction(s,p);if(!check.ok)return s;const stage=getStage(s,p.stageId);if(stage)stage.occupiedBy=p.id;p.status='Production';p.productionStart=s.date;p.pipeline.pre=0;p.pipeline.filmed=0;p.pipeline.ready=0;const promo={None:0,Light:70000,Standard:180000,Heavy:420000}[p.promotionPlan]??180000;if(promo&&s.cash>=promo){s.cash-=promo;s.totalExpense+=promo;p.marketingSpend+=promo;p.awareness=clamp(p.awareness+promo/60000,0,100)}sendMail(s,'Production Office',`Principal production started: ${p.title}`,`${p.title} is now in active production on ${stage?.name||'stage'}. Episodes will move through pre-production, filming and post as scripts become available.`, 'production',{programId:p.id});return s;}
export function startStageBuild(state,type='regular'){const s=deepClone(state),def=STAGE_TYPES[type];if(!def)return s;const cost=def.cost,name=`${def.label} ${(s.stages||[]).filter(x=>x.type===type).length+(s.stageProjects||[]).filter(x=>x.type===type).length+1}`;if(s.cash<cost*.25)return s;s.cash-=cost*.25;s.totalExpense+=cost*.25;s.stageProjects=s.stageProjects||[];s.stageProjects.push({id:uid('stageproj'),type,name,daysRemaining:def.days,totalDays:def.days,cost,paid:cost*.25});sendMail(s,'Facilities',`Stage construction started: ${name}`,`${def.label} construction will take about ${def.days} days.`, 'facility');return s;}

export function startFacilityBuild(state,key){const s=deepClone(state);if(s.facilityProjects.some(x=>x.key===key))return s;const defs={studios:{name:'Soundstage',days:60,cost:1800000},post:{name:'Post-production Suite',days:40,cost:900000},newsroom:{name:'Newsroom',days:45,cost:1200000},vfx:{name:'VFX Facility',days:75,cost:2400000},wardrobe:{name:'Wardrobe Department',days:28,cost:500000},setShop:{name:'Set Construction Shop',days:35,cost:800000},archive:{name:'Archive',days:24,cost:420000},research:{name:'Research Lab',days:42,cost:750000}},d=defs[key];if(!d)return s;const level=(s.facilities[key]||0)+1,cost=d.cost*level;if(s.cash<cost*.25)return s;s.cash-=cost*.25;s.totalExpense+=cost*.25;s.facilityProjects.push({id:uid('fac'),kind:'facility',key,name:`${d.name} L${level}`,daysRemaining:d.days,totalDays:d.days,cost,paid:cost*.25});sendMail(s,'Facilities',`Construction started: ${d.name}`,`Level ${level} construction is underway. Estimated completion: ${d.days} days.`, 'facility');return s;}
function facilityDay(s){s.facilityProjects.forEach(p=>{p.daysRemaining--;if(p.daysRemaining<=0){if(p.key==='studios'){const type='regular',name=`Regular Stage ${(s.stages||[]).filter(x=>x.type===type).length+1}`;s.stages=s.stages||[];s.stages.push({id:uid('stage'),name,type,occupiedBy:null});s.facilities.studios=s.stages.length;}else s.facilities[p.key]=(s.facilities[p.key]||0)+1;const rem=p.cost-p.paid;s.cash-=rem;s.totalExpense+=rem;sendMail(s,'Facilities',`Construction complete: ${p.name}`,`${p.name} is operational.`, 'facility')}});s.facilityProjects=s.facilityProjects.filter(x=>x.daysRemaining>0);s.stageProjects=s.stageProjects||[];s.stageProjects.forEach(p=>{p.daysRemaining--;if(p.daysRemaining<=0){const rem=p.cost-p.paid;s.cash-=rem;s.totalExpense+=rem;s.stages.push({id:uid('stage'),name:p.name,type:p.type,occupiedBy:null});s.facilities.studios=s.stages.length;sendMail(s,'Facilities',`Stage complete: ${p.name}`,`${p.name} is operational and available for pre-production.`, 'facility')}});s.stageProjects=s.stageProjects.filter(x=>x.daysRemaining>0);}

export function startStaffSearch(state,role){const s=deepClone(state);if(!role||s.staffSearches.some(x=>x.role===role&&x.status==='Searching'))return s;const fee=12000,days=3+Math.round(seeded(`${s.date}-${role}`)()*5);if(s.cash<fee)return s;s.cash-=fee;s.totalExpense+=fee;s.staffSearches.push({id:uid('search'),role,status:'Searching',daysRemaining:days,totalDays:days});sendMail(s,'Talent & HR',`Search opened: ${role}`,`Recruiters have started sourcing candidates for ${role}. Expected shortlist: ${days} days.`, 'hiring');return s;}
function searchDay(s){s.staffSearches.forEach(x=>{if(x.status!=='Searching')return;x.daysRemaining--;if(x.daysRemaining>0)return;x.status='Complete';x.completedDate=s.date;const exact=s.candidateMarket.filter(c=>c.role===x.role),near=s.candidateMarket.filter(c=>c.role.includes(x.role)||x.role.includes(c.role)),pool=(exact.length?exact:near).filter(c=>!s.employees.some(e=>e.id===c.id)).slice().sort((a,b)=>b.overall-a.overall),shortlist=pool.slice(0,4).map(c=>c.id);s.candidateShortlists.push({id:uid('short'),searchId:x.id,role:x.role,candidateIds:shortlist,date:s.date});sendMail(s,'Talent & HR',`Candidate shortlist ready: ${x.role}`,shortlist.length?`Recruiting found ${shortlist.length} candidates. Their initial demands and market salary are available in Organization → People.`:'No suitable candidates were found.','hiring',{searchId:x.id});});}
export function startNegotiation(state,candidateId,offerSalary,years=3,bonus=0,backend=0,creativeControl=0){
  const s=deepClone(state),c=s.candidateMarket.find(x=>x.id===candidateId);if(!c||s.negotiations.some(n=>n.candidateId===candidateId&&['Negotiating','Agreed'].includes(n.status)))return s;
  const existing=[...s.negotiations].reverse().find(n=>n.candidateId===candidateId&&n.status==='Countered');
  const days=existing?1:2+Math.floor(seeded(`${s.date}-${candidateId}-neg`)()*3);
  const payload={offerSalary:Number(offerSalary),years:Number(years),bonus:Number(bonus),backend:Number(backend),creativeControl:Number(creativeControl)};
  if(existing){Object.assign(existing,payload,{status:'Negotiating',daysRemaining:days,totalDays:days,round:(existing.round||1)+1});sendMail(s,'Business Affairs',`Counteroffer response submitted: ${c.name}`,`${c.name}'s representatives will respond in ${days} day${days===1?'':'s'}.`, 'hiring',{negotiationId:existing.id,candidateId:c.id});}
  else{s.negotiations.push({id:uid('neg'),candidateId,status:'Negotiating',daysRemaining:days,totalDays:days,round:1,...payload});sendMail(s,'Business Affairs',`Offer submitted: ${c.name}`,`${c.name}'s representatives are reviewing your offer. Response expected in ${days} days.`, 'hiring');}
  return s;
}
export function continueNegotiation(state,negotiationId,offer){const n=state.negotiations.find(x=>x.id===negotiationId);return n?startNegotiation(state,n.candidateId,offer.salary,offer.years,offer.bonus,offer.backend,offer.creativeControl):state;}
function negotiationDay(s){
  s.negotiations.forEach(n=>{if(n.status!=='Negotiating')return;n.daysRemaining--;if(n.daysRemaining>0)return;const c=s.candidateMarket.find(x=>x.id===n.candidateId);if(!c){n.status='Closed';return}
    const salaryRatio=n.offerSalary/(c.ask||1),bonusValue=(n.bonus||0)/Math.max(1,c.ask),backendValue=(n.backend||0)-(c.demands?.backend||0),controlValue=(n.creativeControl||0)-(c.demands?.creativeControl||0),termValue=(n.years||3)-(c.demands?.years||3),prestige=(s.network.prestige||5)/100,fame=(c.popularity||c.overall*.3)/100,r=seeded(`${s.date}-${c.id}-${n.offerSalary}-${n.round||1}`)();
    const packageScore=salaryRatio*.68+bonusValue*.08+backendValue*.018+controlValue*.0015+termValue*.025+prestige*(.14-fame*.06)+r*.07;
    if(packageScore>=.74){n.status='Agreed';sendMail(s,c.name,`Terms agreed — ${c.name}`,`${c.name}'s representatives accept the negotiated terms.\n\nRole: ${c.role}\nSalary: $${Math.round(n.offerSalary).toLocaleString()}/year\nTerm: ${n.years} years\nSigning bonus: $${Math.round(n.bonus).toLocaleString()}\nBackend: ${n.backend}%\nCreative control: ${n.creativeControl}%\n\nThe agreement is NOT signed yet. Sign the person or break negotiations.`, 'hiring',{negotiationId:n.id,candidateId:c.id,mailAction:'signing'});return;}
    if(packageScore<.54||salaryRatio<.68){n.status='Rejected';sendMail(s,c.name,`Offer declined — ${c.name}`,`${c.name}'s representatives consider the offer too far from acceptable terms. You may reopen talks later.`, 'hiring',{candidateId:c.id});return;}
    const leverage=clamp(prestige*.35+(1-fame)*.18,0,.28),targetSalary=Math.round((c.ask*(.96-leverage)+n.offerSalary*(.04+leverage))/5000)*5000,counterSalary=Math.max(n.offerSalary,Math.min(c.ask,targetSalary));n.status='Countered';n.counterOffer={salary:counterSalary,years:Math.max(1,Math.round((n.years+(c.demands?.years||3))/2)),bonus:Math.round(((n.bonus||0)+(c.demands?.bonus||0))/2/5000)*5000,backend:Math.max(n.backend,Math.round(((n.backend||0)+(c.demands?.backend||0))/2*2)/2),creativeControl:Math.max(n.creativeControl,Math.round(((n.creativeControl||0)+(c.demands?.creativeControl||0))/20)*10)};
    sendMail(s,c.name,`Counteroffer — ${c.name}`,`${c.name}'s representatives are interested, but not at your current terms.\n\nYour salary offer: $${Math.round(n.offerSalary).toLocaleString()}\nTheir original ask: $${Math.round(c.ask).toLocaleString()}\nCounter salary: $${Math.round(n.counterOffer.salary).toLocaleString()}\nTerm: ${n.counterOffer.years} years\nSigning bonus: $${Math.round(n.counterOffer.bonus).toLocaleString()}\nBackend: ${n.counterOffer.backend}%\nCreative control: ${n.counterOffer.creativeControl}%\n\nContinue negotiating or walk away.`, 'hiring',{negotiationId:n.id,candidateId:c.id,mailAction:'counter'});
  });
}
export function signNegotiation(state,negotiationId){const s=deepClone(state),n=s.negotiations.find(x=>x.id===negotiationId);if(!n||n.status!=='Agreed')return s;const c=s.candidateMarket.find(x=>x.id===n.candidateId);if(!c)return s;c.salary=n.offerSalary;c.contractYears=n.years;c.backend=n.backend;c.creativeControl=n.creativeControl;c.contractStart=s.date;s.employees.push(c);s.candidateMarket=s.candidateMarket.filter(x=>x.id!==c.id);s.cash-=n.bonus;s.totalExpense+=n.bonus;n.status='Signed';sendMail(s,'HR',`Contract signed: ${c.name}`,`${c.name} officially joins ${s.network.initials} as ${c.role}.`, 'hiring',{employeeId:c.id});return s;}
export function breakNegotiation(state,negotiationId){const s=deepClone(state),n=s.negotiations.find(x=>x.id===negotiationId);if(n&&['Agreed','Negotiating'].includes(n.status)){n.status='Broken';const c=s.candidateMarket.find(x=>x.id===n.candidateId);sendMail(s,'Business Affairs',`Negotiations ended${c?`: ${c.name}`:''}`,'The network walked away from the negotiation.','hiring');}return s;}
export function hireCandidate(state,id,offerSalary,years=3,bonus=0,backend=0,creativeControl=0){return {state:startNegotiation(state,id,offerSalary,years,bonus,backend,creativeControl),accepted:null};}
export function fireEmployee(state,id){const s=deepClone(state),i=s.employees.findIndex(x=>x.id===id);if(i<0)return s;const e=s.employees.splice(i,1)[0],sev=(e.salary||0)*.20;s.cash-=sev;s.totalExpense+=sev;sendMail(s,'HR',`${e.name} released`,`${e.name} has left the network. Severance: $${Math.round(sev).toLocaleString()}.`,'hiring');return s;}

export function audition(state,programId,talentId,roleId=null){const s=deepClone(state),p=getProgram(s,programId),talent=getPerson(s,talentId);if(!p||!talent||talent.dept!=='Talent')return s;const role=roleId||p.roles?.[0]?.id||'lead',r=seeded(`${p.id}-${role}-${talent.id}-chemistry`),fit=(talent.skills.acting||talent.skills.charisma||talent.overall)*.65+(talent.popularity||30)*.15+r()*20;p.auditions=p.auditions||[];p.auditions=p.auditions.filter(x=>!(x.talentId===talentId&&x.roleId===role));p.auditions.push({talentId,roleId:role,fit:clamp(fit,20,98),chemistry:clamp(40+r()*55,20,98)});return s;}
export function castTalent(state,programId,talentId,roleId=null){const s=deepClone(state),p=getProgram(s,programId),person=getPerson(s,talentId);if(!p||!person)return s;const role=roleId||p.roles?.[0]?.id||'lead',a=p.auditions?.find(x=>x.talentId===talentId&&x.roleId===role);if(a){const employed=!!getEmployee(s,talentId);if(!employed){const fee=Math.max(25000,Math.round((person.ask||person.marketAverage||200000)*(p.episodes/22)*.55));if(s.cash<fee)return s;s.cash-=fee;s.totalExpense+=fee;p.guestTalentCosts=(p.guestTalentCosts||0)+fee;p.guestTalentIds=[...new Set([...(p.guestTalentIds||[]),talentId])];}p.castAssignments=p.castAssignments||{};p.castAssignments[role]=talentId;p.cast=Object.values(p.castAssignments);p.team.leadTalent=p.castAssignments[p.roles?.[0]?.id]||p.cast[0]||null;const aud=p.cast.map(id=>p.auditions?.find(x=>x.talentId===id)).filter(Boolean);p.chemistry=aud.length?avg(aud.map(x=>x.chemistry)):50;}return s;}

function productionDay(s){
  const active=s.programs.filter(p=>p.status==='Production');if(!active.length)return;
  active.forEach(p=>{const sr=getEmployee(s,p.team.showrunner),director=getEmployee(s,p.team.director),stage=getStage(s,p.stageId),durationScale=p.duration/60,management=((sr?.skills.management||sr?.overall||55)+(director?.skills.management||director?.overall||55))/120,travel=p.travel==='High'?(researched(s,'t_remote')?.9:.72):p.travel==='Medium'?.86:1,scriptCap=Math.max(0,p.pipeline.scripted||0),preRate=.18*management/durationScale,filmRate=.13*management*travel/durationScale,postRate=.15*(1+s.facilities.post*.25)*(researched(s,'t_cloud')?1.2:1)/durationScale,beforeReady=p.pipeline.ready;
    if(p.pipeline.pre<scriptCap)p.pipeline.pre=clamp(p.pipeline.pre+preRate,0,scriptCap);if(p.pipeline.filmed<Math.min(scriptCap,p.pipeline.pre))p.pipeline.filmed=clamp(p.pipeline.filmed+filmRate,0,Math.min(scriptCap,p.pipeline.pre));if(p.pipeline.ready<Math.min(scriptCap,p.pipeline.filmed))p.pipeline.ready=clamp(p.pipeline.ready+postRate,0,Math.min(scriptCap,p.pipeline.filmed));
    const daily=Math.max(500,(p.budgetPerEpisode*Math.max(1,scriptCap))/(Math.max(20,p.episodes*6*durationScale)));s.cash-=daily;s.totalExpense+=daily;p.productionSpend+=daily;
    if(Math.floor(beforeReady)<1&&Math.floor(p.pipeline.ready)>=1)sendMail(s,'Production Office',`First episode delivered: ${p.title}`,`Episode 1 is ready. You may schedule the premiere while writing and production continue.`, 'production',{programId:p.id});
    if(p.pipeline.ready>=p.episodes-.001&&scriptCap>=p.episodes){p.pipeline.ready=p.episodes;p.status='Ready';p.quality=executionQuality(s,p);if(stage&&stage.occupiedBy===p.id)stage.occupiedBy=null;const ip=getIP(s,p.ipId);if(ip)ip.novelty=clamp(ip.novelty+(p.productionNoveltyBoost||0),0,100);const gain=.15+(p.quality/100)*.2;s.network.expertise[p.format]=clamp((s.network.expertise[p.format]||0)+gain,0,10);sendMail(s,'Production Office',`Season delivered: ${p.title}`,`All ${p.episodes} episodes are broadcast-ready. Execution estimate: ${Math.round(p.quality)}/100.`, 'production',{programId:p.id});}
  });
}
function revealReception(s,p){
  if(p.premiered)return;const ip=getIP(s,p.ipId),sr=getEmployee(s,p.team?.showrunner),director=getEmployee(s,p.team?.director);p.quality=p.quality||executionQuality(s,p);const r=seeded(`premiere-${p.id}-${s.date}`),viewer=clamp(p.quality*.55+(p.scriptStars*20)*.18+(p.chemistry||50)*.11+(ip?.popularity||5)*.08+(ip?.novelty||30)*.08+(r()-.5)*10,25,96),critic=clamp(p.quality*.48+(p.scriptStars*20)*.30+(sr?.skills?.vision||60)*.10+(director?.skills?.direction||60)*.08+(ip?.novelty||30)*.08+(r()-.5)*12-8-(1-(p.stageFit||1))*18,12,99);p.viewer=Math.round(viewer);p.critic=Math.round(critic);p.premiered=true;
  sendMail(s,'Audience Research',`${p.title} aired for the first time!`,`The premiere is complete. Audience Research has the first audience, share, slot position and reception scores ready.\n\nOpen the results when you are ready.`, 'premiere',{programId:p.id,premiereReveal:true});
}


const startMinutes=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
function blockEnd(start,duration){const mins=startMinutes(start)+duration,dayShift=Math.floor(mins/1440),end=mins%1440;return `${dayShift?'+1 ':''}${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;}
export const scheduleBlockEnd=(b,p)=>blockEnd(b.start,p?.duration||b.duration||30);
export function isSchedulable(p){return !!p&&(p.acquired||Math.floor(p.pipeline.ready-p.pipeline.aired)>0||p.status==='Production'||p.genre==='Live Sports');}
function nextDateForDay(from,day){const target=DAYS.indexOf(day),cur=dayIndex(from),delta=(target-cur+7)%7;return addDays(from,delta);}
function recurrenceEnd(startDate,weeks){return addDays(startDate,Math.max(0,Number(weeks||1)*7-1));}
export function setNetworkLaunchDate(state,date){const s=deepClone(state);if(!date||date<s.date)return s;if(s.network.launchDate&&s.date>=s.network.launchDate)return s;s.network.launchDate=date;sendMail(s,'Master Control',`Network launch scheduled: ${date}`,`${s.network.initials} will begin regular broadcasting on ${date}. Until then, programming can be planned but no broadcast revenue or transmission operating cost will be recognized.`, 'system');return s;}
export function scheduleRecurring(state,{programId,start,recurrence='once',days=[],weeks=1,asLongAsEpisodes=false,primaryDay}={}){
  const s=deepClone(state),p=getProgram(s,programId);if(!s.network.launchDate||!p||!isSchedulable(p))return s;const selectedDays=recurrence==='daily'?(days.length?days:[primaryDay||DAYS[dayIndex(s.date)]]):[primaryDay||DAYS[dayIndex(s.date)]],startM=startMinutes(start),endM=startM+p.duration;if(startM<720&&endM>720)return s;
  const remaining=Math.max(1,p.episodes-Math.floor(p.pipeline.aired||0)),perWeek=Math.max(1,selectedDays.length),autoWeeks=Math.ceil(remaining/perWeek),runWeeks=asLongAsEpisodes?autoWeeks:Math.max(1,Number(weeks||1)),baseDate=s.date>s.network.launchDate?s.date:s.network.launchDate,firstDate=nextDateForDay(baseDate,selectedDays[0]),rule={id:uid('rule'),programId:p.id,start,recurrence,days:selectedDays,weeks:runWeeks,asLongAsEpisodes,startDate:firstDate,endDate:recurrence==='once'?firstDate:recurrenceEnd(firstDate,runWeeks),maxOccurrences:recurrence==='once'?1:asLongAsEpisodes?remaining:runWeeks*perWeek,occurrences:0};
  for(const day of selectedDays){const blocks=s.scheduleBlocks[day]||[],overlap=blocks.some(b=>{const bp=getProgram(s,b.programId),a=startM,c=endM,x=startMinutes(b.start),y=x+(bp?.duration||b.duration||30);return a<y&&c>x});if(overlap)return state;}
  s.scheduleRules.push(rule);for(const day of selectedDays)(s.scheduleBlocks[day]||[]).push({id:uid('slot'),ruleId:rule.id,programId:p.id,start,duration:p.duration,recurrence});selectedDays.forEach(day=>s.scheduleBlocks[day].sort((a,b)=>startMinutes(a.start)-startMinutes(b.start)));return s;
}
export function scheduleProgram(state,day,start,programId){return scheduleRecurring(state,{programId,start,recurrence:'once',primaryDay:day,weeks:1});}
export function removeScheduleBlock(state,day,blockId){const s=deepClone(state),block=(s.scheduleBlocks[day]||[]).find(x=>x.id===blockId),ruleId=block?.ruleId;if(ruleId){Object.keys(s.scheduleBlocks).forEach(d=>s.scheduleBlocks[d]=s.scheduleBlocks[d].filter(x=>x.ruleId!==ruleId));s.scheduleRules=s.scheduleRules.filter(x=>x.id!==ruleId);}else s.scheduleBlocks[day]=(s.scheduleBlocks[day]||[]).filter(x=>x.id!==blockId);return s;}
export function scheduleRuleSummary(s,rule){const p=getProgram(s,rule.programId);return {title:p?.title||'Program',days:rule.days.join(', '),start:rule.start,endDate:rule.endDate,maxOccurrences:rule.maxOccurrences,remaining:Math.max(0,rule.maxOccurrences-rule.occurrences)};}
function ruleActive(s,b){const r=s.scheduleRules.find(x=>x.id===b.ruleId);if(!r)return true;if(r.occurrences>=r.maxOccurrences)return false;if(s.date<r.startDate||s.date>r.endDate)return false;return r.days.includes(DAYS[dayIndex(s.date)]);}

function baseAdRevenue(s,p,audience,band){if(p.commercialsEnabled===false)return 0;const c=s.adAgencyContract;if(!c)return 0;const ag=s.agencies.find(x=>x.id===c.agencyId);if(!ag)return 0;const gross=audience/1000*ag.cpm*(SLOT_MULT[band]||.7)*clamp((p.adLoad??12)/12,.65,1.6);return gross*(1-ag.baseShare);}
function sponsorRevenue(s,p,audience){return s.sponsorships.filter(x=>x.status==='Active'&&x.programId===p.id&&x.weeksRemaining>0).reduce((sum,x)=>sum+x.fixed/(x.totalWeeks*7)+(audience/1000000)*x.variablePerMillion,0);}
function slotCompetition(s,band,own){
  const rivals=s.competitorRatings.filter(r=>r.date===s.date&&r.band===band),rank=(scopeKey,ownValue)=>1+rivals.filter(r=>(r[scopeKey]||0)>ownValue).length,total=(scopeKey,ownValue)=>ownValue+rivals.reduce((a,r)=>a+(r[scopeKey]||0),0);
  const totals={national:total('audience',own.audience),state:total('stateAudience',own.scopes.state),local:total('localAudience',own.scopes.local)};
  return {rankNational:rank('audience',own.audience),rankState:rank('stateAudience',own.scopes.state),rankLocal:rank('localAudience',own.scopes.local),shareNational:own.audience/Math.max(1,totals.national),shareState:own.scopes.state/Math.max(1,totals.state),shareLocal:own.scopes.local/Math.max(1,totals.local)};
}
function airDay(s){
  if(!s.network.launchDate||s.date<s.network.launchDate){s.lastDayRevenue=0;s.lastDayAudience=0;return;}
  const d=DAYS[dayIndex(s.date)],blocks=(s.scheduleBlocks?.[d]||[]).filter(b=>ruleActive(s,b));let totalAudience=0,revenue=0,homeStateAudience=0,localAudience=0;const reportRows=[];
  blocks.forEach(b=>{const p=getProgram(s,b.programId);if(!p)return;const rule=s.scheduleRules.find(x=>x.id===b.ruleId),available=Math.floor(p.pipeline.ready)-Math.floor(p.pipeline.aired),seasonComplete=Math.floor(p.pipeline.aired)>=p.episodes;if(available<=0&&!seasonComplete&&p.genre!=='Live Sports'){sendMail(s,'Master Control',`Missed airing: ${p.title}`,`${p.title} could not air at ${b.start}: no broadcast-ready episode/run remained. The recurrence remains active.`, 'warning',{programId:p.id});return;}
    const wasPremiered=p.premiered;revealReception(s,p);const band=slotBand(b.start),r=calcAudience(s,p,b.start,s.date);if(seasonComplete){r.audience*=.72;r.scopes.state*=.72;r.scopes.local*=.72;Object.keys(r.demoShares).forEach(k=>r.demoShares[k]*=.72);}const comp=slotCompetition(s,band,r);p.lastAudience=r.audience;p.totalAudience=(p.totalAudience||0)+r.audience;p.airings=(p.airings||0)+1;totalAudience+=r.audience;homeStateAudience+=r.scopes.state;localAudience+=r.scopes.local;if(Math.floor(p.pipeline.aired)<p.episodes)p.pipeline.aired=Math.min(p.episodes,p.pipeline.aired+1);if(rule)rule.occurrences++;
    const ip=getIP(s,p.ipId);if(ip){const reception=(p.viewer+p.critic)/2,buzz=(reception-62)/38+(r.audience/Math.max(1,networkReachHouseholds(s))-.06)*4;p.momentum=clamp((p.momentum||0)*.82+buzz,-30,30);ip.popularity=clamp(ip.popularity+buzz*.14,0,100);ip.novelty=clamp(ip.novelty-.06,0,100);if(ip.novelty<25)ip.fatigue=clamp((ip.fatigue||0)+.04,0,100);ip.value=Math.max(100000,ip.value*(1+buzz*.002));}p.awareness=clamp((p.awareness||8)+.04+r.audience/Math.max(1,networkReachHouseholds(s))*.4,0,100);const adRev=baseAdRevenue(s,p,r.audience,band),spRev=sponsorRevenue(s,p,r.audience),showRev=adRev+spRev;p.revenue+=showRev;revenue+=showRev;const epNo=Math.min(p.episodes,Math.max(1,Math.floor(p.pipeline.aired))),epScript=p.scripts?.find(x=>x.episode===epNo),scoreRand=seeded(`episode-score-${p.id}-${epNo}-${s.date}`),scriptDelta=((epScript?.stars||p.scriptStars||2.5)-(p.scriptStars||2.5))*3,epViewer=clamp(p.viewer+scriptDelta+(scoreRand()-.5)*7,20,99),epCritic=clamp(p.critic+scriptDelta*1.25+(scoreRand()-.5)*9,10,100);const hist={date:s.date,episode:epNo,audience:r.audience,stateAudience:r.scopes.state,localAudience:r.scopes.local,viewer:epViewer,critic:epCritic,novelty:ip?.novelty||0,popularity:ip?.popularity||0,...comp};p.episodeHistory.push(hist);const scored=p.episodeHistory.length;p.viewer=avg(p.episodeHistory.map(x=>x.viewer));p.critic=avg(p.episodeHistory.map(x=>x.critic));s.ratingsLog.push({date:s.date,day:d,start:b.start,band,programId:p.id,audience:r.audience,stateAudience:r.scopes.state,localAudience:r.scopes.local,viewer:epViewer,critic:epCritic,...comp});reportRows.push({title:p.title,start:b.start,band,audience:r.audience,share:comp.shareLocal,rank:comp.rankLocal,viewer:epViewer/10,critic:epCritic,premiere:!wasPremiered});
  });
  s.cash+=revenue;s.totalRevenue+=revenue;s.lastDayRevenue=revenue;s.lastDayAudience=totalAudience;s.weeklyAudience=(s.weeklyAudience||0)*.78+totalAudience*.22;s.ratingsLog=s.ratingsLog.slice(-5000);s.networkAudienceHistory.push({date:s.date,national:totalAudience,state:homeStateAudience,local:localAudience,revenue});s.networkAudienceHistory=s.networkAudienceHistory.slice(-1460);
  if(reportRows.length)sendMail(s,'Audience Research',`Daily ratings report — ${s.date}`,`Your complete daily performance report is ready for ${reportRows.length} aired program${reportRows.length===1?'':'s'}.`, 'ratings',{reportRows});
}

function generateCompetitorPrograms(c){if(c.programs?.length)return;const sp=c.specialty;const formats=sp?[sp]:['Scripted','Reality','News','Live','Contests'];const names={morning:['Morning Desk','First Light','Daybreak Live'],afternoon:['Afternoon Live','Daytime Club','The Daily Game'],access:['Evening Report','Access Tonight','Family Challenge'],prime:['City Lines','Survival Coast','National Match','The Great Quiz','Frontline Report'],late:['Night Desk','After Hours','Late Live']};c.programs=[];['morning','afternoon','access','prime','late'].forEach((band,bi)=>{const count=band==='prime'&&sp!=='Sports'?2:1;for(let i=0;i<count;i++){const format=sp||formats[(bi+i)%formats.length],genre=format==='Sports'?(band==='prime'?'Live Sports':'Sports Talk'):format==='News'?(band==='morning'?'Morning News':'National News'):format==='Documentaries'?'Nature':format==='Scripted'?(i?'Comedy':'Drama'):format==='Reality'?'Survival':format==='Contests'?'General Knowledge':'Talk Show';c.programs.push({id:`${c.id}-${band}-${i}`,title:`${c.name.split(' ')[0]} ${names[band][(bi+i)%names[band].length]}`,format,genre,band,viewer:clamp(55+c.strength*.35+(i?2:0),45,94),critic:clamp(40+c.prestige*.45+(format==='Documentaries'?10:0),25,98),baseAppeal:clamp(c.strength+(format===c.specialty?10:0)+(i?2:0),30,98),popularity:clamp(c.strength+(format===c.specialty?8:0)+(i?2:0),20,96),novelty:clamp(18+((bi*13+i*9+c.id.length*3)%55),8,84)});}});}
function competitorDay(s){const rDate=s.date;let nationalTotal=0,stateTotal=0,localTotal=0;(s.competitors||[]).forEach(c=>{generateCompetitorPrograms(c);let dayTotal=0,state=0,local=0;c.programs.forEach(p=>{const r=seeded(`${rDate}-${p.id}`),bandMult={morning:.72,afternoon:.65,access:.83,prime:1.18,late:.58}[p.band],scopeBase=c.scope==='Local'?220000:c.scope==='State'?900000:c.scope==='Specialist'?2400000:5200000,aud=scopeBase*(p.baseAppeal/100)*bandMult*(.86+r()*.28),stateAud=c.scope==='Local'?aud:c.scope==='State'?aud:aud*.08,localAud=c.scope==='Local'?aud:c.scope==='State'?aud*.24:aud*.018;dayTotal+=aud;state+=stateAud;local+=localAud;const expected=scopeBase*(p.baseAppeal/100)*bandMult;p.popularity=clamp((p.popularity||50)+(aud/Math.max(1,expected)-1)*.18,5,100);p.novelty=clamp((p.novelty||30)-.012,3,100);s.competitorRatings.push({date:rDate,networkId:c.id,programId:p.id,title:p.title,format:p.format,genre:p.genre,band:p.band,audience:aud,stateAudience:stateAud,localAudience:localAud,viewer:p.viewer/10,critic:p.critic,popularity:p.popularity,novelty:p.novelty});});c.audience.yesterday=dayTotal;c.audience.month=(c.audience.month||0)*.92+dayTotal*.08;c.audience.year=(c.audience.year||0)+dayTotal;c.revenueYTD=(c.revenueYTD||0)+dayTotal/1000*14;const month=rDate.slice(0,7),existing=c.monthlyAudience.find(x=>x.month===month);if(existing){existing.total+=dayTotal;existing.days++;}else c.monthlyAudience.push({month,total:dayTotal,days:1});nationalTotal+=dayTotal;stateTotal+=state;localTotal+=local;});s.competitorRatings=s.competitorRatings.slice(-25000);}

function researchDay(s){if(!s.research)return;const cio=s.employees.find(e=>e.role==='Chief Innovation Officer');if(!cio){sendMail(s,'Technology','Research paused — CIO required','Hire a Chief Innovation Officer to initiate and manage research.','warning');s.research=null;return;}const t=s.tech.find(x=>x.id===s.research.techId);if(!t){s.research=null;return}const techStaff=s.employees.filter(e=>e.dept==='Technology'),speed=Math.max(.12,(cio.skills.research||cio.overall)/155+avg(techStaff.map(e=>e.skills.technology||e.overall))/300)*(1+s.facilities.research*.08),cost=Math.max(1200,(t.cost||500000)/180);t.progress=clamp((t.progress||0)+speed,0,100);s.cash-=cost;s.totalExpense+=cost;if(t.progress>=100){t.researched=true;s.research=null;sendMail(s,'Technology',`Research completed: ${t.name}`,`${t.name} is now operational.`, 'research');if(t.id==='t_stream')s.streaming.unlocked=true;}}
export function startResearch(state,id){const s=deepClone(state),t=s.tech.find(x=>x.id===id),cio=s.employees.find(e=>e.role==='Chief Innovation Officer');if(!t||t.researched||s.research||!cio)return s;s.research={techId:id,start:s.date};sendMail(s,'Innovation Office',`Research initiated: ${t.name}`,`${cio.name} has opened the research project.`, 'research');return s;}

function dailyOverhead(s){const payroll=s.employees.reduce((sum,e)=>sum+(e.salary||0),0)/365,f=s.facilities,facilities=(f.studios*260000+f.post*180000+f.newsroom*240000+f.vfx*300000+f.wardrobe*90000+f.setShop*120000+f.control*150000+f.archive*70000+f.research*110000)/365,rights=s.contracts.reduce((sum,c)=>sum+(c.annualCost||0)/365,0),broadcastOps=(s.network.launchDate&&s.date>=s.network.launchDate)?2500:0,expense=payroll+facilities+rights+broadcastOps;s.cash-=expense;s.totalExpense+=expense;s.lastDayExpense=expense;}
function licensingDay(s){s.licenses.forEach(l=>{if(l.status==='Active'){const daily=l.annualRevenue/365;s.cash+=daily;s.totalRevenue+=daily;const p=getProgram(s,l.programId);if(p)p.licensingRevenue=(p.licensingRevenue||0)+daily}});s.merchDeals.forEach(m=>{if(m.status==='Active'){const ip=getIP(s,m.ipId);if(!ip)return;const daily=(m.baseAnnual||0)/365*(.6+ip.fandom/100*.6);s.cash+=daily;s.totalRevenue+=daily}});s.sponsorships.forEach(x=>{if(x.status==='Active'&&x.weeksRemaining>0)x.weeksRemaining-=1/7;});}

function distributionDay(s){s.distributionProjects.forEach(p=>{p.daysRemaining--;if(p.daysRemaining>0)return;const st=s.states.find(x=>x.code===p.state),targets=p.areaId==='all'?st.areas:st.areas.filter(a=>a.id===p.areaId);if(p.kind==='rights'){targets.forEach(a=>{a.rightsOwned=true;a.rightsPending=false});if(p.areaId==='all')st.allStateRights=true;sendMail(s,'Distribution',`Emission rights secured: ${st.code}`,p.areaId==='all'?'Statewide emission rights are active. You still need antennas in each area to create technical reach.':`${targets[0]?.name||'Market'} rights are active. Build an antenna to reach households.`, 'distribution');}else if(p.kind==='antenna'){targets.forEach(a=>{a.antennaLevel=p.level;a.antennaPending=false;a.reachPct=[0,.46,.76,1][p.level]||1});sendMail(s,'Engineering',`Antenna operational: ${targets[0]?.name||st.code}`,`Level ${p.level} antenna is now transmitting.`, 'distribution');}st.coverage=st.areas.reduce((sum,a)=>sum+a.share*(a.reachPct||0),0);});s.distributionProjects=s.distributionProjects.filter(x=>x.daysRemaining>0);}
export function startEmissionRights(state,code,areaId='all'){const s=deepClone(state),st=s.states.find(x=>x.code===code);if(!st)return s;const targets=areaId==='all'?st.areas:st.areas.filter(a=>a.id===areaId),missing=targets.filter(a=>!a.rightsOwned&&!a.rightsPending);if(!missing.length)return s;const households=missing.reduce((a,x)=>a+x.households,0),cost=Math.max(60000,households*.18),days=areaId==='all'?30:12;if(s.cash<cost*.2)return s;s.cash-=cost*.2;s.totalExpense+=cost*.2;missing.forEach(a=>a.rightsPending=true);s.distributionProjects.push({id:uid('dist'),kind:'rights',state:code,areaId,daysRemaining:days,totalDays:days,cost,paid:cost*.2});sendMail(s,'Distribution',`Rights application filed: ${code}`,`${areaId==='all'?'All-state':missing[0]?.name} emission rights application is underway. Estimated ${days} days.`, 'distribution');return s;}
export function startAntennaBuild(state,code,areaId,level=1){const s=deepClone(state),st=s.states.find(x=>x.code===code),a=st?.areas.find(x=>x.id===areaId);if(!a||!a.rightsOwned||a.antennaPending||a.antennaLevel>=level)return s;const multipliers={1:.28,2:.52,3:.86},cost=Math.max(120000,a.households*(multipliers[level]||.86)),days={1:25,2:45,3:70}[level];if(s.cash<cost*.25)return s;s.cash-=cost*.25;s.totalExpense+=cost*.25;a.antennaPending=true;s.distributionProjects.push({id:uid('dist'),kind:'antenna',state:code,areaId,level,daysRemaining:days,totalDays:days,cost,paid:cost*.25});sendMail(s,'Engineering',`Antenna build started: ${a.name}`,`Level ${level} transmission infrastructure will take about ${days} days.`, 'distribution');return s;}
export function expandState(state,code){const st=state.states.find(x=>x.code===code),a=st?.areas.find(x=>x.rightsOwned&&!x.antennaPending&&x.antennaLevel<3);return a?startAntennaBuild(state,code,a.id,Math.min(3,a.antennaLevel+1)):state;}

export function signAdAgency(state,agencyId){const s=deepClone(state),a=s.agencies.find(x=>x.id===agencyId);if(!a)return s;s.adAgencyContract={agencyId,start:s.date,term:a.term,commission:a.baseShare,cpm:a.cpm};s.contracts=s.contracts.filter(x=>x.type!=='ad-agency');s.contracts.push({id:uid('ct'),name:a.name,type:'ad-agency',annualCost:0,term:a.term,start:s.date});sendMail(s,'Commercial Office',`Advertising representation signed: ${a.name}`,`${a.name} will monetize standard advertising inventory. Net revenue now scales with audience, slot and ad load.`, 'commercial');return s;}
export function signSponsor(state,id,programId){const s=deepClone(state),x=s.sponsorships.find(y=>y.id===id),p=getProgram(s,programId);if(!x||!p)return s;x.status='Active';x.programId=p.id;x.totalWeeks=x.weeks;x.weeksRemaining=x.weeks;p.sponsor=x.brand;sendMail(s,'Sponsorships',`${x.brand} signs ${p.title}`,`${x.brand}: ${x.weeks} weeks, fixed $${x.fixed.toLocaleString()} + $${x.variablePerMillion.toLocaleString()} per million viewers.`, 'commercial',{programId:p.id});return s;}
export function setAdLoad(state,programId,minutes){const s=deepClone(state),p=getProgram(s,programId);if(p){p.commercialsEnabled=Number(minutes)>0;p.adLoad=Number(minutes)||12;}return s;}
export function setCommercialsEnabled(state,programId,on){const s=deepClone(state),p=getProgram(s,programId);if(p)p.commercialsEnabled=!!on;return s;}
export function setMarketing(state,programId,level){const s=deepClone(state),p=getProgram(s,programId);if(p){const cost=Number(level)*2500;if(s.cash<cost)return s;p.marketing=Number(level);p.marketingSpend+=cost;s.cash-=cost;s.totalExpense+=cost;p.awareness=clamp(p.awareness+Number(level)*.08,0,100)}return s;}

export function licenseContent(state,id,mode='single',movieId=null){
  const s=deepClone(state),pack=s.contentMarket.find(x=>x.id===id);if(!pack)return s;s.contentLicenses=s.contentLicenses||[];const already=new Set(s.contentLicenses.flatMap(x=>x.movieIds||[]));let movies=[];
  if(mode==='single')movies=[pack.movies.find(x=>x.id===movieId)||pack.movies[0]];else if(mode==='four'){const idx=Math.max(0,pack.movies.findIndex(x=>x.id===movieId));movies=pack.movies.slice(idx,idx+4);if(movies.length<4)movies=[...movies,...pack.movies.slice(0,4-movies.length)];}else movies=[...pack.movies];
  if(!movies.length||movies.some(m=>already.has(m.id)))return s;const per=pack.fullCost/pack.packageSize,cost=mode==='single'?per*1.35:mode==='four'?per*4*1.15:pack.fullCost;if(s.cash<cost)return s;
  s.cash-=cost;s.totalExpense+=cost;const collectionId=uid('library');s.contentLicenses.push({id:collectionId,packageId:pack.id,packageTitle:pack.title,mode,movieIds:movies.map(x=>x.id),cost,date:s.date});
  movies.forEach((m,i)=>{const ip={id:uid('ip'),name:m.name,origin:'Licensed Movie',genre:pack.genre,popularity:pack.popularity,novelty:14,fatigue:8,prestige:m.critic*.6,fandom:pack.popularity*.35,flexibility:20,value:cost/movies.length*.7,affinity:{...pack.affinity},seasons:0,identity:[pack.genre,'movie'],merchPotential:3};s.ips.push(ip);const p=makeProgramDraft({title:m.name,format:'Acquired',genre:pack.genre,episodes:2,duration:120,target:{...pack.affinity},ipId:ip.id,art:'cinematic',font:'serif',p1:'#ba6146',p2:'#312437'});p.acquired=true;p.collectionId=collectionId;p.collectionName=pack.title;p.status='Ready';p.preProductionFinalized=true;p.pipeline={scripted:2,pre:2,filmed:2,ready:2,aired:0};p.viewer=m.viewer;p.critic=m.critic;p.quality=(m.viewer+m.critic)/2;p.premiered=true;s.programs.push(p);});sendMail(s,'Acquisitions',`Rights confirmed: ${pack.title}`,`${movies.length} movie${movies.length===1?'':'s'} licensed from ${pack.title} for $${Math.round(cost).toLocaleString()}. These rights are now locked and cannot be purchased again. Each title has two authorized broadcasts.`, 'rights');return s;
}
export function isMovieLicenseAvailable(state,packId,mode='single',movieId=null){const pack=state.contentMarket.find(x=>x.id===packId);if(!pack)return false;const already=new Set((state.contentLicenses||[]).flatMap(x=>x.movieIds||[]));let movies=mode==='full'?pack.movies:mode==='single'?[pack.movies.find(x=>x.id===movieId)||pack.movies[0]]:(()=>{const idx=Math.max(0,pack.movies.findIndex(x=>x.id===movieId));let m=pack.movies.slice(idx,idx+4);if(m.length<4)m=[...m,...pack.movies.slice(0,4-m.length)];return m})();return movies.length>0&&!movies.some(m=>already.has(m.id));}
export function acquireContent(state,id){return licenseContent(state,id,'full');}
export function acquireIP(state,id){const s=deepClone(state),i=s.ipMarket.findIndex(x=>x.id===id);if(i<0)return s;const m=s.ipMarket[i];if(s.cash<m.cost)return s;s.cash-=m.cost;s.totalExpense+=m.cost;s.ips.push({...m,id:uid('ip'),origin:'Licensed IP',value:m.cost,rights:{...m.rights},seasons:0,fatigue:8});s.contracts.push({id:uid('ct'),name:m.name,type:'ip',annualCost:m.cost/m.rights.term,term:m.rights.term,start:s.date});s.ipMarket.splice(i,1);sendMail(s,'Rights Desk',`IP rights acquired: ${m.name}`,`${m.name} is now under contract for ${m.rights.term} years. The opportunity has been removed from the open market.`, 'rights');return s;}
function awardSport(s,x,annualPrice){if(x.owned)return;x.owned=true;x.cost=annualPrice;x.leader=s.network.initials;s.contracts.push({id:uid('ct'),name:x.name,type:'sports',annualCost:annualPrice,term:x.term,start:s.date});const ip={id:uid('ip'),name:x.name,origin:'Sports Rights',genre:'Sports',popularity:x.popularity,novelty:10,fatigue:5,prestige:x.prestige,fandom:x.popularity*.55,flexibility:20,value:annualPrice*x.term*.8,affinity:affinity({[x.target]:90}),seasons:0,identity:['sports','live'],merchPotential:15};s.ips.push(ip);const p=makeProgramDraft({title:x.name,format:'Sports',genre:'Live Sports',episodes:x.events,duration:x.eventDuration||180,target:{...ip.affinity},ipId:ip.id,art:ART_BY_GENRE['Live Sports']||'stadium',font:'wide',p1:'#db4e70',p2:'#211a36'});p.acquired=true;p.status='Ready';p.pipeline={scripted:x.events,pre:x.events,filmed:x.events,ready:x.events,aired:0};p.viewer=70;p.critic=55;p.quality=72;p.premiered=true;p.budgetPerEpisode=Math.max(25000,annualPrice/x.events*.18);p.sportsRightsId=x.id;s.programs.push(p);sendMail(s,'Rights Desk',`Sports rights won: ${x.name}`,`${x.events} events are available for scheduling. Use the Sports format to create pregame, postgame, sports news or talk around the rights.`, 'rights',{programId:p.id});}
export function placeSportBid(state,id){const s=deepClone(state),x=s.sports.find(y=>y.id===id);if(!x||x.owned||x.bidEnds<=0)return s;const next=Math.round(((x.currentBid||x.cost*.75)*(x.leader?1.1:1.06))/10000)*10000;if(s.cash<next*.08)return s;x.currentBid=next;x.leader=s.network.initials;return s;}
export function acquireSport(state,id){const s=deepClone(state),x=s.sports.find(y=>y.id===id);if(!x||x.owned)return s;awardSport(s,x,x.cost);return s;}
export function createSportsCompanion(state,sportId,type='Pregame'){const s=deepClone(state),sp=s.sports.find(x=>x.id===sportId&&x.owned);if(!sp)return s;const parent=s.programs.find(p=>p.sportsRightsId===sp.id),ipId=parent?.ipId,d={id:uid('dev'),title:`${sp.name}: ${type}`,format:'Sports',genre:type,theme:'Sports',topic:`Companion programming for ${sp.name}`,angle:'Familiar',episodes:40,duration:type==='Highlights'?30:60,writerId:null,status:'Idea',daysRemaining:0,totalDays:0,cost:0,spent:0,scriptStars:null,novelty:null,target:affinity({[sp.target]:82}),art:ART_BY_GENRE['Live Sports']||'stadium',font:'wide',p1:'#db4e70',p2:'#211a36',ipId};s.developments.push(d);return s;}

export function startRightsAuctionTick(s){s.sports.forEach(x=>{if(x.owned||x.bidEnds<=0)return;x.bidEnds--;if(x.leader===s.network.initials){const r=seeded(`sports-bid-${s.date}-${x.id}`);if(r()>.64){const rival=[...s.competitors].sort((a,b)=>b.strength-a.strength)[Math.floor(r()*4)];x.currentBid=Math.round(x.currentBid*1.08/10000)*10000;x.leader=rival.name;sendMail(s,'Rights Desk',`${x.name}: you have been outbid`,`${rival.name} now leads at $${x.currentBid.toLocaleString()}/year.`, 'rights');}}if(x.bidEnds===0&&x.leader===s.network.initials)awardSport(s,x,x.currentBid||x.cost);});}

export function audienceRankings(s,period='yesterday',scope='national'){
  const scopeKey=scope==='local'?'local':scope==='state'?'state':'national',ownHistory=s.networkAudienceHistory||[],today=dateObj(s.date),start=period==='year'?new Date(today.getFullYear(),0,1):period==='month'?new Date(today.getFullYear(),today.getMonth(),1):new Date(today.getTime()-86400000),ownRows=ownHistory.filter(x=>dateObj(x.date)>=start),ownTotal=ownRows.reduce((a,x)=>a+(x[scopeKey]||0),0),ownAvg=ownTotal/Math.max(1,period==='yesterday'?1:ownRows.length),rows=[{id:'player',name:s.network.name,initials:s.network.initials,scope:'Player',audience:ownAvg,totalAudience:ownTotal,prestige:s.network.prestige,revenue:s.totalRevenue}];
  s.competitors.forEach(c=>{const monthKey=s.date.slice(0,7),monthRow=(c.monthlyAudience||[]).find(x=>x.month===monthKey),daysYear=Math.max(1,Math.floor((today-new Date(today.getFullYear(),0,1))/86400000)+1);let total=period==='yesterday'?c.audience.yesterday:period==='month'?(monthRow?.total||0):c.audience.year,days=period==='yesterday'?1:period==='month'?Math.max(1,monthRow?.days||0):daysYear;if(scope==='state')total*=c.scope==='Local'?.95:c.scope==='State'?1:.08;if(scope==='local')total*=c.scope==='Local'?1:c.scope==='State'?.24:.018;rows.push({id:c.id,name:c.name,scope:c.scope,audience:total/days,totalAudience:total,prestige:c.prestige,revenue:c.revenue});});return rows.sort((a,b)=>b.audience-a.audience);
}
export function currentProgramRankings(s,{scope='national',format='all',band='all'}={}){const rows=[],year=String(new Date(s.date).getFullYear()),scopeKey=scope==='local'?'localAudience':scope==='state'?'stateAudience':'audience',ownMap=new Map();s.ratingsLog.filter(r=>String(r.date||'').startsWith(year)).forEach(r=>{const p=getProgram(s,r.programId);if(!p||format!=='all'&&p.format!==format||band!=='all'&&r.band!==band)return;const x=ownMap.get(p.id)||{programId:p.id,networkId:'player',network:s.network.initials,title:p.title,format:p.format,genre:p.genre,band:r.band,totalAudience:0,n:0,viewer:p.viewer/10,critic:p.critic};x.totalAudience+=r[scopeKey]||0;x.n++;ownMap.set(p.id,x);});rows.push(...ownMap.values().map(x=>({...x,audience:x.totalAudience/Math.max(1,x.n),airings:x.n})));const compMap=new Map();s.competitorRatings.filter(r=>String(r.date||'').startsWith(year)).forEach(r=>{if(format!=='all'&&r.format!==format||band!=='all'&&r.band!==band)return;const key=r.programId,x=compMap.get(key)||{programId:r.programId,networkId:r.networkId,network:s.competitors.find(c=>c.id===r.networkId)?.name||'Rival',title:r.title,format:r.format,genre:r.genre,band:r.band,totalAudience:0,n:0,viewer:r.viewer,critic:r.critic};x.totalAudience+=r[scopeKey]||r.audience;x.n++;compMap.set(key,x);});rows.push(...compMap.values().map(x=>({...x,audience:x.totalAudience/Math.max(1,x.n),airings:x.n})));return rows.sort((a,b)=>b.audience-a.audience);}
export function historicalRecords(s,{format='all',metric='audience'}={}){const all=[...(s.programRecords||[])];const current=currentProgramRankings(s,{format,band:'all'}).map(x=>({...x,year:new Date(s.date).getFullYear()}));const rows=[...all,...current].filter(x=>format==='all'||x.format===format);const key=metric==='viewer'?'viewer':metric==='critic'?'critic':'audience';return rows.sort((a,b)=>(b[key]||0)-(a[key]||0)).slice(0,10);}
function yearEnd(s){const d=dateObj(s.date);if(d.getMonth()===11&&d.getDate()===31&&!s.yearly.recordsProcessed){const year=d.getFullYear(),current=currentProgramRankings(s,{});current.slice(0,150).forEach(x=>s.programRecords.push({...x,year}));s.yearly.recordsProcessed=true;sendMail(s,'Audience Research',`${year} records archived`,'Annual network and program performance has been added to the historical record books.','ratings');}if(d.getMonth()===0&&d.getDate()===1){s.yearly.recordsProcessed=false;s.competitors.forEach(c=>c.audience.year=0);}}

export function runOneDay(s,{silent=false}={}){s.lastDayRevenue=0;s.lastDayAudience=0;developmentDay(s);searchDay(s);negotiationDay(s);facilityDay(s);distributionDay(s);productionDay(s);researchDay(s);dailyOverhead(s);competitorDay(s);airDay(s);licensingDay(s);startRightsAuctionTick(s);yearEnd(s);s.financeLog.push({date:s.date,cash:s.cash,revenue:s.lastDayRevenue,expense:s.lastDayExpense||0});s.financeLog=s.financeLog.slice(-1460);s.date=addDays(s.date,1);if(!silent&&s.cash<0)sendMail(s,'CFO','Cash balance is negative','The network needs financing, rights sales or immediate cost action.','warning');}
export function advanceDays(state,n){const s=deepClone(state);for(let i=0;i<n;i++)runOneDay(s,{silent:true});return s;}
export function alerts(s){const out=[];if(!s.programs.length)out.push({sev:'orange',title:'No programming owned',sub:'License movies or commission an original script.'});if(!s.employees.length)out.push({sev:'orange',title:'No staff',sub:'Open a role search in Organization.'});if(!s.adAgencyContract)out.push({sev:'orange',title:'No advertising agency',sub:'Standard audience currently produces no base ad revenue.'});s.programs.forEach(p=>{if(p.status==='Pre-production'){const c=canStartProduction(s,p);if(!c.ok)out.push({sev:'orange',title:`${p.title}: pre-production blocked`,sub:c.reason})}const runway=Math.floor(p.pipeline.ready-p.pipeline.aired);if(['Production','Ready','On Air'].includes(p.status)&&runway<=1)out.push({sev:'orange',title:`${p.title} runway: ${Math.max(0,runway)}`,sub:'Production/delivery is close to the schedule.'})});if(s.cash<3000000)out.push({sev:'red',title:'Cash reserve dangerously low',sub:'Reduce commitments or improve monetization.'});return out.slice(0,10);}

export function setAdAgency(state,id){return signAdAgency(state,id);}
export function signAd(state){return state;}
export function signAffiliate(state){return state;}
export function expandFacility(state,key){return startFacilityBuild(state,key);}
export function launchStreaming(state){const s=deepClone(state);if(!s.streaming.unlocked||s.streaming.launched||s.cash<3500000)return s;s.cash-=3500000;s.totalExpense+=3500000;s.streaming.launched=true;s.streaming.subscribers=2500;return s;}
export function updateStreaming(state,patch){const s=deepClone(state);Object.assign(s.streaming,patch);return s;}
export function updateNewsroom(state,key,delta){const s=deepClone(state);if(['bureaus','reporters','weather','sportsDesk','investigative'].includes(key)){const cost={bureaus:650000,reporters:140000,weather:280000,sportsDesk:320000,investigative:450000}[key]*delta;if(delta>0&&s.cash<cost)return s;s.newsroom[key]=Math.max(0,s.newsroom[key]+delta);s.cash-=cost;s.totalExpense+=Math.max(0,cost)}return s;}
export function setAutomation(state,key,value){const s=deepClone(state);s.automation[key]=value;return s;}
export function updateNetwork(state,patch){const s=deepClone(state);Object.assign(s.network,patch);if(patch.initials)s.streaming.name=`${patch.initials}+`;return s;}
export function updateProductionPlan(state,programId,focus,technical){const s=deepClone(state),p=getProgram(s,programId);if(p){if(focus)p.productionAllocation={...focus};if(technical)p.technical={...technical}}return s;}
export function rewriteScript(state,programId,episode){const s=deepClone(state),p=getProgram(s,programId),sc=p?.scripts?.find(x=>x.episode===episode);if(sc){const writer=getEmployee(s,p.team.leadWriter),r=seeded(`${s.date}-${p.id}-${episode}-rewrite`)();sc.stars=Math.round(clamp(sc.stars+(writer?.skills.writing||60)/100*.6+(r()-.5)*.5,1,5)*2)/2;p.scriptStars=avg(p.scripts.map(x=>x.stars));}return s;}
export function renewProgram(state,programId,change){const s=deepClone(state),p=getProgram(s,programId),ip=p&&getIP(s,p.ipId),writer=p&&getEmployee(s,p.team?.leadWriter);if(!p||!ip||!writer)return s;if(s.developments.some(d=>d.seasonRenewalFor===p.id&&['Writing','Rewrite','Complete'].includes(d.status)))return s;const e=ipSeasonEffect(ip,Number(change));ip.popularity=e.retainedPopularity;ip.novelty=e.newNovelty;ip.fatigue=e.newFatigue;ip.seasons=(ip.seasons||0)+1;const speed=writer.skills.speed||65,totalDays=Math.max(4,Math.round(p.episodes*(p.duration/30)*(8.5-speed/18)*.72)),cost=Math.round(p.episodes*(p.duration/30)*(p.format==='Scripted'?11000:p.format==='Reality'?6500:4000));if(s.cash<cost*.25)return s;s.cash-=cost*.25;s.totalExpense+=cost*.25;s.developments.push({id:uid('dev'),title:p.title,format:p.format,genre:p.genre,theme:ip.identity?.[1]||'Contemporary',topic:`Season ${p.season+1}`,angle:Number(change)>70?'Experimental':Number(change)<15?'Familiar':'Fresh',episodes:p.episodes,duration:p.duration,writerId:writer.id,status:'Writing',daysRemaining:totalDays,totalDays,cost,spent:cost*.25,scriptStars:null,novelty:null,target:{...p.target},art:p.art,font:p.font,p1:p.p1,p2:p.p2,ipId:ip.id,seasonRenewalFor:p.id,nextSeason:p.season+1,creativeChange:Number(change),created:s.date});return s;}
export function createProgram(state,form){return commissionScript(state,form);}
export function setSchedule(state,day,slot,programId){return scheduleProgram(state,day,slot,programId);}
export function runPromotion(state,programId,type){const s=deepClone(state),p=getProgram(s,programId);if(!p)return s;const options={network:{cost:50000,awareness:3},digital:{cost:80000,awareness:5},press:{cost:120000,awareness:4},premiere:{cost:220000,awareness:6},awards:{cost:350000,awareness:1}},o=options[type];if(!o||s.cash<o.cost)return s;s.cash-=o.cost;s.totalExpense+=o.cost;p.marketingSpend+=o.cost;p.awareness=clamp(p.awareness+o.awareness,0,100);return s;}
export function createLicenseDeal(state,programId){const s=deepClone(state),p=getProgram(s,programId),ip=p&&getIP(s,p.ipId);if(!p||!ip||p.airings<2)return s;const annual=Math.max(80000,(p.viewer*.4+p.critic*.25+ip.popularity*.35)*12000);s.licenses.push({id:uid('lic'),programId:p.id,name:`${p.title} Syndication`,annualRevenue:annual,term:3,status:'Active'});return s;}
export function createMerchDeal(state,ipId,mode='License'){const s=deepClone(state),ip=getIP(s,ipId);if(!ip||ip.fandom<35)return s;let annual=Math.max(50000,(ip.fandom*.5+ip.popularity*.25+(ip.merchPotential||20)*.25)*9000);if(mode==='Direct'){const upfront=450000;if(s.cash<upfront)return s;s.cash-=upfront;s.totalExpense+=upfront;annual*=1.6}s.merchDeals.push({id:uid('merch'),ipId,partner:mode==='Direct'?'Network Consumer Products':'Licensed Consumer Products',mode,baseAnnual:annual,status:'Active'});return s;}
export function programPnL(s,p){const production=(p.productionSpend||0)+(p.residualSpend||0);return {revenue:(p.revenue||0)+(p.licensingRevenue||0)+(p.merchRevenue||0),production,marketing:p.marketingSpend||0,residuals:p.residualSpend||0,contribution:(p.revenue||0)+(p.licensingRevenue||0)+(p.merchRevenue||0)-production-(p.marketingSpend||0)};}
export function createSpinOff(state,ipId,title){const s=deepClone(state),ip=getIP(s,ipId);if(!ip)return s;s.developments.push({id:uid('dev'),title:title||`${ip.name}: After Hours`,format:'Live',genre:'Talk Show',theme:'Contemporary',topic:`Companion to ${ip.name}`,angle:'Familiar',episodes:26,duration:30,writerId:null,status:'Idea',daysRemaining:0,totalDays:0,cost:0,spent:0,scriptStars:null,novelty:null,target:{...ip.affinity},art:'bars',font:'wide',p1:'#9272d1',p2:'#1b213d',ipId});return s;}
