import fs from 'node:fs';
import path from 'node:path';
import { runScenarioQA, runStateQA } from './src/game/qa.js';
import { seedState } from './src/game/seed.js';

const base=seedState({name:'QA Network',initials:'QAN',home:'VA',focus:'Scripted'});
const baseChecks=runStateQA(base);
const scenario=runScenarioQA();
const scenarioStateChecks=runStateQA(scenario.state);
const all=[...baseChecks,...scenario.results,...scenarioStateChecks];
const root=process.cwd();
const repoChecks=[];const check=(n,v,d='')=>repoChecks.push({name:n,ok:!!v,detail:d});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
check('Vite config exists',fs.existsSync(path.join(root,'vite.config.js')));
check('React app entry exists',fs.existsSync(path.join(root,'src','App.jsx')));
check('GitHub Pages workflow exists',fs.existsSync(path.join(root,'.github','workflows','deploy.yml')));
const css=read('src/styles.css'), app=read('src/App.jsx'), channel=read('src/screens/Channel.jsx'), org=read('src/screens/Organization.jsx'), business=read('src/screens/Business.jsx'), dash=read('src/screens/Dashboard.jsx');
check('Mobile breakpoint present',/@media\s*\(max-width:\s*840px\)/.test(css));
check('Safe-area support',css.includes('env(safe-area-inset-bottom)'));
check('Touch manipulation enabled',css.includes('touch-action:manipulation')||css.includes('touch-action: manipulation'));
check('Bottom navigation retained',css.includes('.bottom-nav'));
check('Recurrence UI present',channel.includes('as long as')||channel.includes('As long as'));
check('Audience competition tabs present',channel.includes('Audience')&&channel.includes('Records')&&channel.includes('Programs'));
check('State expansion drawer present',org.includes('All-state')||org.includes('All-State')||org.includes('All State'));
check('Negotiation offer UI present',org.includes('market average')||org.includes('Market average'));
check('Agency advertising UI present',business.includes('Advertising')&&business.includes('agency'));
check('Sponsor marketplace present',business.includes('Sponsors'));
check('Inbox signing actions present',dash.includes('Sign Person')&&dash.includes('Break Negotiations'));
check('v0.4 save prefix',app.includes('v04'));
const failed=[...all,...repoChecks].filter(x=>!x.ok);
console.log(`Simulation/state/scenario: ${all.length-failed.filter(x=>all.includes(x)).length}/${all.length}`);
console.log(`Repository/mobile: ${repoChecks.filter(x=>x.ok).length}/${repoChecks.length}`);
for(const x of failed) console.log(`FAIL: ${x.name}${x.detail?` — ${x.detail}`:''}`);
if(failed.length) process.exit(1);
console.log(`Scenario cash: $${Math.round(scenario.state.cash).toLocaleString()}`);
