import React, { useState } from 'react';
import { Card, Empty, MoneyStat, Pill, ProgramPoster, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { DEMOS } from '../game/constants.js';
import { acquireContent, acquireIP, createLicenseDeal, createMerchDeal, createSportsCompanion, launchStreaming, placeSportBid, programPnL, setAdLoad, signAd, signSponsor, updateStreaming } from '../game/simulation.js';
import { money, num, pct } from '../game/utils.js';

const demoLabel=k=>DEMOS.find(x=>x[0]===k)?.[1]||k;

export default function Business({state,setState}){
  const [tab,setTab]=useState('ads');
  return <div className="page-stack">
    <div className="page-head"><div><span className="eyebrow">QUADRANT III</span><h1>Business</h1><p>Turn attention into money, acquire rights and compound the value of your content library.</p></div></div>
    <Tabs value={tab} onChange={setTab} items={[["ads","Advertising"],["sponsors","Sponsors"],["rights","Rights"],["ip","IP Market"],["licensing","Licensing"],["finance","Finance"],["streaming","Streaming"]]}/>
    {tab==='ads'&&<Ads state={state} setState={setState}/>} 
    {tab==='sponsors'&&<Sponsors state={state} setState={setState}/>} 
    {tab==='rights'&&<Rights state={state} setState={setState}/>} 
    {tab==='ip'&&<IPMarket state={state} setState={setState}/>} 
    {tab==='licensing'&&<Licensing state={state} setState={setState}/>} 
    {tab==='finance'&&<Finance state={state}/>} 
    {tab==='streaming'&&<Streaming state={state} setState={setState}/>} 
  </div>
}

function Ads({state,setState}){
  const [packages,setPackages]=useState({});
  const toggle=(aid,pid)=>setPackages(x=>{const cur=x[aid]||[];return {...x,[aid]:cur.includes(pid)?cur.filter(id=>id!==pid):[...cur,pid]}});
  return <div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Advertising RFPs" sub="Build an actual package of programs for each advertiser, then guarantee the target impressions."/><div className="candidate-grid">{state.adCampaigns.filter(a=>a.status!=='Closed').map(a=>{const pace=a.delivered/Math.max(1,a.goal),chosen=a.programIds||packages[a.id]||[];return <Card className="candidate-card" key={a.id}><div className="section-title"><div><h3>{a.brand}</h3><span>{demoLabel(a.target)} + {demoLabel(a.secondary)}</span></div><b>{money(a.budget)}</b></div><div className="mini-stats"><span>CPM <b>${a.cpm}</b></span><span>Goal <b>{num(a.goal)}</b></span><span>Days <b>{a.days}</b></span></div>{a.status==='Active'&&<><StatBar label="Delivered" value={pace*100}/><div className="chips">{chosen.map(id=><Pill key={id}>{state.programs.find(p=>p.id===id)?.title}</Pill>)}</div></>}{a.status==='Available'&&<><div className="package-builder"><b>Package inventory</b>{state.programs.slice(0,8).map(p=><label className="package-option" key={p.id}><input type="checkbox" checked={(packages[a.id]||[]).includes(p.id)} onChange={()=>toggle(a.id,p.id)}/><span>{p.title}</span></label>)}</div><button className="primary" disabled={!(packages[a.id]||[]).length} onClick={()=>setState(signAd(state,a.id,packages[a.id]||[]))}>Sign Package</button></>}<Pill tone={a.status==='Active'?'ok':''}>{a.status}</Pill></Card>})}</div></Card>
    <Card className="pad"><SectionTitle title="Ad Load" sub="More inventory raises short-term revenue but viewers switch away."/>{state.programs.slice(0,8).map(p=><label className="range-row" key={p.id}><span>{p.title}<small>{p.adLoad??12} min/hr</small></span><input type="range" min="6" max="20" value={p.adLoad??12} onChange={e=>setState(setAdLoad(state,p.id,e.target.value))}/><b>{p.adLoad??12}</b></label>)}</Card></div>
}
function Sponsors({state,setState}){
  const [choice,setChoice]=useState({});
  const offers=state.sponsorships.filter(x=>x.status!=='Closed');
  return <Card className="pad"><SectionTitle title="Sponsorship Market" sub="Premium integrations attach brands directly to a show or event."/><div className="candidate-grid">{offers.map(sp=><Card className="candidate-card" key={sp.id}><div><span className="eyebrow">{sp.programType} partner</span><h3>{sp.brand}</h3><p>{money(sp.offer)} · {sp.weeks} weeks · Target {demoLabel(sp.target)}</p></div>{sp.status==='Active'?<Pill tone="ok">On {state.programs.find(p=>p.id===sp.programId)?.title}</Pill>:<><select value={choice[sp.id]||''} onChange={e=>setChoice(c=>({...c,[sp.id]:e.target.value}))}><option value="">Choose program</option>{state.programs.filter(p=>p.genre.includes(sp.programType)||p.format.includes(sp.programType)||sp.programType==='Sports'&&p.format==='Sports').map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select><button className="primary" disabled={!choice[sp.id]} onClick={()=>setState(signSponsor(state,sp.id,choice[sp.id]))}>Accept Sponsorship</button></>}</Card>)}</div></Card>
}

function Rights({state,setState}){
  const [sub,setSub]=useState('content');
  return <div className="page-stack"><Tabs value={sub} onChange={setSub} items={[["content","Movies & Library"],["sports","Sports Rights"]]}/>
    {sub==='content'?<Card className="pad"><SectionTitle title="Content Acquisition" sub="Acquire finished programming with limited broadcast runs."/><div className="candidate-grid">{state.contentMarket.map(m=><Card className="candidate-card" key={m.id}><span className="eyebrow">{m.type}</span><h3>{m.title}</h3><p>{m.genre} · {m.runs} runs · {m.duration} min</p><div className="mini-stats"><span>Viewer <b>{(m.viewer/10).toFixed(1)}</b></span><span>Critics <b>{m.critic}%</b></span><span>Pop <b>{m.popularity}</b></span></div><button className="primary" disabled={state.cash<m.cost} onClick={()=>setState(acquireContent(state,m.id))}>License · {money(m.cost)}</button></Card>)}</div></Card>:
    <Card className="pad"><SectionTitle title="Sports Rights" sub="Multi-year commitments can transform the channel or trap its balance sheet."/><div className="candidate-grid">{state.sports.map(sp=><Card className="candidate-card" key={sp.id}><span className="eyebrow">{sp.exclusivity} · {sp.schedule}</span><h3>{sp.name}</h3><p>{sp.events} events · {sp.term} season{sp.term>1?'s':''} · target {demoLabel(sp.target)}</p><StatBar label="Popularity" value={sp.popularity}/>{sp.owned?<><Pill tone="ok">Rights Owned · {money(sp.cost)}/yr</Pill><div className="button-row"><button onClick={()=>setState(createSportsCompanion(state,sp.id,'Pregame'))}>+ Pregame</button><button onClick={()=>setState(createSportsCompanion(state,sp.id,'Highlights'))}>+ Highlights</button></div></>:<><div className="auction-box"><span>Current bid <b>{money(sp.currentBid||sp.cost)}</b></span><span>Leader <b>{sp.leader||'No bids'}</b></span><span>Closes <b>{sp.bidEnds}d</b></span></div><button className="primary" disabled={sp.bidEnds<=0||state.cash<(sp.currentBid||sp.cost)*.12} onClick={()=>setState(placeSportBid(state,sp.id))}>{sp.leader==='PCN'?'Raise Bid':'Place Bid'}</button></>}</Card>)}</div></Card>}
  </div>
}

function IPMarket({state,setState}){
  return <Card className="pad"><SectionTitle title="Adaptation Rights Market" sub="Rights are granular: term, territory, medium and merchandising economics matter."/><div className="ip-grid">{state.ipMarket.map(ip=><Card className="candidate-card" key={ip.id}><span className="eyebrow">{ip.type}</span><h3>{ip.name}</h3><StatBar label="Popularity" value={ip.popularity}/><StatBar label="Novelty" value={ip.novelty}/><StatBar label="Fandom" value={ip.fandom}/><StatBar label="Merch Potential" value={ip.merchPotential}/><div className="rights-note"><span>{ip.rights.medium}</span><span>{ip.rights.territory} · {ip.rights.term} years</span><span>Merch split {ip.rights.merchSplit}%</span></div><button className="primary" disabled={state.cash<ip.cost} onClick={()=>setState(acquireIP(state,ip.id))}>Acquire · {money(ip.cost)}</button></Card>)}</div></Card>
}

function Licensing({state,setState}){
  return <div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Library Exploitation" sub="Successful programs can earn long-tail syndication and licensing revenue."/><div className="candidate-grid">{state.programs.map(p=>{const deal=state.licenses.find(x=>x.programId===p.id&&x.status==='Active');return <Card className="candidate-card" key={p.id}><h3>{p.title}</h3><p>{p.airings} airings · Viewer {(p.viewer/10).toFixed(1)} · Critics {Math.round(p.critic)}%</p>{deal?<><Pill tone="ok">{money(deal.annualRevenue)}/yr licensed</Pill></>:<button disabled={p.airings<2} onClick={()=>setState(createLicenseDeal(state,p.id))}>Offer Syndication</button>}</Card>})}</div></Card><Card className="pad"><SectionTitle title="Merchandise Licensing" sub="Fandom matters more than raw household reach."/>{state.ips.map(ip=>{const d=state.merchDeals.find(x=>x.ipId===ip.id&&x.status==='Active');return <div className="compact-line" key={ip.id}><span>{ip.name}<small>Fandom {Math.round(ip.fandom)} · Potential {Math.round(ip.merchPotential||0)}</small></span>{d?<b>{d.mode||'License'} · {money(d.baseAnnual)}/yr</b>:<span className="inline-buttons"><button disabled={ip.fandom<35} onClick={()=>setState(createMerchDeal(state,ip.id,'License'))}>License</button><button disabled={ip.fandom<35||state.cash<450000} onClick={()=>setState(createMerchDeal(state,ip.id,'Direct'))}>Produce</button></span>}</div>})}</Card></div>
}

function Finance({state}){
  const showRows=[...state.programs].map(p=>({p,pnl:programPnL(state,p)})).sort((a,b)=>b.pnl.contribution-a.pnl.contribution);
  const futureCommitments=state.contracts.reduce((s,c)=>s+(c.annualCost||0)*(c.term||1),0);
  return <div className="dashboard-grid"><Card className="pad"><SectionTitle title="Company Financials"/><MoneyStat label="Cash" value={state.cash}/><MoneyStat label="Debt" value={-state.debt}/><MoneyStat label="Lifetime Revenue" value={state.totalRevenue}/><MoneyStat label="Lifetime Expense" value={-state.totalExpense}/><MoneyStat label="Net cumulative" value={state.totalRevenue-state.totalExpense}/><MoneyStat label="Contracted future commitments" value={-futureCommitments}/></Card><Card className="pad span-2"><SectionTitle title="Program P&L" sub="A hit can be valuable even before current-season contribution turns positive."/><div className="table-wrap"><table><thead><tr><th>Program</th><th>Revenue</th><th>Production</th><th>Marketing</th><th>Contribution</th></tr></thead><tbody>{showRows.map(({p,pnl})=><tr key={p.id}><td><b>{p.title}</b><small>{p.genre}</small></td><td>{money(pnl.revenue)}</td><td>{money(pnl.production)}</td><td>{money(pnl.marketing)}</td><td className={pnl.contribution>=0?'positive':'negative'}>{money(pnl.contribution)}</td></tr>)}</tbody></table></div></Card><Card className="pad span-3"><SectionTitle title="Contracts & Commitments"/><div className="candidate-grid">{state.contracts.map(c=><Card className="candidate-card" key={c.id}><span className="eyebrow">{c.type}</span><h3>{c.name}</h3><p>{money(c.annualCost)}/yr · {c.term} year term · started {c.start}</p></Card>)}</div></Card></div>
}

function Streaming({state,setState}){
  const st=state.streaming;
  return <div className="split-layout"><Card className="pad"><SectionTitle title={st.name} sub="Direct distribution is a strategic choice, not a free national-reach button."/><div className="stream-hero"><span>STREAM</span><b>{state.network.initials}<i>+</i></b></div>{!st.unlocked?<Empty>Research Streaming Platform in Organization → Research to unlock.</Empty>:!st.launched?<button className="primary big" disabled={state.cash<3500000} onClick={()=>setState(launchStreaming(state))}>Launch {st.name} · $3.5M</button>:<><div className="metric-grid compact-metrics"><div className="metric"><span>Subscribers</span><strong>{num(st.subscribers)}</strong></div><div className="metric"><span>Price</span><strong>${Number(st.price).toFixed(2)}</strong></div></div><label>Business model<select value={st.model} onChange={e=>setState(updateStreaming(state,{model:e.target.value}))}><option>Hybrid</option><option>Subscription</option><option>Advertising</option></select></label><label>Monthly price<input type="number" min="0" step="0.5" value={st.price} onChange={e=>setState(updateStreaming(state,{price:Number(e.target.value)}))}/></label><label className="range-row"><span>Digital ad load</span><input type="range" min="0" max="12" value={st.adLoad} onChange={e=>setState(updateStreaming(state,{adLoad:Number(e.target.value)}))}/><b>{st.adLoad}</b></label><label className="range-row"><span>Broadcast window</span><input type="range" min="0" max="90" value={st.libraryWindow} onChange={e=>setState(updateStreaming(state,{libraryWindow:Number(e.target.value)}))}/><b>{st.libraryWindow}d</b></label></>}</Card><Card className="pad"><SectionTitle title="Distribution Tension" sub="Streaming changes the economics of affiliates, advertising and library value."/><div className="logic-list"><div><b>Subscription</b><span>Highest direct revenue per subscriber; little digital ad inventory.</span></div><div><b>Advertising</b><span>Low barrier, scale-driven, sensitive to ad technology.</span></div><div><b>Hybrid</b><span>Balanced model with both subscription and ad income.</span></div><div><b>Windowing</b><span>A later streaming window protects linear exclusivity; an earlier one boosts digital value.</span></div></div></Card></div>
}
