import React, { useMemo, useState } from 'react';
import { Card, ConfirmButton, Empty, Pill, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { acquireIP, isMovieLicenseAvailable, licenseContent, placeSportBid, programPnL, setAdAgency, signSponsor } from '../game/simulation.js';
import { getIP } from '../game/simulation.js';
import { money, num } from '../game/utils.js';

export default function Business({state,setState}){
  const [tab,setTab]=useState('ads');
  return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">QUADRANT III</span><h1>Business</h1><p>Monetize audience, license programming, buy rights and build an IP portfolio.</p></div></div><Tabs value={tab} onChange={setTab} items={[["ads","Advertising"],["sponsors","Sponsors"],["movies","Movie Libraries"],["sports","Sports Rights"],["ip","IP Market"],["finance","Finance"]]}/>{tab==='ads'&&<Advertising state={state} setState={setState}/>} {tab==='sponsors'&&<Sponsors state={state} setState={setState}/>} {tab==='movies'&&<Movies state={state} setState={setState}/>} {tab==='sports'&&<Sports state={state} setState={setState}/>} {tab==='ip'&&<IPMarket state={state} setState={setState}/>} {tab==='finance'&&<Finance state={state}/>}</div>
}

function Advertising({state,setState}){
  const active=state.adAgencyContract&&state.agencies.find(a=>a.id===state.adAgencyContract.agencyId);
  return <div className="page-stack"><Card className="pad business-explainer"><SectionTitle title="Base Advertising" sub="You do not sell individual toothpaste spots. Sign an agency; the agency monetizes standard inventory based on audience, share, daypart and negotiated economics."/>{active?<div className="contract-banner"><div><span className="eyebrow">ACTIVE REPRESENTATION</span><h2>{active.name}</h2><p>{active.description}</p></div><div><b>{money(active.cpm)} CPM</b><span>{Math.round(active.baseShare*100)}% agency commission · {active.term} year term</span></div></div>:<div className="warning-box">No advertising representation. Standard audience currently earns no base advertising revenue; sponsorship revenue is separate.</div>}</Card><div className="candidate-grid agency-grid">{state.agencies.map(a=><Card className={`pad agency-card ${active?.id===a.id?'selected':''}`} key={a.id}><span className="eyebrow">ADVERTISING AGENCY</span><h2>{a.name}</h2><p>{a.description}</p><div className="detail-list"><p><span>Base CPM</span><b>{money(a.cpm)}</b></p><p><span>Agency commission</span><b>{Math.round(a.baseShare*100)}%</b></p><p><span>Contract</span><b>{a.term} year{a.term===1?'':'s'}</b></p><p><span>Sales quality</span><b>{a.quality}/100</b></p></div><ConfirmButton className="primary big" disabled={active?.id===a.id} label={active?.id===a.id?'Current Agency':'Sign Representation Deal'} confirmLabel="Confirm agency contract" onConfirm={()=>setState(setAdAgency(state,a.id))}/></Card>)}</div></div>
}

function Sponsors({state,setState}){
  const eligible=state.programs.filter(p=>p.status!=='Pre-production');const [programId,setProgramId]=useState(eligible[0]?.id||'');
  return <div className="page-stack"><Card className="pad"><SectionTitle title="Brand Sponsorships" sub="This is where brands—not the ad agency—attach directly to a show, event or sports property."/><label className="large-select">Program / property<select value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Select program…</option>{eligible.map(p=><option key={p.id} value={p.id}>{p.title} · {p.format} / {p.genre}</option>)}</select></label></Card><div className="candidate-grid sponsor-grid">{state.sponsorships.map(x=>{const p=state.programs.find(y=>y.id===x.programId);return <Card className="pad sponsor-card" key={x.id}><span className="eyebrow">{x.category}</span><h2>{x.brand}</h2><p>Best target: {x.target} · minimum audience {num(x.minimumAudience)}</p><div className="sponsor-offer"><div><span>Duration</span><b>{x.weeks} weeks</b></div><div><span>Fixed</span><b>{money(x.fixed)}</b></div><div><span>Variable</span><b>{money(x.variablePerMillion)} / 1M viewers</b></div></div>{x.status==='Active'?<Pill tone="ok">Sponsors {p?.title||'program'} · {Math.ceil(x.weeksRemaining)} weeks left</Pill>:<ConfirmButton className="primary" disabled={!programId} label="Accept Sponsor Offer" confirmLabel="Confirm sponsor" onConfirm={()=>setState(signSponsor(state,x.id,programId))}/>}</Card>})}</div></div>
}

function Movies({state,setState}){
  const [selected,setSelected]=useState(null),pack=state.contentMarket.find(x=>x.id===selected);const [movieId,setMovieId]=useState('');
  const choose=id=>{setSelected(id);const p=state.contentMarket.find(x=>x.id===id);setMovieId(p?.movies?.[0]?.id||'')};
  return <div className="page-stack"><Card className="pad"><SectionTitle title="Movie & Library Marketplace" sub="License one movie, a four-film monthly rotation, or the entire 10/50-film package. Each licensed movie arrives with two broadcast runs."/></Card><div className="library-market">{state.contentMarket.map(p=><button className={`library-package ${selected===p.id?'active':''}`} key={p.id} onClick={()=>choose(p.id)}><div className="library-art"><b>{p.title.split(' ')[0]}</b><span>{p.packageSize}</span></div><div><span className="eyebrow">{p.genre}</span><h3>{p.title}</h3><p>{p.packageSize} movies · {money(p.fullCost)} full package</p><div><Pill>Viewer {(p.viewer/10).toFixed(1)}</Pill><Pill>Critic {p.critic}%</Pill></div></div></button>)}</div>{pack&&<Card className="pad license-drawer-card"><SectionTitle title={pack.title} sub={`${pack.packageSize}-movie ${pack.genre} library`}/><div className="split-layout"><div><label className="large-select">Starting movie<select value={movieId} onChange={e=>setMovieId(e.target.value)}>{pack.movies.map(m=><option key={m.id} value={m.id}>{m.name} · {(m.viewer/10).toFixed(1)} viewer · {m.critic}% critic</option>)}</select></label><div className="movie-sample-list">{pack.movies.slice(0,10).map(m=><div key={m.id}><b>{m.name}</b><span>{(m.viewer/10).toFixed(1)} · {m.critic}%</span></div>)}{pack.packageSize>10&&<small>+ {pack.packageSize-10} more titles in the full package</small>}</div></div><div className="license-options"><LicenseOption title="Single Movie" count={1} cost={pack.fullCost/pack.packageSize*1.35} available={isMovieLicenseAvailable(state,pack.id,'single',movieId)} onClick={()=>setState(licenseContent(state,pack.id,'single',movieId))}/><LicenseOption title="Monthly Cycle" subtitle="4 films · one per week" count={4} cost={pack.fullCost/pack.packageSize*4*1.15} available={isMovieLicenseAvailable(state,pack.id,'four',movieId)} onClick={()=>setState(licenseContent(state,pack.id,'four',movieId))}/><LicenseOption title="Entire Package" count={pack.packageSize} cost={pack.fullCost} available={isMovieLicenseAvailable(state,pack.id,'full',movieId)} onClick={()=>setState(licenseContent(state,pack.id,'full',movieId))}/></div></div></Card>}</div>
}
function LicenseOption({title,subtitle,count,cost,onClick,available=true}){return <div className={`license-option ${!available?'locked':''}`}><span>{count} title{count===1?'':'s'}</span><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}<b>{money(cost)}</b>{available?<ConfirmButton className="primary" label="License" confirmLabel={`Confirm · ${money(cost)}`} onConfirm={onClick}/>:<Pill tone="ok">Rights already licensed</Pill>}</div>}

function Sports({state,setState}){
  const [scope,setScope]=useState('all'),[sport,setSport]=useState('all');const sports=state.sports.filter(x=>(scope==='all'||x.scope===scope)&&(sport==='all'||x.sport===sport)),sportsList=[...new Set(state.sports.map(x=>x.sport))];
  return <div className="page-stack"><div className="filter-bar"><label>Rights scale<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All</option><option value="local">Local</option><option value="state">State</option><option value="regional">Regional</option><option value="national">National</option><option value="international">International</option></select></label><label>Sport<select value={sport} onChange={e=>setSport(e.target.value)}><option value="all">All sports</option>{sportsList.map(x=><option key={x}>{x}</option>)}</select></label></div><Card className="pad"><SectionTitle title="Sports Rights Auctions" sub="From high-school games to massive national packages. Live rights create the event; you can then build sports news, pregame, postgame and talk around it."/><div className="table-wrap"><table className="sports-table"><thead><tr><th>Competition</th><th>Scale</th><th>Target</th><th>Events</th><th>Schedule</th><th>Term</th><th>Current bid</th><th>Leader</th><th></th></tr></thead><tbody>{sports.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.sport} · popularity {x.popularity}</small></td><td>{x.scope}</td><td>{x.target}</td><td>{x.events}</td><td>{x.schedule}</td><td>{x.term}y</td><td>{money(x.currentBid)}</td><td>{x.owned?<Pill tone="ok">Owned</Pill>:x.leader||'—'}</td><td>{x.owned?<span>Won</span>:x.bidEnds>0?<ConfirmButton className="primary" label={`Bid · ${x.bidEnds}d`} confirmLabel={`Confirm ${money(Math.round(((x.currentBid||x.cost*.75)*(x.leader?1.1:1.06))/10000)*10000)}`} onConfirm={()=>setState(placeSportBid(state,x.id))}/>:<span>Auction closed</span>}</td></tr>)}</tbody></table></div></Card></div>
}

function IPMarket({state,setState}){return <div className="page-stack"><Card className="pad"><SectionTitle title="IP Rights Market" sub="Popularity, novelty, fandom, flexibility and merchandising potential are separate assets."/></Card><div className="candidate-grid ip-market-grid">{state.ipMarket.map(ip=><Card className="pad ip-card" key={ip.id}><span className="eyebrow">{ip.type}</span><h2>{ip.name}</h2><div className="ip-score-grid"><StatBar label="Popularity" value={ip.popularity}/><StatBar label="Novelty" value={ip.novelty}/><StatBar label="Fandom" value={ip.fandom}/><StatBar label="Prestige" value={ip.prestige}/><StatBar label="Flexibility" value={ip.flexibility}/><StatBar label="Merch" value={ip.merchPotential}/></div><p>{ip.rights.term}y · {ip.rights.territory} · {ip.rights.medium} · merch split {ip.rights.merchSplit}%</p><ConfirmButton className="primary" disabled={state.cash<ip.cost} label={`Acquire Rights · ${money(ip.cost)}`} confirmLabel="Confirm acquisition" onConfirm={()=>setState(acquireIP(state,ip.id))}/></Card>)}</div></div>}

function Finance({state}){
  const programRows=[...state.programs].map(p=>({p,pnl:programPnL(state,p)})).sort((a,b)=>b.pnl.contribution-a.pnl.contribution),rights=state.contracts.reduce((a,x)=>a+(x.annualCost||0),0),payroll=state.employees.reduce((a,x)=>a+(x.salary||0),0);
  return <div className="page-stack"><div className="metric-grid"><div className="metric"><span>Cash</span><strong>{money(state.cash)}</strong></div><div className="metric"><span>Total Revenue</span><strong>{money(state.totalRevenue)}</strong></div><div className="metric"><span>Annual Payroll</span><strong>{money(payroll)}</strong></div><div className="metric"><span>Annual Rights Commitments</span><strong>{money(rights)}</strong></div></div><Card className="pad"><SectionTitle title="Program Economics" sub="Revenue is credited to the program that generated the audience or licensing value."/>{programRows.length?<div className="table-wrap"><table><thead><tr><th>Program</th><th>Revenue</th><th>Production</th><th>Marketing</th><th>Contribution</th></tr></thead><tbody>{programRows.map(({p,pnl})=><tr key={p.id}><td><b>{p.title}</b><small>{p.format} · {p.genre}</small></td><td>{money(pnl.revenue)}</td><td>{money(pnl.production)}</td><td>{money(pnl.marketing)}</td><td className={pnl.contribution>=0?'positive':'negative'}>{money(pnl.contribution)}</td></tr>)}</tbody></table></div>:<Empty>No program economics yet.</Empty>}</Card></div>
}
