import React, { useMemo, useState } from 'react';
import { Card, ConfirmButton, Empty, Pill, ProgramPoster, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { ProgramProfile, RivalProgramProfile } from '../components/Profiles.jsx';
import { BAND_LABELS, BROADCAST_SLOTS, DAYS, FORMAT_EXPERTISE, slotBand } from '../game/constants.js';
import { audienceRankings, calcAudience, currentProgramRankings, getProgram, historicalRecords, isSchedulable, removeScheduleBlock, scheduleBlockEnd, scheduleRecurring, scheduleRuleSummary, setNetworkLaunchDate } from '../game/simulation.js';
import { money, num } from '../game/utils.js';

const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const fitsBroadcastWindow=(start,duration)=>{const a=mins(start),e=a+Number(duration||30);return !(a<720&&e>720);};
const formatTime=t=>{let [h,m]=t.split(':').map(Number),s=h>=12?'PM':'AM',hh=h%12||12;return `${hh}:${String(m).padStart(2,'0')} ${s}`};

export default function Channel({state,setState}){
  const [tab,setTab]=useState('schedule');
  const [programId,setProgramId]=useState(null),[rivalRow,setRivalRow]=useState(null);
  const program=state.programs.find(p=>p.id===programId);
  return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">QUADRANT II</span><h1>Channel</h1><p>Schedule television, compete for audience, and measure what actually wins.</p></div></div><Tabs value={tab} onChange={setTab} items={[["schedule","Programming"],["audience","Audience"],["competition","Networks"],["programs","Programs"],["records","Records"],["brand","Network"]]}/>
    {tab==='schedule'&&<Schedule state={state} setState={setState}/>} 
    {tab==='audience'&&<Audience state={state}/>} 
    {tab==='competition'&&<Competition state={state}/>} 
    {tab==='programs'&&<ProgramRankings state={state} onOpen={setProgramId} onOpenRival={setRivalRow}/>} 
    {tab==='records'&&<Records state={state}/>} 
    {tab==='brand'&&<Brand state={state}/>} 
    <ProgramProfile state={state} p={program} onClose={()=>setProgramId(null)}/><RivalProgramProfile state={state} row={rivalRow} onClose={()=>setRivalRow(null)}/>
  </div>
}

function Schedule({state,setState}){
  const defaultLaunch=(()=>{const d=new Date(`${state.date}T12:00:00`);d.setDate(d.getDate()+21);return d.toISOString().slice(0,10)})();
  const [launchDate,setLaunchDate]=useState(state.network.launchDate||defaultLaunch);
  const [day,setDay]=useState(DAYS[(new Date(`${state.date}T12:00:00`).getDay()+6)%7]);
  const eligible=state.programs.filter(isSchedulable),[selected,setSelected]=useState(eligible[0]?.id||'');
  const [recurrence,setRecurrence]=useState('once'),[recDays,setRecDays]=useState([day]),[weeks,setWeeks]=useState(4),[asLong,setAsLong]=useState(false);
  React.useEffect(()=>{if(selected&&!eligible.some(p=>p.id===selected))setSelected(eligible[0]?.id||'')},[state.programs.length,state.programs.map(p=>p.pipeline.ready-p.pipeline.aired).join('|')]);
  React.useEffect(()=>{if(recurrence!=='daily')setRecDays([day])},[day,recurrence]);
  if(!state.network.launchDate)return <Card className="pad launch-date-card"><SectionTitle title="Choose the Network Launch Date" sub="Until you commit to an initial air date, the broadcast grid remains locked. Use pre-launch time to hire, write, build, acquire rights and prepare programming."/><div className="launch-date-content"><div><span className="eyebrow">CURRENT DATE</span><strong>{state.date}</strong></div><label>Initial air date<input type="date" min={state.date} value={launchDate} onChange={e=>setLaunchDate(e.target.value)}/></label><ConfirmButton className="primary big" label="Commit Launch Date" confirmLabel={`Launch ${launchDate}`} onConfirm={()=>setState(setNetworkLaunchDate(state,launchDate))}/></div><div className="creative-note"><b>No broadcast operations yet</b><p>Before launch there is no airing revenue and no daily transmission operating charge. Development, staffing, construction and rights costs still occur because you are building the company.</p></div></Card>;
  const blocks=state.scheduleBlocks[day]||[],selectedP=getProgram(state,selected),covered=slot=>blocks.some(b=>{const p=getProgram(state,b.programId),a=mins(b.start),e=a+(p?.duration||b.duration||30),x=mins(slot);return x>=a&&x<e});
  const toggleDay=d=>setRecDays(x=>x.includes(d)?x.filter(y=>y!==d):[...x,d]);
  const place=t=>setState(scheduleRecurring(state,{programId:selected,start:t,recurrence,days:recurrence==='daily'?recDays:[day],weeks,asLongAsEpisodes:asLong,primaryDay:day}));
  const remaining=selectedP?Math.max(1,selectedP.episodes-Math.floor(selectedP.pipeline.aired||0)):1,maxWeeks=selectedP?Math.max(1,remaining):1;
  return <div className="schedule-layout outlook-layout"><Card className="pad span-2"><SectionTitle title="Broadcast Calendar" sub={`Launch ${state.network.launchDate} · 9 AM–12 PM and 3 PM–12 AM. 30m / 1h / 2h originals consume real calendar space.`}/><div className="day-switch">{DAYS.map(d=><button key={d} className={day===d?'active':''} onClick={()=>setDay(d)}>{d}</button>)}</div>{eligible.length?<div className="schedule-program-picker"><span>Place:</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{eligible.map(p=><option value={p.id} key={p.id}>{p.title} · {p.duration}m · {Math.max(0,Math.floor(p.pipeline.ready-p.pipeline.aired))} ready / {Math.max(0,p.episodes-Math.floor(p.pipeline.aired))} season remaining</option>)}</select></div>:<div className="warning-box">Nothing is schedulable yet. License movies or deliver an original episode first.</div>}
      <div className="recurrence-panel"><div><span className="eyebrow">RECURRENCE</span><div className="segmented">{[['once','Non recurring'],['weekly','Weekly'],['daily','Daily / selected days']].map(([k,l])=><button className={recurrence===k?'active':''} onClick={()=>setRecurrence(k)} key={k}>{l}</button>)}</div></div>{recurrence==='daily'&&<div><span className="eyebrow">DAYS</span><div className="day-checks">{DAYS.map(d=><button key={d} className={recDays.includes(d)?'active':''} onClick={()=>toggleDay(d)}>{d}</button>)}</div></div>}{recurrence!=='once'&&<div className="recurrence-terms"><label>Repeat for<input type="number" min="1" max={Math.max(1,maxWeeks)} value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/><span>weeks</span></label><label className="checkbox-line"><input type="checkbox" checked={asLong} onChange={e=>setAsLong(e.target.checked)}/>As long as season episodes exist</label>{selectedP&&<small>{asLong?`Uses all ${remaining} remaining season episodes, including episodes still being written or produced.`:`Planned run: ${weeks} week${weeks===1?'':'s'}.`}</small>}</div>}</div>
      <div className="outlook-schedule" style={{'--rows':BROADCAST_SLOTS.length}}>{BROADCAST_SLOTS.map((t,i)=><div className={`time-label ${t==='15:00'?'afternoon-start':''} ${t==='20:00'?'prime-start':''}`} style={{gridRow:i+1,gridColumn:1}} key={`time-${t}`}><b>{formatTime(t)}</b>{t==='20:00'&&<span>PRIME</span>}</div>)}{BROADCAST_SLOTS.map((t,i)=>{const valid=selectedP?fitsBroadcastWindow(t,selectedP.duration):true;return !covered(t)?<button className={`empty-calendar-cell ${!valid?'invalid':''} ${t==='15:00'?'afternoon-start':''} ${t==='20:00'?'prime-start':''}`} style={{gridRow:i+1,gridColumn:2}} key={`empty-${t}`} disabled={!selectedP||!valid||(recurrence==='daily'&&!recDays.length)} onClick={()=>place(t)}><span>{valid?'＋':'—'}</span><small>{selectedP?(valid?`Start ${selectedP.title}`:'Would cross noon blackout'):'Open'}</small></button>:null})}{blocks.map(b=>{const p=getProgram(state,b.programId);if(!p)return null;const row=BROADCAST_SLOTS.indexOf(b.start);if(row<0)return null;const nominal=Math.ceil(p.duration/30),visible=Math.max(1,Math.min(nominal,BROADCAST_SLOTS.length-row)),preview=calcAudience(state,p,b.start,state.date),rule=state.scheduleRules.find(r=>r.id===b.ruleId);return <div className={`calendar-block band-${slotBand(b.start)}`} style={{gridRow:`${row+1} / span ${visible}`,gridColumn:2}} key={b.id}><ProgramPoster p={p} compact/><div><span>{formatTime(b.start)} → {scheduleBlockEnd(b,p)}</span><b>{p.title}</b><small>{p.duration}m · forecast {num(preview.audience)}</small>{rule&&<em>{rule.recurrence==='once'?'one-time':`${rule.recurrence} · through ${rule.endDate}`}</em>}</div><button title="Remove recurrence" onClick={()=>setState(removeScheduleBlock(state,day,b.id))}>×</button></div>})}</div>
    </Card><Card className="pad schedule-sidebar"><SectionTitle title="Available Programming" sub="Select content, recurrence, then tap a start time."/>{eligible.map(p=><button className={`schedule-library-card ${selected===p.id?'active':''}`} onClick={()=>setSelected(p.id)} key={p.id}><ProgramPoster p={p} compact/><span><b>{p.title}</b><small>{p.genre} · {p.duration}m</small><em>{Math.max(0,Math.floor(p.pipeline.ready-p.pipeline.aired))} ready · {Math.max(0,p.episodes-Math.floor(p.pipeline.aired))} season left</em></span></button>)}{!eligible.length&&<Empty>Your schedule is dead air.</Empty>}<SectionTitle title="Active Runs"/>{state.scheduleRules.length?state.scheduleRules.map(r=>{const x=scheduleRuleSummary(state,r);return <div className="run-summary" key={r.id}><b>{x.title}</b><span>{x.days} · {formatTime(x.start)}</span><small>Ends {x.endDate} · {x.remaining} planned airings left</small></div>}):<Empty>No recurring runs yet.</Empty>}</Card></div>
}
function Audience({state}){
  const [period,setPeriod]=useState('yesterday'),[scope,setScope]=useState('local');const rows=audienceRankings(state,period,scope),playerRank=rows.findIndex(x=>x.id==='player')+1;
  const months=useMemo(()=>{const map={};(state.networkAudienceHistory||[]).forEach(x=>{const m=x.date.slice(0,7);map[m]=(map[m]||0)+(x[scope]||0)});return Object.entries(map).slice(-12)},[state.networkAudienceHistory,scope]);const max=Math.max(1,...months.map(x=>x[1]));
  return <div className="page-stack"><div className="filter-bar"><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="yesterday">Yesterday</option><option value="month">Current Month</option><option value="year">Current Year</option></select></label><label>Market<select value={scope} onChange={e=>setScope(e.target.value)}><option value="local">Original Local Market</option><option value="state">Home State</option><option value="national">National / Total Reach</option></select></label></div><div className="metric-grid"><div className="metric"><span>Your rank</span><strong>#{playerRank}</strong><small>of {rows.length} tracked networks</small></div><div className="metric"><span>Avg Daily Audience</span><strong>{num(rows.find(x=>x.id==='player')?.audience||0)}</strong><small>{period} · {scope}</small></div><div className="metric"><span>Total Audience</span><strong>{num(rows.find(x=>x.id==='player')?.totalAudience||0)}</strong><small>sum of tracked viewing</small></div><div className="metric"><span>Leader</span><strong>{rows[0]?.name}</strong><small>{num(rows[0]?.audience||0)}</small></div></div><div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Network Audience Ranking" sub="15 persistent rival networks plus your network."/><RankingTable rows={rows}/></Card><Card className="pad"><SectionTitle title="Monthly Evolution" sub="Your audience across the selected market."/><div className="bar-chart">{months.length?months.map(([m,v])=><div key={m}><i style={{height:`${Math.max(4,v/max*100)}%`}}/><span>{m.slice(5)}</span><small>{num(v)}</small></div>):<Empty>No audience history yet.</Empty>}</div></Card></div></div>
}
function RankingTable({rows}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Network</th><th>Scope</th><th>Total Audience</th><th>Avg Audience</th><th>Prestige</th><th>Revenue</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={r.id==='player'?'player-row':''}><td>{i+1}</td><td><b>{r.name}</b></td><td>{r.scope}</td><td>{num(r.totalAudience||r.audience)}</td><td>{num(r.audience)}</td><td>{Math.round(r.prestige||0)}</td><td>{money(r.revenue||0)}</td></tr>)}</tbody></table></div>}

function Competition({state}){
  const [sort,setSort]=useState('prestige');
  const recent=(state.financeLog||[]).slice(-30),days=Math.max(1,recent.length),playerRevenueRunRate=recent.reduce((a,x)=>a+(x.revenue||0),0)/days*365;
  const rows=[{id:'player',name:state.network.name,scope:'Player',prestige:state.network.prestige,revenue:playerRevenueRunRate,strength:state.network.prestige||0},...state.competitors].sort((a,b)=>(b[sort]||0)-(a[sort]||0));
  return <div className="page-stack"><div className="filter-bar"><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="prestige">Prestige</option><option value="revenue">Annual Revenue / Run Rate</option><option value="strength">Competitive strength</option></select></label></div><Card className="pad"><SectionTitle title="Competitive Landscape" sub="Four national, four state, three local and four specialist networks. Rival revenue is annual; yours is annualized from the latest 30 simulated days."/><div className="network-card-grid">{rows.map((r,i)=><div className={`network-rank-card ${r.id==='player'?'player':''}`} key={r.id}><span>#{i+1} · {r.scope}</span><h3>{r.name}</h3><p>{r.identity||'Your network'}</p><div><b>Prestige {Math.round(r.prestige||0)}</b><b>Revenue {money(r.revenue||0)}</b></div></div>)}</div></Card></div>
}

function ProgramRankings({state,onOpen,onOpenRival}){
  const [scope,setScope]=useState('local'),[format,setFormat]=useState('all'),[band,setBand]=useState('all'),[sort,setSort]=useState('audience');let rows=currentProgramRankings(state,{scope,format,band});rows=[...rows].sort((a,b)=>(b[sort]||0)-(a[sort]||0));
  return <div className="page-stack"><div className="filter-bar"><label>Market<select value={scope} onChange={e=>setScope(e.target.value)}><option value="local">Local</option><option value="state">State</option><option value="national">National</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="all">All formats</option>{FORMAT_EXPERTISE.map(x=><option key={x}>{x}</option>)}</select></label><label>Slot<select value={band} onChange={e=>setBand(e.target.value)}><option value="all">All slots</option>{Object.entries(BAND_LABELS).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="audience">Average Audience</option><option value="totalAudience">Total Audience</option><option value="viewer">Viewer Score</option><option value="critic">Critic Score</option></select></label></div><Card className="pad"><SectionTitle title="Current Year Programs" sub="Every tracked network competes inside the same slot and format rankings."/>{rows.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>Program</th><th>Network</th><th>Format</th><th>Slot</th><th>Total Audience</th><th>Avg Audience</th><th>Viewer</th><th>Critic</th></tr></thead><tbody>{rows.map((r,i)=>{const own=state.programs.find(p=>p.title===r.title&&r.network===state.network.initials);return <tr key={`${r.network}-${r.title}`} className={`click-row ${own?'player-row':''}`} onClick={()=>own?onOpen(own.id):onOpenRival(r)}><td>{i+1}</td><td><b>{r.title}</b><small>{r.genre}</small></td><td>{r.network}</td><td>{r.format}</td><td>{BAND_LABELS[r.band]||r.band}</td><td>{num(r.totalAudience||0)}</td><td>{num(r.audience)}</td><td>{Number(r.viewer||0).toFixed(1)}</td><td>{Math.round(r.critic||0)}%</td></tr>})}</tbody></table></div>:<Empty>No programs have aired yet.</Empty>}</Card></div>
}

function Records({state}){const [format,setFormat]=useState('all'),[metric,setMetric]=useState('audience');const rows=historicalRecords(state,{format,metric});return <div className="page-stack"><div className="filter-bar"><label>Category<select value={format} onChange={e=>setFormat(e.target.value)}><option value="all">All programming</option>{FORMAT_EXPERTISE.map(x=><option key={x}>{x}</option>)}</select></label><label>Record<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="audience">Audience</option><option value="viewer">Viewer Score</option><option value="critic">Critic Score</option></select></label></div><Card className="pad"><SectionTitle title="All-Time Top 10" sub="Current-year leaders are provisional. December 31 archives them into permanent history."/>{rows.length?<div className="record-list">{rows.map((r,i)=><div className="record-row" key={`${r.year}-${r.network}-${r.title}`}><strong>{i+1}</strong><div><b>{r.title}</b><span>{r.network} · {r.format} · {r.year}</span></div><em>{metric==='audience'?num(r.audience):metric==='viewer'?Number(r.viewer).toFixed(1):`${Math.round(r.critic)}%`}</em></div>)}</div>:<Empty>No records yet. The record book grows as television airs.</Empty>}</Card></div>}

function Brand({state}){return <div className="dashboard-grid"><Card className="pad"><SectionTitle title="Format Expertise" sub="You started with two stars in one format; experience grows by making television."/>{FORMAT_EXPERTISE.map(f=><div className="expertise-row" key={f}><div><b>{f}</b><small>{'★'.repeat(Math.floor((state.network.expertise[f]||0)/2))}{'☆'.repeat(5-Math.floor((state.network.expertise[f]||0)/2))}</small></div><strong>{(state.network.expertise[f]||0).toFixed(1)} / 10</strong></div>)}</Card><Card className="pad"><SectionTitle title="Network Brand"/><StatBar label="Prestige" value={state.network.prestige}/><StatBar label="Trust" value={state.network.trust}/><StatBar label="Sports" value={state.network.sports}/><StatBar label="Youth" value={state.network.youth}/><StatBar label="Family" value={state.network.family}/><StatBar label="Innovation" value={state.network.innovation}/></Card></div>}
