import React, { useMemo, useState } from 'react';
import { Card, ConfirmButton, Drawer, Empty, Pill, ProgramPoster, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { ProgramProfile, RivalProgramProfile } from '../components/Profiles.jsx';
import { BAND_LABELS, BROADCAST_SLOTS, DAYS, FORMAT_EXPERTISE, slotBand } from '../game/constants.js';
import { audienceRankings, calcAudience, currentProgramRankings, getProgram, historicalRecords, isSchedulable, networkAwardScope, removeScheduleBlock, scheduleBlockEnd, scheduleRecurring, scheduleRuleActiveOnDate, scheduleRuleSummary, setNetworkLaunchDate } from '../game/simulation.js';
import { money, num } from '../game/utils.js';

const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const fitsBroadcastWindow=(start,duration)=>{const a=mins(start),e=a+Number(duration||30);return !(a<720&&e>720);};
const formatTime=t=>{let [h,m]=t.split(':').map(Number),s=h>=12?'PM':'AM',hh=h%12||12;return `${hh}:${String(m).padStart(2,'0')} ${s}`};

export default function Channel({state,setState}){
  const [tab,setTab]=useState('schedule');
  const [programId,setProgramId]=useState(null),[rivalRow,setRivalRow]=useState(null);
  const program=state.programs.find(p=>p.id===programId);
  return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">QUADRANT II</span><h1>Channel</h1><p>Schedule television, compete for audience, and measure what actually wins.</p></div></div><Tabs value={tab} onChange={setTab} items={[["schedule","Programming"],["audience","Audience"],["competition","Networks"],["programs","Programs"],["records","Records"],["awards","Awards"],["brand","Network"]]}/>
    {tab==='schedule'&&<Schedule state={state} setState={setState}/>} 
    {tab==='audience'&&<Audience state={state}/>} 
    {tab==='competition'&&<Competition state={state}/>} 
    {tab==='programs'&&<ProgramRankings state={state} onOpen={setProgramId} onOpenRival={setRivalRow}/>} 
    {tab==='records'&&<Records state={state}/>} 
    {tab==='awards'&&<Awards state={state}/>} 
    {tab==='brand'&&<Brand state={state}/>} 
    <ProgramProfile state={state} p={program} onClose={()=>setProgramId(null)}/><RivalProgramProfile state={state} row={rivalRow} onClose={()=>setRivalRow(null)}/>
  </div>
}

function dateAdd(date,days){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function mondayOf(date){const d=new Date(`${date}T12:00:00`),idx=(d.getDay()+6)%7;d.setDate(d.getDate()-idx);return d.toISOString().slice(0,10)}
function dateLabel(date){return new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function dayFromDate(date){return DAYS[(new Date(`${date}T12:00:00`).getDay()+6)%7]}

function Schedule({state,setState}){
  const defaultLaunch=dateAdd(state.date,21),[launchDate,setLaunchDate]=useState(state.network.launchDate||defaultLaunch);
  const [weekStart,setWeekStart]=useState(mondayOf(state.date)),[selectedDate,setSelectedDate]=useState(state.date),[slotDraft,setSlotDraft]=useState(null);
  const eligible=state.programs.filter(isSchedulable),selectedDay=dayFromDate(selectedDate);
  const [selected,setSelected]=useState(eligible[0]?.id||''),[recurrence,setRecurrence]=useState('once'),[recDays,setRecDays]=useState([selectedDay]),[weeks,setWeeks]=useState(4),[asLong,setAsLong]=useState(false);
  React.useEffect(()=>{if(selected&&!eligible.some(p=>p.id===selected))setSelected(eligible[0]?.id||'')},[state.programs.length,state.programs.map(p=>p.pipeline.ready-p.pipeline.aired).join('|')]);
  React.useEffect(()=>{setRecDays([selectedDay])},[selectedDate]);
  if(!state.network.launchDate)return <Card className="pad launch-date-card channel-launch"><SectionTitle title="Choose the Network Launch Date" sub="Until you commit to an initial air date, the broadcast grid remains locked. Use pre-launch time to hire, write, build, acquire rights and prepare programming."/><div className="launch-date-content"><div><span className="eyebrow">CURRENT DATE</span><strong>{state.date}</strong></div><label>Initial air date<input type="date" min={state.date} value={launchDate} onChange={e=>setLaunchDate(e.target.value)}/></label><ConfirmButton className="primary big" label="Commit Launch Date" confirmLabel={`Launch ${launchDate}`} onConfirm={()=>setState(setNetworkLaunchDate(state,launchDate))}/></div><div className="creative-note"><b>No broadcast operations yet</b><p>Before launch there is no airing revenue and no daily transmission operating charge. Development, staffing, construction and rights costs still occur because you are building the company.</p></div></Card>;
  const selectedP=getProgram(state,selected),blocks=(state.scheduleBlocks[selectedDay]||[]).filter(b=>{const rule=state.scheduleRules.find(r=>r.id===b.ruleId);return !rule||scheduleRuleActiveOnDate(state,rule,selectedDate)});
  const covered=slot=>blocks.some(b=>{const p=getProgram(state,b.programId),a=mins(b.start),e=a+(p?.duration||b.duration||30),x=mins(slot);return x>=a&&x<e});
  const toggleDay=d=>setRecDays(x=>x.includes(d)?x.filter(y=>y!==d):[...x,d]);
  const openSlot=t=>{setSlotDraft({start:t,date:selectedDate});setRecurrence('once');setRecDays([selectedDay]);setWeeks(4);setAsLong(false);if(!selected&&eligible[0])setSelected(eligible[0].id)};
  const place=()=>{if(!slotDraft||!selected)return;setState(scheduleRecurring(state,{programId:selected,start:slotDraft.start,startDate:slotDraft.date,recurrence,days:recurrence==='daily'?recDays:[selectedDay],weeks,asLongAsEpisodes:asLong,primaryDay:selectedDay}));setSlotDraft(null)};
  const remaining=selectedP?Math.max(1,selectedP.episodes-Math.floor(selectedP.pipeline.aired||0)):1,maxWeeks=Math.max(1,remaining);
  const weekDates=Array.from({length:7},(_,i)=>dateAdd(weekStart,i));
  return <div className="page-stack tv-guide-shell"><Card className="pad tv-guide-header"><div className="schedule-week-head"><div><span className="eyebrow">ELECTRONIC PROGRAM GUIDE</span><h2>Broadcast Calendar</h2><p>Click a half-hour slot first. Then schedule content and recurrence in the booking window.</p></div><div className="week-controls"><button onClick={()=>{const w=dateAdd(weekStart,-7);setWeekStart(w);setSelectedDate(w)}}>← Previous</button><button onClick={()=>{const w=mondayOf(state.date);setWeekStart(w);setSelectedDate(state.date)}}>Today</button><button onClick={()=>{const w=dateAdd(weekStart,7);setWeekStart(w);setSelectedDate(w)}}>Next →</button></div></div><div className="dated-day-switch">{weekDates.map(d=><button key={d} className={selectedDate===d?'active':''} onClick={()=>setSelectedDate(d)}><b>{dateLabel(d).split(',')[0]}</b><span>{new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></button>)}</div></Card>
    <div className="schedule-layout outlook-layout"><Card className="pad span-2 guide-card"><SectionTitle title={`${dateLabel(selectedDate)} Programming`} sub="9 AM–12 PM and 3 PM–12 AM · Prime Time 8–10 PM"/><div className="calendar-grid tv-grid">{BROADCAST_SLOTS.map((t,row)=>{if(covered(t))return <div className="calendar-time muted-slot" key={t} style={{gridRow:row+1,gridColumn:1}}>{formatTime(t)}</div>;const disabled=!eligible.length;return <React.Fragment key={t}><div className="calendar-time" style={{gridRow:row+1,gridColumn:1}}>{formatTime(t)}</div><button disabled={disabled} className={`calendar-empty-slot band-${slotBand(t)}`} style={{gridRow:row+1,gridColumn:2}} onClick={()=>openSlot(t)}><span>+</span><small>{disabled?'No ready content':'Schedule program'}</small></button></React.Fragment>})}{blocks.map(b=>{const p=getProgram(state,b.programId);if(!p)return null;const startIndex=BROADCAST_SLOTS.indexOf(b.start);if(startIndex<0)return null;const spans=Math.ceil((p.duration||30)/30),visible=Math.min(spans,BROADCAST_SLOTS.length-startIndex),preview=calcAudience(state,p,b.start,state.date),rule=state.scheduleRules.find(r=>r.id===b.ruleId);return <div className={`calendar-block band-${slotBand(b.start)}`} style={{gridRow:`${startIndex+1} / span ${visible}`,gridColumn:2}} key={b.id}><ProgramPoster p={p} compact/><div><span>{formatTime(b.start)} → {scheduleBlockEnd(b,p)}</span><b>{p.title}</b><small>{p.duration}m · forecast {num(preview.audience)}</small>{rule&&<em>{rule.recurrence==='once'?'one-time':`${rule.recurrence} · through ${rule.endDate}`}</em>}</div><button title="Remove recurrence" onClick={()=>setState(removeScheduleBlock(state,selectedDay,b.id))}>×</button></div>})}</div></Card>
    <Card className="pad schedule-sidebar"><SectionTitle title="Active Runs" sub="Recurring bookings stay as rules rather than copied calendar blocks."/>{state.scheduleRules.length?state.scheduleRules.map(r=>{const x=scheduleRuleSummary(state,r);return <div className="run-summary" key={r.id}><b>{x.title}</b><span>{x.days} · {formatTime(x.start)}</span><small>{x.startDate?`Starts ${x.startDate} · `:''}Ends {x.endDate} · {x.remaining} planned airings</small></div>}):<Empty>No recurring runs yet.</Empty>}<SectionTitle title="Available Inventory"/><div className="inventory-mini">{eligible.slice(0,8).map(p=><div key={p.id}><b>{p.title}</b><span>{p.duration}m · {Math.max(0,Math.floor(p.pipeline.ready-p.pipeline.aired))} ready</span></div>)}</div></Card></div>
    <Drawer open={!!slotDraft} title={slotDraft?`Schedule · ${dateLabel(slotDraft.date)} · ${formatTime(slotDraft.start)}`:''} onClose={()=>setSlotDraft(null)} wide>{slotDraft&&<div className="schedule-booking"><SectionTitle title="Choose Programming" sub="Like booking a meeting: the selected duration consumes contiguous half-hour cells."/>{eligible.length?<div className="booking-programs">{eligible.map(p=><button className={selected===p.id?'active':''} key={p.id} onClick={()=>setSelected(p.id)}><ProgramPoster p={p} compact/><div><b>{p.title}</b><span>{p.format} · {p.genre} · {p.duration}m</span><small>{Math.max(0,Math.floor(p.pipeline.ready-p.pipeline.aired))} ready · {Math.max(0,p.episodes-Math.floor(p.pipeline.aired))} season remaining</small></div></button>)}</div>:<Empty>No content is ready to schedule.</Empty>}{selectedP&&!fitsBroadcastWindow(slotDraft.start,selectedP.duration)&&<div className="warning-box">{selectedP.title} would cross the noon broadcast blackout from this start time.</div>}<SectionTitle title="Recurrence"/><div className="segmented recurrence-choice">{[['once','Non recurring'],['weekly','Weekly'],['daily','Selected days']].map(([k,l])=><button className={recurrence===k?'active':''} onClick={()=>setRecurrence(k)} key={k}>{l}</button>)}</div>{recurrence==='daily'&&<div className="day-checks">{DAYS.map(d=><button key={d} className={recDays.includes(d)?'active':''} onClick={()=>toggleDay(d)}>{d}</button>)}</div>}{recurrence!=='once'&&<div className="recurrence-terms"><label>Repeat for<input type="number" min="1" max={maxWeeks} value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/><span>weeks</span></label><label className="checkbox-line"><input type="checkbox" checked={asLong} onChange={e=>setAsLong(e.target.checked)}/>As long as season episodes exist</label>{selectedP&&<small>{asLong?`Plans against all ${remaining} remaining commissioned episodes, including those still in production.`:`Projected run: ${weeks} week${weeks===1?'':'s'}.`}</small>}</div>}<button className="primary big full" disabled={!selectedP||!fitsBroadcastWindow(slotDraft.start,selectedP.duration)||(recurrence==='daily'&&!recDays.length)} onClick={place}>Place on Schedule</button></div>}</Drawer>
  </div>;
}

function Audience({state}){
  const [period,setPeriod]=useState('yesterday'),[scope,setScope]=useState('local');const rows=audienceRankings(state,period,scope),playerRank=rows.findIndex(x=>x.id==='player')+1;
  const months=useMemo(()=>{const map={};(state.networkAudienceHistory||[]).forEach(x=>{const m=x.date.slice(0,7);map[m]=(map[m]||0)+(x[scope]||0)});return Object.entries(map).slice(-12)},[state.networkAudienceHistory,scope]);const max=Math.max(1,...months.map(x=>x[1]));
  return <div className="page-stack"><div className="filter-bar"><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="yesterday">Yesterday</option><option value="month">Current Month</option><option value="year">Current Year</option></select></label><label>Market<select value={scope} onChange={e=>setScope(e.target.value)}><option value="local">Original Local Market</option><option value="state">Home State</option><option value="national">National / Total Reach</option></select></label></div><div className="metric-grid"><div className="metric"><span>Your rank</span><strong>#{playerRank}</strong><small>of {rows.length} tracked networks</small></div><div className="metric"><span>Avg Daily Audience</span><strong>{num(rows.find(x=>x.id==='player')?.audience||0)}</strong><small>{period} · {scope}</small></div><div className="metric"><span>Total Audience</span><strong>{num(rows.find(x=>x.id==='player')?.totalAudience||0)}</strong><small>sum of tracked viewing</small></div><div className="metric"><span>Leader</span><strong>{rows[0]?.name}</strong><small>{num(rows[0]?.audience||0)}</small></div></div><div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Network Audience Ranking" sub="15 persistent rival networks plus your network."/><RankingTable rows={rows}/></Card><Card className="pad"><SectionTitle title="Monthly Evolution" sub="Your audience across the selected market."/><div className="bar-chart">{months.length?months.map(([m,v])=><div key={m}><i style={{height:`${Math.max(4,v/max*100)}%`}}/><span>{m.slice(5)}</span><small>{num(v)}</small></div>):<Empty>No audience history yet.</Empty>}</div></Card></div></div>
}
function RankingTable({rows}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Network</th><th>Scope</th><th>Total Audience</th><th>Avg Audience</th><th>Prestige</th><th>Revenue</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={r.id==='player'?'player-row':''}><td>{i+1}</td><td><b>{r.name}</b></td><td>{r.scope}</td><td>{num(r.totalAudience||r.audience)}</td><td>{num(r.audience)}</td><td>{Math.round(r.prestige||0)}</td><td>{money(r.revenue||0)}</td></tr>)}</tbody></table></div>}

function Competition({state}){
  const [sort,setSort]=useState('prestige');
  const recent=(state.financeLog||[]).slice(-30),days=Math.max(1,recent.length),playerRevenueRunRate=recent.reduce((a,x)=>a+(x.revenue||0),0)/days*365;
  const rows=[{id:'player',name:state.network.name,scope:'Player',prestige:state.network.prestige,revenue:playerRevenueRunRate,strength:state.network.prestige||0},...state.competitors].sort((a,b)=>(b[sort]||0)-(a[sort]||0));
  return <div className="page-stack"><div className="filter-bar"><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="prestige">Prestige</option><option value="revenue">Annual Revenue / Run Rate</option><option value="strength">Competitive strength</option></select></label></div><Card className="pad"><SectionTitle title="Competitive Landscape" sub="Four national, four state, three local and four specialist networks. Rival revenue is annual; yours is annualized from the latest 30 simulated days."/><div className="network-card-grid">{rows.map((r,i)=><div className={`network-rank-card ${r.id==='player'?'player':''}`} key={r.id}><span>#{i+1} · {r.scope}</span><h3>{r.name}</h3><p>{r.identity||'Your network'}</p><div><b>Prestige {Math.round(r.prestige||0)}</b><b>Revenue {money(r.revenue||0)}</b></div></div>)}</div></Card></div>
}

function ProgramRankings({state,onOpen,onOpenRival}){
  const [scope,setScope]=useState('local'),[format,setFormat]=useState('all'),[band,setBand]=useState('all'),[sort,setSort]=useState('audience');let rows=currentProgramRankings(state,{scope,format,band});rows=[...rows].sort((a,b)=>(b[sort]||0)-(a[sort]||0));
  return <div className="page-stack"><div className="filter-bar"><label>Market<select value={scope} onChange={e=>setScope(e.target.value)}><option value="local">Local</option><option value="state">State</option><option value="national">National</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="all">All formats</option>{FORMAT_EXPERTISE.map(x=><option key={x}>{x}</option>)}</select></label><label>Slot<select value={band} onChange={e=>setBand(e.target.value)}><option value="all">All slots</option>{Object.entries(BAND_LABELS).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="audience">Average Audience</option><option value="totalAudience">Total Audience</option><option value="viewer">Viewer Score</option><option value="critic">Critic Score</option></select></label></div><Card className="pad"><SectionTitle title="Current Year Programs" sub="Every tracked network competes inside the same slot and format rankings."/>{rows.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>Program</th><th>Network</th><th>Format</th><th>Slot</th><th>Total Audience</th><th>Avg Audience</th><th>Viewer</th><th>Critic</th></tr></thead><tbody>{rows.map((r,i)=>{const own=state.programs.find(p=>p.title===r.title&&r.network===state.network.initials);return <tr key={`${r.network}-${r.title}`} className={`click-row ${own?'player-row':''}`} onClick={()=>own?onOpen(own.id):onOpenRival(r)}><td>{i+1}</td><td><b>{r.title}</b><small>{r.genre}</small></td><td>{r.network}</td><td>{r.format}</td><td>{BAND_LABELS[r.band]||r.band}</td><td>{num(r.totalAudience||0)}</td><td>{num(r.audience)}</td><td>{Number(r.viewer||0).toFixed(1)}</td><td>{Math.round(r.critic||0)}%</td></tr>})}</tbody></table></div>:<Empty>No programs have aired yet.</Empty>}</Card></div>
}

function Records({state}){const [format,setFormat]=useState('all'),[metric,setMetric]=useState('audience');const rows=historicalRecords(state,{format,metric});return <div className="page-stack"><div className="filter-bar"><label>Category<select value={format} onChange={e=>setFormat(e.target.value)}><option value="all">All programming</option>{FORMAT_EXPERTISE.map(x=><option key={x}>{x}</option>)}</select></label><label>Record<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="audience">Audience</option><option value="viewer">Viewer Score</option><option value="critic">Critic Score</option></select></label></div><Card className="pad"><SectionTitle title="All-Time Top 10" sub="Current-year leaders are provisional. December 31 archives them into permanent history."/>{rows.length?<div className="record-list">{rows.map((r,i)=><div className="record-row" key={`${r.year}-${r.network}-${r.title}`}><strong>{i+1}</strong><div><b>{r.title}</b><span>{r.network} · {r.format} · {r.year}</span></div><em>{metric==='audience'?num(r.audience):metric==='viewer'?Number(r.viewer).toFixed(1):`${Math.round(r.critic)}%`}</em></div>)}</div>:<Empty>No records yet. The record book grows as television airs.</Empty>}</Card></div>}

function Awards({state}){
  const scope=networkAwardScope(state),history=[...(state.awardHistory||[])].reverse(),year=state.date.slice(0,4);
  const ceremonies=[['Local','Nov 15','Local stations only','Best Program · Actor · Actress · Director · Host · Showrunner'],['State','Dec 1','Local + state networks','Best Program · Actor · Actress · Director · Host · Showrunner'],['National','Dec 20','Every network','Format winners · Technical · Ambience · Most Watched · Viewer/Critic · Talent & Creatives']];
  return <div className="page-stack awards-hall"><div className="awards-hero"><div><span className="eyebrow">AWARDS SEASON · {year}</span><h1>Television Honors</h1><p>Your current eligibility level is <b>{scope}</b>. Awards grow with the reach of the network, but national competition is always open to every broadcaster.</p></div><div className="award-statue">✦</div></div><div className="award-tier-grid">{ceremonies.map(([name,date,elig,cats])=><Card className={`pad award-tier tier-${name.toLowerCase()}`} key={name}><span className="eyebrow">{date}</span><h2>{name} Awards</h2><p>{elig}</p><small>{cats}</small>{(name==='National'||name==='State'&&['Local','State'].includes(scope)||name==='Local'&&scope==='Local')?<Pill tone="ok">Eligible</Pill>:<Pill>Not eligible at this scope</Pill>}</Card>)}</div><Card className="pad"><SectionTitle title="Awards History" sub="Ceremonies run automatically each year. Player winners increase program and network prestige."/>{history.length?<div className="award-history">{history.slice(0,80).map((a,i)=><div className={a.playerWon?'player-winner':''} key={`${a.year}-${a.scope}-${a.category}-${i}`}><span>{a.year} · {a.scope}</span><b>{a.category}</b><strong>{a.winner}</strong><small>{a.programTitle} · {a.network}</small></div>)}</div>:<Empty>No trophies yet. Local awards begin November 15, state awards December 1, and nationals December 20.</Empty>}</Card></div>;
}

function Brand({state}){return <div className="dashboard-grid"><Card className="pad"><SectionTitle title="Format Expertise" sub="You started with two stars in one format; experience grows by making television."/>{FORMAT_EXPERTISE.map(f=><div className="expertise-row" key={f}><div><b>{f}</b><small>{'★'.repeat(Math.floor((state.network.expertise[f]||0)/2))}{'☆'.repeat(5-Math.floor((state.network.expertise[f]||0)/2))}</small></div><strong>{(state.network.expertise[f]||0).toFixed(1)} / 10</strong></div>)}</Card><Card className="pad"><SectionTitle title="Network Brand"/><StatBar label="Prestige" value={state.network.prestige}/><StatBar label="Trust" value={state.network.trust}/><StatBar label="Sports" value={state.network.sports}/><StatBar label="Youth" value={state.network.youth}/><StatBar label="Family" value={state.network.family}/><StatBar label="Innovation" value={state.network.innovation}/></Card></div>}
