import React, { useEffect, useState } from 'react';
import { Card, Drawer, Metric, ProgramPoster, Score, SectionTitle } from '../components/UI.jsx';
import { alerts, breakNegotiation, markAllMailRead, markMailRead, networkReachHouseholds, signNegotiation } from '../game/simulation.js';
import { fmtDate, money, num } from '../game/utils.js';

export default function Dashboard({state,setState,onNavigate,onOpenProgram}){
  const [selected,setSelected]=useState(state.emails?.[0]?.id||null),[reveal,setReveal]=useState(null);
  const mails=state.emails||[],mail=mails.find(x=>x.id===selected)||mails[0],a=alerts(state),unread=mails.filter(x=>!x.read).length;
  const open=id=>{setSelected(id);setState(markMailRead(state,id));};
  const neg=mail?.negotiationId&&state.negotiations.find(n=>n.id===mail.negotiationId);
  return <div className="page-stack">
    <div className="hero-panel inbox-hero"><div><span className="eyebrow">EXECUTIVE INBOX · {fmtDate(state.date)}</span><h1>{state.network.initials} Network Office</h1><p>Processes finish here. Advance time, read the mail, make the next decision.</p></div><div className="hero-mail-count"><b>{unread}</b><span>unread</span></div></div>
    <div className="metric-grid"><Metric label="Cash" value={money(state.cash)} sub="working capital" tone={state.cash<3000000?'danger':''}/><Metric label="Technical Reach" value={num(networkReachHouseholds(state))} sub="households with access"/><Metric label="Owned Programs" value={state.programs.length} sub={`${state.developments.filter(d=>(d.scriptedEpisodes||0)>0&&!d.greenlit).length} script packages available`}/><Metric label="Staff" value={state.employees.length} sub={`${state.staffSearches.filter(x=>x.status==='Searching').length} searches active`}/><Metric label="Production" value={state.programs.filter(p=>p.status==='Production').length} sub={`${state.stageProjects?.length||0} stages under construction`}/><Metric label="Unread Mail" value={unread} sub={`${a.length} active alerts`} tone={unread?'warn':''}/></div>
    <div className="inbox-layout"><Card className="inbox-list-card"><div className="inbox-toolbar"><div><b>Inbox</b><span>{mails.length} messages</span></div><button disabled={!unread} onClick={()=>setState(markAllMailRead(state))}>Mark all read</button></div><div className="mail-list">{mails.map(m=><button key={m.id} className={`mail-row ${!m.read?'unread':''} ${mail?.id===m.id?'active':''}`} onClick={()=>open(m.id)}><i className={`mail-type ${m.category||'info'}`}/><div><b>{m.from}</b><strong>{m.subject}</strong><span>{m.body.split('\n')[0]}</span></div><time>{m.date.slice(5)}</time></button>)}</div></Card>
      <Card className="mail-reader">{mail?<><div className="mail-reader-head"><span className="eyebrow">{mail.category||'MESSAGE'} · {mail.date}</span><h2>{mail.subject}</h2><p>From: <b>{mail.from}</b></p></div>{mail.reportRows?<RatingsReport rows={mail.reportRows}/>:<div className="mail-body">{mail.body.split('\n').map((line,i)=><p key={i}>{line||' '}</p>)}</div>}<div className="mail-actions">{mail.premiereReveal&&mail.programId&&<button className="primary big premiere-check" onClick={()=>setReveal(mail.programId)}>Check Premiere Results</button>}{mail.developmentId&&!mail.premiereReveal&&<button className="primary" onClick={()=>onNavigate('studio')}>Open Studio</button>}{mail.programId&&!mail.premiereReveal&&<button className="primary" onClick={()=>onOpenProgram?.(mail.programId)}>Open Program</button>}{mail.searchId&&<button className="primary" onClick={()=>onNavigate('organization')}>Open Hiring</button>}{mail.negotiationId&&neg?.status==='Agreed'&&<><button className="primary big" onClick={()=>setState(signNegotiation(state,mail.negotiationId))}>Sign Person</button><button className="danger-btn big" onClick={()=>setState(breakNegotiation(state,mail.negotiationId))}>Break Negotiations</button></>}{mail.negotiationId&&neg?.status==='Countered'&&<button className="primary big" onClick={()=>onNavigate('organization')}>Review Counteroffer</button>}{mail.negotiationId&&neg?.status==='Signed'&&<span className="mail-action-status">✓ Contract signed</span>}{mail.negotiationId&&neg?.status==='Broken'&&<span className="mail-action-status">Negotiations ended</span>}</div></>:<div className="empty">No messages yet.</div>}</Card></div>
    <div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Process Monitor" sub="Processes remain visible after completion in their dedicated department."/><div className="process-board">{state.developments.filter(d=>['Writing','Rewrite','Refining'].includes(d.status)).map(d=><Process key={d.id} label={`${d.status} · ${d.title}`} days={d.daysRemaining} total={d.totalDays} detail={d.status==='Writing'?`${d.scriptedEpisodes||0}/${d.episodes} scripts ready`:''}/>)}{state.staffSearches.filter(x=>x.status==='Searching').map(x=><Process key={x.id} label={`${x.role} search`} days={x.daysRemaining} total={x.totalDays}/>)}{state.negotiations.filter(x=>x.status==='Negotiating').map(x=><Process key={x.id} label={`Negotiation · ${state.candidateMarket.find(c=>c.id===x.candidateId)?.name||'Candidate'}`} days={x.daysRemaining} total={x.totalDays}/>)}{[...(state.facilityProjects||[]),...(state.stageProjects||[])].map(x=><Process key={x.id} label={`Construction · ${x.name}`} days={x.daysRemaining} total={x.totalDays}/>)}{state.programs.filter(p=>p.status==='Production').map(p=><div className="process-line" key={p.id}><div><b>Production · {p.title}</b><span>{Math.floor(p.pipeline.ready)} ready · {Math.floor(p.pipeline.scripted)} scripts delivered</span></div><div className="progress-mini"><i style={{width:`${p.pipeline.ready/p.episodes*100}%`}}/></div></div>)}</div></Card><Card className="pad"><SectionTitle title="Alerts"/><div className="alert-list">{a.map((x,i)=><div className="alert-row" key={i}><i className={`dot ${x.sev}`}/><div><b>{x.title}</b><span>{x.sub}</span></div></div>)}</div></Card><Card className="pad span-3"><SectionTitle title="Opening Playbook" sub={state.network.launchDate?`Launch date: ${state.network.launchDate}`:'Choose a launch date only when you have a credible plan.'}/><div className="opening-steps"><button onClick={()=>onNavigate('business')}><b>1</b><span><strong>Acquire filler</strong>License movies while original content is being built.</span></button><button onClick={()=>onNavigate('organization')}><b>2</b><span><strong>Build the company</strong>Hire writers and construct appropriate stages.</span></button><button onClick={()=>onNavigate('studio')}><b>3</b><span><strong>Develop scripts</strong>React to scripts as they arrive; greenlight early or wait.</span></button><button onClick={()=>onNavigate('channel')}><b>4</b><span><strong>Commit launch</strong>Select the initial air date, then build the grid around it.</span></button></div></Card></div>
    <PremiereReveal state={state} programId={reveal} onClose={()=>setReveal(null)} onOpenProgram={onOpenProgram}/>
  </div>
}
function RatingsReport({rows}){return <div className="mail-report"><p>Daily audience results for everything your network aired:</p><div className="table-wrap"><table><thead><tr><th>Program</th><th>Time</th><th>Audience</th><th>Share</th><th>Slot Rank</th><th>Viewer</th><th>Critic</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.title}-${i}`}><td><b>{r.title}</b>{r.premiere&&<small> PREMIERE</small>}</td><td>{r.start}</td><td>{num(r.audience)}</td><td>{(r.share*100).toFixed(1)}%</td><td>#{r.rank}</td><td>{Number(r.viewer).toFixed(1)}</td><td>{Math.round(r.critic)}%</td></tr>)}</tbody></table></div></div>}
function PremiereReveal({state,programId,onClose,onOpenProgram}){const [stage,setStage]=useState(0),p=state.programs.find(x=>x.id===programId);useEffect(()=>{if(!programId)return;setStage(0);const a=setTimeout(()=>setStage(1),450),b=setTimeout(()=>setStage(2),1000);return()=>{clearTimeout(a);clearTimeout(b)}},[programId]);if(!p)return null;const h=p.episodeHistory?.[p.episodeHistory.length-1];return <Drawer open wide title={`${p.title} · Premiere Night`} onClose={onClose}><div className="premiere-reveal"><ProgramPoster p={p}/><span className="eyebrow">THE FIRST NUMBERS ARE IN</span><h1>{stage<1?'Audience Research is processing…':stage<2?'Reception scores incoming…':`${p.title} has entered the race.`}</h1>{stage>=1&&<div className="premiere-audience-grid"><div><span>Audience</span><strong>{num(h?.audience||p.lastAudience)}</strong></div><div><span>Local Share</span><strong>{((h?.shareLocal||0)*100).toFixed(1)}%</strong></div><div><span>Slot Position</span><strong>#{h?.rankLocal||'—'}</strong></div></div>}{stage>=2&&<div className="premiere-score-reveal"><Score label="Viewer" value={p.viewer/10}/><Score label="Critics" value={p.critic}/></div>}<div className="button-row"><button onClick={onClose}>Close</button>{stage>=2&&<button className="primary" onClick={()=>{onClose();onOpenProgram?.(p.id)}}>Open Program</button>}</div></div></Drawer>}
function Process({label,days,total,detail}){const done=Math.max(0,100-days/Math.max(1,total)*100);return <div className="process-line"><div><b>{label}</b><span>{detail||`${days} day${days===1?'':'s'} remaining`}</span></div><div className="progress-mini"><i style={{width:`${done}%`}}/></div></div>}
