import React, { useState } from 'react';
import { Card, Empty, Pill, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { expandState, fireEmployee, networkReachHouseholds, setAutomation, signAffiliate, startFacilityBuild, startNegotiation, startResearch, startStaffSearch, updateNetwork, updateNewsroom } from '../game/simulation.js';
import { money, num, pct } from '../game/utils.js';

const ROLE_GROUPS={
  Creative:['Writer','Showrunner','Director'],Talent:['Actor','Host','Anchor','Sports Host'],Production:['VFX Supervisor'],Commercial:['Ad Sales Executive','Licensing Executive','Marketing Director','Distribution VP'],Technology:['Broadcast Engineer','Chief Engineer'],News:['News Producer'],Executive:['Head of Content','Head of Programming','Head of Ad Sales']
};

export default function Organization({state,setState}){
  const [tab,setTab]=useState('people');
  return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">QUADRANT IV</span><h1>Organization</h1><p>Every hire and facility begins as a process, not an instant purchase.</p></div></div><Tabs value={tab} onChange={setTab} items={[["people","People"],["facilities","Facilities"],["research","Research"],["distribution","Distribution"],["news","Newsroom"],["network","Network"]]}/>{tab==='people'&&<People state={state} setState={setState}/>} {tab==='facilities'&&<Facilities state={state} setState={setState}/>} {tab==='research'&&<Research state={state} setState={setState}/>} {tab==='distribution'&&<Distribution state={state} setState={setState}/>} {tab==='news'&&<Newsroom state={state} setState={setState}/>} {tab==='network'&&<NetworkSettings state={state} setState={setState}/>}</div>
}

function People({state,setState}){
  const [role,setRole]=useState('Writer'),[offers,setOffers]=useState({});
  const activeSearches=state.staffSearches.filter(x=>x.status==='Searching'),shortlists=[...state.candidateShortlists].reverse(),activeNegs=state.negotiations.filter(x=>x.status==='Negotiating');
  const updateOffer=(id,k,v)=>{const c=state.candidateMarket.find(x=>x.id===id);setOffers(o=>({...o,[id]:{salary:o[id]?.salary??c?.ask??0,years:o[id]?.years??3,bonus:o[id]?.bonus??0,backend:o[id]?.backend??0,creativeControl:o[id]?.creativeControl??40,[k]:Number(v)}}))};
  return <div className="page-stack"><div className="dashboard-grid"><Card className="pad span-2"><SectionTitle title="Current Staff" sub={`${state.employees.length} contracted key personnel.`}/>{state.employees.length?<div className="candidate-grid">{state.employees.map(e=><Card className="candidate-card" key={e.id}><span className="eyebrow">{e.dept}</span><h3>{e.name}</h3><p>{e.role} · Overall {e.overall}</p><div className="mini-stats"><span>Salary <b>{money(e.salary)}</b></span><span>Morale <b>{Math.round(e.morale)}</b></span><span>Term <b>{e.contractYears}y</b></span></div><div className="chips">{Object.entries(e.skills).slice(0,4).map(([k,v])=><Pill key={k}>{k} {v}</Pill>)}</div><button className="danger-btn" onClick={()=>setState(fireEmployee(state,e.id))}>Release</button></Card>)}</div>:<Empty>No staff. Your company really does begin as a license and an empty office.</Empty>}</Card><Card className="pad"><SectionTitle title="Create a Position" sub="First define who you need. Recruiting then takes several days."/><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(ROLE_GROUPS).map(([g,rs])=><optgroup label={g} key={g}>{rs.map(r=><option key={r}>{r}</option>)}</optgroup>)}</select></label><button className="primary big full" onClick={()=>setState(startStaffSearch(state,role))}>Open {role} Search</button><p className="muted-copy">Search fee covers recruiters/agents. Candidate quality is not guaranteed until the shortlist arrives.</p></Card></div>
    <Card className="pad"><SectionTitle title="Open Processes" sub="Searches and negotiations advance with the calendar."/><div className="process-board">{activeSearches.map(x=><Process key={x.id} label={`Searching · ${x.role}`} days={x.daysRemaining} total={x.totalDays}/>)}{activeNegs.map(n=><Process key={n.id} label={`Negotiating · ${state.candidateMarket.find(c=>c.id===n.candidateId)?.name||'Candidate'}`} days={n.daysRemaining} total={n.totalDays}/>)}{!activeSearches.length&&!activeNegs.length&&<Empty>No active HR processes.</Empty>}</div></Card>
    <Card className="pad"><SectionTitle title="Candidate Shortlists" sub="Only candidates found through completed searches are visible here."/>{shortlists.length?<div className="shortlist-stack">{shortlists.map(sl=><div className="shortlist-section" key={sl.id}><div className="section-title"><div><span className="eyebrow">SEARCH COMPLETE · {sl.date}</span><h3>{sl.role}</h3></div></div><div className="candidate-grid">{sl.candidateIds.map(id=>{const c=state.candidateMarket.find(x=>x.id===id);if(!c)return null;const o=offers[id]||{salary:c.ask,years:3,bonus:0,backend:0,creativeControl:40},neg=state.negotiations.find(n=>n.candidateId===id&&n.status==='Negotiating');return <Card className="candidate-card hire-candidate" key={id}><div><h3>{c.name}</h3><span>{c.role} · OVR {c.overall}</span><small>Agent ask {money(c.ask)}</small></div><div className="chips">{Object.entries(c.skills).slice(0,4).map(([k,v])=><Pill key={k}>{k} {v}</Pill>)}</div><label>Salary<input type="number" step="10000" value={o.salary} onChange={e=>updateOffer(id,'salary',e.target.value)}/></label><label>Years<input type="number" min="1" max="5" value={o.years} onChange={e=>updateOffer(id,'years',e.target.value)}/></label><label>Signing bonus<input type="number" step="10000" value={o.bonus} onChange={e=>updateOffer(id,'bonus',e.target.value)}/></label><label>Backend %<input type="number" min="0" max="10" step="0.5" value={o.backend} onChange={e=>updateOffer(id,'backend',e.target.value)}/></label><label>Creative control<input type="number" min="0" max="100" step="10" value={o.creativeControl} onChange={e=>updateOffer(id,'creativeControl',e.target.value)}/></label><button className="primary" disabled={!!neg} onClick={()=>setState(startNegotiation(state,id,o.salary,o.years,o.bonus,o.backend,o.creativeControl))}>{neg?'Negotiating…':'Submit Offer'}</button></Card>})}</div></div>)}</div>:<Empty>No completed searches yet.</Empty>}</Card>
  </div>
}
function Process({label,days,total}){return <div className="process-line"><div><b>{label}</b><span>{days} days remaining</span></div><div className="progress-mini"><i style={{width:`${Math.max(0,100-days/Math.max(1,total)*100)}%`}}/></div></div>}

function Facilities({state,setState}){
  const defs={studios:['Soundstage',1800000,60,'Required to begin original production'],post:['Post Suite',900000,40,'Speeds editing and broadcast delivery'],newsroom:['Newsroom Facility',1200000,45,'Permanent local news operation'],vfx:['VFX Facility',2400000,75,'High-end effects capability'],wardrobe:['Wardrobe',500000,28,'Costume-heavy production support'],setShop:['Set Construction',800000,35,'Physical production-design capacity'],control:['Broadcast Control',1000000,0,'Basic control is included with your local license'],archive:['Archive',420000,24,'Library preservation and reuse'],research:['Research Lab',750000,42,'Technology development speed']};
  return <div className="page-stack">{state.facilityProjects.length>0&&<Card className="pad"><SectionTitle title="Construction Calendar"/>{state.facilityProjects.map(x=><Process key={x.id} label={x.name} days={x.daysRemaining} total={x.totalDays}/>)}</Card>}<div className="facility-grid">{Object.entries(defs).map(([k,[name,base,days,desc]])=>{const lvl=state.facilities[k]||0,cost=base*(lvl+1),project=state.facilityProjects.find(x=>x.key===k);return <Card className="pad" key={k}><span className="eyebrow">LEVEL {lvl}</span><h2>{name}</h2><p>{desc}</p><div className="facility-level">{Array.from({length:5}).map((_,i)=><i className={i<lvl?'on':''} key={i}/>)}</div>{k==='control'?<Pill tone="ok">Operational</Pill>:project?<><Pill>{project.daysRemaining} days remaining</Pill><button disabled>Under construction</button></>:<button disabled={state.cash<cost*.25} onClick={()=>setState(startFacilityBuild(state,k))}>Build L{lvl+1} · {days}d · {money(cost)}</button>}</Card>})}</div></div>
}

function Research({state,setState}){const active=state.research&&state.tech.find(t=>t.id===state.research.techId);return <div className="dashboard-grid"><Card className="pad"><SectionTitle title="R&D Department" sub="Capabilities develop over time. Engineers and research facilities accelerate the work."/>{active?<><h3>{active.name}</h3><StatBar label="Progress" value={active.progress}/><p>{active.desc}</p></>:<Empty>No active project.</Empty>}</Card><Card className="pad span-2"><SectionTitle title="Technology Roadmap"/><div className="candidate-grid">{state.tech.map(t=><Card className="candidate-card" key={t.id}><span className="eyebrow">{t.group} · Tier {t.tier}</span><h3>{t.name}</h3><p>{t.desc}</p>{t.researched?<Pill tone="ok">Operational</Pill>:<><StatBar label="Progress" value={t.progress}/><button className="primary" disabled={!!state.research} onClick={()=>setState(startResearch(state,t.id))}>Start Research · {money(t.cost)}</button></>}</Card>)}</div></Card></div>}

function Distribution({state,setState}){const reach=networkReachHouseholds(state);return <div className="page-stack"><div className="metric-grid"><div className="metric"><span>Technical Reach</span><strong>{num(reach)}</strong><small>households</small></div><div className="metric"><span>Covered States</span><strong>{state.states.filter(x=>x.coverage>.05).length}</strong></div><div className="metric"><span>Active Affiliates</span><strong>{state.affiliates.filter(x=>x.status==='Active').length}</strong></div></div><Card className="pad"><SectionTitle title="U.S. Broadcast Footprint" sub="You begin with local emission rights in one state. Coverage does not create viewers by itself."/><div className="us-map">{state.states.map(st=><button title={`${st.code}: ${pct(st.coverage*100)} coverage`} onClick={()=>setState(expandState(state,st.code))} key={st.code} style={{gridColumn:st.col,gridRow:st.row,'--cov':st.coverage}} className={st.coverage>.7?'high':st.coverage>.15?'mid':''}><b>{st.code}</b><span>{Math.round(st.coverage*100)}%</span></button>)}</div></Card><Card className="pad"><SectionTitle title="Affiliate Market"/><div className="candidate-grid">{state.affiliates.map(af=><Card className="candidate-card" key={af.id}><span className="eyebrow">{af.market}</span><h3>{af.station}</h3><p>{num(af.households)} households · {af.term} years</p><StatBar label="Station quality" value={af.quality}/>{af.status==='Active'?<Pill tone="ok">Affiliate</Pill>:<button onClick={()=>setState(signAffiliate(state,af.id))}>Sign · {money(af.ask)}/yr</button>}</Card>)}</div></Card></div>}

function Newsroom({state,setState}){const n=state.newsroom,controls=[['reporters','Reporters'],['bureaus','Bureaus'],['weather','Weather Unit'],['sportsDesk','Sports Desk'],['investigative','Investigative Team']];return <div className="split-layout"><Card className="pad"><SectionTitle title="News Operation" sub="You start with none. Build a newsroom and hire news staff before trying to become a trusted local news brand."/><div className="newsroom-score"><b>{Math.round(n.trust)}</b><span>Trust</span></div>{state.facilities.newsroom<1&&<div className="warning-box">No newsroom facility. Build one in Facilities.</div>}</Card><Card className="pad"><SectionTitle title="Permanent Capacity"/>{controls.map(([k,l])=><div className="capacity-row" key={k}><div><b>{l}</b><span>{n[k]}</span></div><div><button disabled={n[k]<=0} onClick={()=>setState(updateNewsroom(state,k,-1))}>−</button><button disabled={state.facilities.newsroom<1} onClick={()=>setState(updateNewsroom(state,k,1))}>+</button></div></div>)}</Card></div>}

function NetworkSettings({state,setState}){const [f,setF]=useState({...state.network}),set=(k,v)=>setF(x=>({...x,[k]:v}));return <div className="split-layout"><Card className="pad"><SectionTitle title="Network Identity"/><div className="form-grid"><label className="full">Network name<input value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>Initials<input value={f.initials} maxLength="5" onChange={e=>set('initials',e.target.value.toUpperCase())}/></label><label>Icon<select value={f.icon} onChange={e=>set('icon',e.target.value)}>{['★','●','◆','▲','✦','☀','⚡','♣','♥','⬟','◉','🐦','📺'].map(x=><option key={x}>{x}</option>)}</select></label><label>Shape<select value={f.shape||'circle'} onChange={e=>set('shape',e.target.value)}><option value="circle">Circle</option><option value="square">Square</option><option value="diamond">Diamond</option><option value="shield">Shield</option></select></label><label>Shape color<input type="color" value={f.primary} onChange={e=>set('primary',e.target.value)}/></label><label>Icon color<input type="color" value={f.secondary} onChange={e=>set('secondary',e.target.value)}/></label><button className="primary full" onClick={()=>setState(updateNetwork(state,{name:f.name,initials:f.initials,icon:f.icon,shape:f.shape,primary:f.primary,secondary:f.secondary}))}>Apply Rebrand</button></div></Card><Card className="pad"><SectionTitle title="Live Preview"/><div className={`brand-seal-large shape-${f.shape||'circle'}`} style={{'--primary':f.primary,'--secondary':f.secondary}}><i>{f.icon}</i><b>{f.initials}</b><span>{f.name}</span></div></Card></div>}
