import React, { useMemo, useState } from 'react';
import { Card, Drawer, Empty, Pill, SectionTitle, StatBar, Tabs } from '../components/UI.jsx';
import { PersonProfile } from '../components/Profiles.jsx';
import { FORMAT_EXPERTISE } from '../game/constants.js';
import { breakNegotiation, fireEmployee, networkReachHouseholds, signNegotiation, startAntennaBuild, startEmissionRights, startFacilityBuild, startNegotiation, startResearch, startStaffSearch, updateNetwork, updateNewsroom } from '../game/simulation.js';
import { money, num, pct } from '../game/utils.js';

const roleGroups={
  Executive:['Head of Content','Head of Programming','Chief Innovation Officer'],
  Creative:['Writer','Showrunner','Director','Contest Producer','Documentary Producer','Sports Producer'],
  Talent:['Actor','Host','Anchor','Sports Host'],
  Production:['VFX Supervisor'],Technology:['Broadcast Engineer','Chief Engineer'],Commercial:['Ad Sales Executive','Head of Ad Sales','Licensing Executive','Marketing Director','Distribution VP'],News:['News Producer']
};

export default function Organization({state,setState}){
  const [tab,setTab]=useState('people');
  return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">QUADRANT IV</span><h1>Organization</h1><p>Build the people, facilities, technology and broadcast footprint that make the network possible.</p></div></div><Tabs value={tab} onChange={setTab} items={[["people","People"],["facilities","Facilities"],["research","Research"],["distribution","Distribution"],["newsroom","Newsroom"],["network","Network"]]}/>{tab==='people'&&<People state={state} setState={setState}/>} {tab==='facilities'&&<Facilities state={state} setState={setState}/>} {tab==='research'&&<Research state={state} setState={setState}/>} {tab==='distribution'&&<Distribution state={state} setState={setState}/>} {tab==='newsroom'&&<Newsroom state={state} setState={setState}/>} {tab==='network'&&<NetworkSettings state={state} setState={setState}/>}</div>
}

function People({state,setState}){
  const [role,setRole]=useState('Writer'),[offerCandidate,setOfferCandidate]=useState(null),[personId,setPersonId]=useState(null);const person=state.employees.find(e=>e.id===personId),candidate=state.candidateMarket.find(c=>c.id===offerCandidate);const [offer,setOffer]=useState(null);
  const activeSearches=state.staffSearches.filter(x=>x.status==='Searching'),activeNegs=state.negotiations.filter(x=>x.status==='Negotiating'),shortlists=state.candidateShortlists;
  const openNegotiation=c=>{setOfferCandidate(c.id);setOffer({salary:c.ask,years:c.demands?.years||3,bonus:c.demands?.bonus||0,backend:c.demands?.backend||0,creativeControl:c.demands?.creativeControl||0})};
  return <div className="page-stack"><div className="split-layout"><Card className="pad"><SectionTitle title="Create a Position" sub="Open a search, wait for recruiters, then negotiate with the shortlist."/><label className="large-select">Role<select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(roleGroups).map(([g,rs])=><optgroup label={g} key={g}>{rs.map(r=><option key={r}>{r}</option>)}</optgroup>)}</select></label><button className="primary big full" onClick={()=>setState(startStaffSearch(state,role))}>Open {role} Search</button></Card><Card className="pad"><SectionTitle title="HR Processes" sub="Searches and offers take calendar time."/><div className="process-board">{activeSearches.map(x=><Process key={x.id} label={`Searching · ${x.role}`} days={x.daysRemaining} total={x.totalDays}/>)}{activeNegs.map(n=><Process key={n.id} label={`Negotiating · ${state.candidateMarket.find(c=>c.id===n.candidateId)?.name||'Candidate'}`} days={n.daysRemaining} total={n.totalDays}/>)}{!activeSearches.length&&!activeNegs.length&&<Empty>No active HR processes.</Empty>}</div></Card></div>
    <Card className="pad"><SectionTitle title="Your Staff" sub="Open a person to see specialties, project history and contract details."/>{state.employees.length?<div className="staff-list">{state.employees.map(e=><button className="staff-row" key={e.id} onClick={()=>setPersonId(e.id)}><div className="person-avatar small">{e.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><b>{e.name}</b><span>{e.role} · OVR {e.overall}</span></div><strong>{money(e.salary)}/yr</strong></button>)}</div>:<Empty>No staff. Every department must be built deliberately.</Empty>}</Card>
    <Card className="pad"><SectionTitle title="Candidate Shortlists" sub="Initial demands are visible first. Negotiate opens a larger contract screen."/>{shortlists.length?<div className="candidate-grid big-candidate-grid">{shortlists.flatMap(sl=>sl.candidateIds.map(id=>state.candidateMarket.find(x=>x.id===id)).filter(Boolean)).filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i).map(c=>{const neg=state.negotiations.find(n=>n.candidateId===c.id&&['Negotiating','Agreed'].includes(n.status));return <Card className="candidate-card candidate-summary" key={c.id}><div className="candidate-head"><div><span className="eyebrow">{c.role}</span><h2>{c.name}</h2><p>Overall {c.overall}</p></div><div className="demand-box"><span>Initial demand</span><b>{money(c.ask)}/yr</b><small>Market avg {money(c.marketAverage)}</small></div></div><div className="chips">{Object.entries(c.skills).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=><Pill key={k}>{k} {v}</Pill>)}</div>{neg?.status==='Agreed'?<Pill tone="ok">Terms agreed — sign from Inbox</Pill>:<button className="primary big" disabled={neg?.status==='Negotiating'} onClick={()=>openNegotiation(c)}>{neg?.status==='Negotiating'?'Negotiating…':'Negotiate Contract'}</button>}</Card>})}</div>:<Empty>No completed searches yet.</Empty>}</Card>
    <Drawer open={!!candidate} title={candidate?`Negotiate · ${candidate.name}`:''} onClose={()=>setOfferCandidate(null)} wide>{candidate&&offer&&<div className="negotiation-screen"><div className="negotiation-summary"><div><span className="eyebrow">CANDIDATE DEMANDS</span><h2>{candidate.name}</h2><p>{candidate.role} · OVR {candidate.overall}</p></div><div className="demand-comparison"><div><span>Agent salary ask</span><b>{money(candidate.ask)}</b></div><div><span>Market average</span><b>{money(candidate.marketAverage)}</b></div><div><span>Requested term</span><b>{candidate.demands?.years||3} years</b></div></div></div><div className="contract-form"><SectionTitle title="Your Offer" sub="Set the terms you want. Their representatives respond after several simulated days."/><label>Annual salary<input type="number" step="10000" value={offer.salary} onChange={e=>setOffer({...offer,salary:Number(e.target.value)})}/></label><label>Contract years<input type="number" min="1" max="5" value={offer.years} onChange={e=>setOffer({...offer,years:Number(e.target.value)})}/></label><label>Signing bonus<input type="number" step="10000" value={offer.bonus} onChange={e=>setOffer({...offer,bonus:Number(e.target.value)})}/></label><label>Backend %<input type="number" min="0" max="10" step="0.5" value={offer.backend} onChange={e=>setOffer({...offer,backend:Number(e.target.value)})}/></label><label>Creative control %<input type="number" min="0" max="100" step="10" value={offer.creativeControl} onChange={e=>setOffer({...offer,creativeControl:Number(e.target.value)})}/></label><button className="primary big full" onClick={()=>{setState(startNegotiation(state,candidate.id,offer.salary,offer.years,offer.bonus,offer.backend,offer.creativeControl));setOfferCandidate(null)}}>Submit Negotiated Offer</button></div></div>}</Drawer>
    <PersonProfile state={state} person={person} onClose={()=>setPersonId(null)}/>
  </div>
}
function Process({label,days,total}){return <div className="process-line"><div><b>{label}</b><span>{days} days remaining</span></div><div className="progress-mini"><i style={{width:`${Math.max(0,100-days/Math.max(1,total)*100)}%`}}/></div></div>}

function Facilities({state,setState}){const defs={studios:['Soundstage',1800000,60,'Required to begin original production'],post:['Post Suite',900000,40,'Speeds editing and delivery'],newsroom:['Newsroom Facility',1200000,45,'Permanent news operation'],vfx:['VFX Facility',2400000,75,'High-end effects capability'],wardrobe:['Wardrobe',500000,28,'Costume-heavy production support'],setShop:['Set Construction',800000,35,'Physical production design'],control:['Broadcast Control',1000000,0,'Basic control included'],archive:['Archive',420000,24,'Library preservation'],research:['Research Lab',750000,42,'Research speed']};return <div className="page-stack">{state.facilityProjects.length>0&&<Card className="pad"><SectionTitle title="Construction Calendar"/>{state.facilityProjects.map(x=><Process key={x.id} label={x.name} days={x.daysRemaining} total={x.totalDays}/>)}</Card>}<div className="facility-grid">{Object.entries(defs).map(([k,[name,base,days,desc]])=>{const lvl=state.facilities[k]||0,cost=base*(lvl+1),project=state.facilityProjects.find(x=>x.key===k);return <Card className="pad" key={k}><span className="eyebrow">LEVEL {lvl}</span><h2>{name}</h2><p>{desc}</p><div className="facility-level">{Array.from({length:5}).map((_,i)=><i className={i<lvl?'on':''} key={i}/>)}</div>{k==='control'?<Pill tone="ok">Operational</Pill>:project?<Pill>{project.daysRemaining} days remaining</Pill>:<button disabled={state.cash<cost*.25} onClick={()=>setState(startFacilityBuild(state,k))}>Build L{lvl+1} · {days}d · {money(cost)}</button>}</Card>})}</div></div>}

function Research({state,setState}){const active=state.research&&state.tech.find(t=>t.id===state.research.techId),cio=state.employees.find(e=>e.role==='Chief Innovation Officer');return <div className="dashboard-grid"><Card className="pad"><SectionTitle title="Innovation Office" sub="Research cannot begin until a Chief Innovation Officer is under contract."/>{cio?<div className="contract-banner"><div><span className="eyebrow">CIO</span><h2>{cio.name}</h2><p>Innovation {cio.skills.innovation||cio.overall} · Research {cio.skills.research||cio.overall}</p></div></div>:<div className="warning-box">No Chief Innovation Officer. Create a CIO position in People and complete the hiring process first.</div>}{active?<><h3>{active.name}</h3><StatBar label="Progress" value={active.progress}/></>:<Empty>No active research.</Empty>}</Card><Card className="pad span-2"><SectionTitle title="Technology Roadmap"/><div className="candidate-grid">{state.tech.map(t=><Card className="candidate-card" key={t.id}><span className="eyebrow">{t.group} · Tier {t.tier}</span><h3>{t.name}</h3><p>{t.desc}</p>{t.researched?<Pill tone="ok">Operational</Pill>:<><StatBar label="Progress" value={t.progress}/><button className="primary" disabled={!!state.research||!cio} onClick={()=>setState(startResearch(state,t.id))}>Start Research · {money(t.cost)}</button></>}</Card>)}</div></Card></div>}

function Distribution({state,setState}){
  const [code,setCode]=useState(null),st=state.states.find(x=>x.code===code),reach=networkReachHouseholds(state);
  return <div className="page-stack"><div className="metric-grid"><div className="metric"><span>Technical Reach</span><strong>{num(reach)}</strong><small>households</small></div><div className="metric"><span>States with Signal</span><strong>{state.states.filter(x=>x.coverage>.01).length}</strong></div><div className="metric"><span>Rights Markets</span><strong>{state.states.reduce((a,x)=>a+x.areas.filter(y=>y.rightsOwned).length,0)}</strong></div><div className="metric"><span>Antennas</span><strong>{state.states.reduce((a,x)=>a+x.areas.filter(y=>y.antennaLevel>0).length,0)}</strong></div></div>{state.distributionProjects.length>0&&<Card className="pad"><SectionTitle title="Distribution Projects" sub="Rights applications and antennas both take time."/>{state.distributionProjects.map(x=><Process key={x.id} label={`${x.kind==='rights'?'Rights':'Antenna'} · ${x.state}`} days={x.daysRemaining} total={x.totalDays}/>)}</Card>}<Card className="pad"><SectionTitle title="U.S. Broadcast Footprint" sub="Tap a state. Expansion requires BOTH emission rights and physical transmission infrastructure."/><div className="us-map">{state.states.map(x=><button title={`${x.code}: ${pct(x.coverage*100)} coverage`} onClick={()=>setCode(x.code)} key={x.code} style={{gridColumn:x.col,gridRow:x.row,'--cov':x.coverage}} className={x.coverage>.7?'high':x.coverage>.15?'mid':''}><b>{x.code}</b><span>{Math.round(x.coverage*100)}%</span></button>)}</div></Card><Drawer open={!!st} title={st?`${st.code} Broadcast Markets`:''} onClose={()=>setCode(null)} wide>{st&&<StateExpansion state={state} setState={setState} st={st}/>}</Drawer></div>
}
function StateExpansion({state,setState,st}){const allRights=st.areas.every(a=>a.rightsOwned),pendingAll=st.areas.some(a=>a.rightsPending);return <div className="page-stack"><div className="state-expansion-hero"><div><span className="eyebrow">{st.code} · {num(st.households)} households</span><h1>{Math.round(st.coverage*100)}% technical coverage</h1><p>Rights let you legally emit. Antennas create actual reach. Buy either statewide or market-by-market.</p></div><button className="primary big" disabled={allRights||pendingAll} onClick={()=>setState(startEmissionRights(state,st.code,'all'))}>{allRights?'All-state rights owned':'Purchase All-State Rights'}</button></div><div className="market-area-grid">{st.areas.map(a=><Card className="pad market-area-card" key={a.id}><span className="eyebrow">{a.type}</span><h2>{a.name}</h2><p>{num(a.households)} households · {Math.round(a.reachPct*100)}% reached</p><div className="market-gates"><div className={a.rightsOwned?'done':''}><b>1. Emission rights</b><span>{a.rightsOwned?'Owned':a.rightsPending?'Application pending':'Required'}</span>{!a.rightsOwned&&!a.rightsPending&&<button onClick={()=>setState(startEmissionRights(state,st.code,a.id))}>Purchase Area Rights</button>}</div><div className={a.antennaLevel>0?'done':''}><b>2. Antenna infrastructure</b><span>{a.antennaPending?'Under construction':a.antennaLevel?`Level ${a.antennaLevel} · ${Math.round(a.reachPct*100)}% area reach`:'No signal'}</span>{a.rightsOwned&&!a.antennaPending&&a.antennaLevel<3&&<div className="button-row"><button onClick={()=>setState(startAntennaBuild(state,st.code,a.id,Math.max(1,a.antennaLevel+1)))}>Build L{Math.max(1,a.antennaLevel+1)}</button>{a.antennaLevel<2&&<button onClick={()=>setState(startAntennaBuild(state,st.code,a.id,3))}>High-Power L3</button>}</div>}</div></div></Card>)}</div></div>}

function Newsroom({state,setState}){const n=state.newsroom,controls=[['reporters','Reporters'],['bureaus','Bureaus'],['weather','Weather Unit'],['sportsDesk','Sports Desk'],['investigative','Investigative Team']];return <div className="split-layout"><Card className="pad"><SectionTitle title="News Operation" sub="News is a full format: local, national, global, investigative and special reports."/><div className="newsroom-score"><b>{Math.round(n.trust)}</b><span>Trust</span></div>{state.facilities.newsroom<1&&<div className="warning-box">No newsroom facility. Build one first.</div>}</Card><Card className="pad"><SectionTitle title="Permanent Capacity"/>{controls.map(([k,l])=><div className="capacity-row" key={k}><div><b>{l}</b><span>{n[k]}</span></div><div><button disabled={n[k]<=0} onClick={()=>setState(updateNewsroom(state,k,-1))}>−</button><button disabled={state.facilities.newsroom<1} onClick={()=>setState(updateNewsroom(state,k,1))}>+</button></div></div>)}</Card></div>}

function NetworkSettings({state,setState}){const [f,setF]=useState({...state.network}),set=(k,v)=>setF(x=>({...x,[k]:v}));return <div className="split-layout"><Card className="pad"><SectionTitle title="Network Identity"/><div className="form-grid"><label className="full">Network name<input value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>Initials<input value={f.initials} maxLength="5" onChange={e=>set('initials',e.target.value.toUpperCase())}/></label><label>Icon<select value={f.icon} onChange={e=>set('icon',e.target.value)}>{['★','●','◆','▲','✦','☀','⚡','♣','♥','⬟','◉','🐦','📺'].map(x=><option key={x}>{x}</option>)}</select></label><label>Shape<select value={f.shape||'circle'} onChange={e=>set('shape',e.target.value)}><option value="circle">Circle</option><option value="square">Square</option><option value="diamond">Diamond</option><option value="shield">Shield</option></select></label><label>Shape color<input type="color" value={f.primary} onChange={e=>set('primary',e.target.value)}/></label><label>Icon color<input type="color" value={f.secondary} onChange={e=>set('secondary',e.target.value)}/></label><button className="primary full" onClick={()=>setState(updateNetwork(state,{name:f.name,initials:f.initials,icon:f.icon,shape:f.shape,primary:f.primary,secondary:f.secondary}))}>Apply Rebrand</button></div></Card><Card className="pad"><SectionTitle title="Live Preview"/><div className={`brand-seal-large shape-${f.shape||'circle'}`} style={{'--primary':f.primary,'--secondary':f.secondary}}><i>{f.icon}</i><b>{f.initials}</b><span>{f.name}</span></div><SectionTitle title="Starting Expertise"/>{FORMAT_EXPERTISE.map(x=><div className="expertise-row" key={x}><b>{x}</b><strong>{(state.network.expertise[x]||0).toFixed(1)}/10</strong></div>)}</Card></div>}
