import React, { useState } from 'react';
import { Card, Drawer, Empty, Pill, ProgramPoster, Score, SectionTitle, StatBar, Tabs } from './UI.jsx';
import { DEMOS } from '../game/constants.js';
import { getEmployee, getIP, programPnL } from '../game/simulation.js';
import { money, num } from '../game/utils.js';

export function ProgramProfile({state,p,onClose}){
  const [tab,setTab]=useState('overview');
  if(!p)return null;
  const ip=getIP(state,p.ipId),pnl=programPnL(state,p),history=p.episodeHistory||[];
  return <Drawer open title={p.title} onClose={onClose} wide><div className="profile-hero"><ProgramPoster p={p}/><div><span className="eyebrow">{p.format} · {p.genre} · SEASON {p.season}</span><h1>{p.title}</h1><div className="score-row"><Score label="Viewer" value={p.premiered?p.viewer/10:null}/><Score label="Critics" value={p.premiered?p.critic:null}/></div></div></div><Tabs value={tab} onChange={setTab} items={[["overview","Overview"],["audience","Audience & Scores"],["episodes","Episodes"],["identity","IP / Identity"],["finance","Finance"]]}/>
    {tab==='overview'&&<div className="profile-grid"><Card className="pad"><SectionTitle title="Season"/><div className="detail-list"><p><span>Status</span><b>{p.status}</b></p><p><span>Episodes aired</span><b>{Math.floor(p.pipeline.aired)} / {p.episodes}</b></p><p><span>Broadcast-ready</span><b>{Math.max(0,Math.floor(p.pipeline.ready-p.pipeline.aired))}</b></p><p><span>Duration</span><b>{p.duration} min</b></p><p><span>Average audience</span><b>{num(p.airings?p.totalAudience/p.airings:0)}</b></p><p><span>Last audience</span><b>{num(p.lastAudience||0)}</b></p></div></Card><Card className="pad"><SectionTitle title="Creative Team"/><div className="detail-list">{[['Writer',p.team?.leadWriter],['Showrunner',p.team?.showrunner],['Director',p.team?.director]].map(([l,id])=><p key={l}><span>{l}</span><b>{getEmployee(state,id)?.name||'—'}</b></p>)}</div></Card><Card className="pad"><SectionTitle title="Audience Target"/>{DEMOS.map(([k,l])=><StatBar key={k} label={l} value={p.target?.[k]||0}/>)}</Card></div>}
    {tab==='audience'&&<div className="page-stack"><Card className="pad"><SectionTitle title="Episode Evolution" sub="Audience, viewer/critic reception and IP momentum over time."/>{history.length?<div className="table-wrap"><table><thead><tr><th>Ep.</th><th>Date</th><th>Audience</th><th>Home State</th><th>Local</th><th>Viewer</th><th>Critic</th><th>Popularity</th><th>Novelty</th></tr></thead><tbody>{history.map((h,i)=><tr key={i}><td>{h.episode}</td><td>{h.date}</td><td>{num(h.audience)}</td><td>{num(h.stateAudience)}</td><td>{num(h.localAudience)}</td><td>{(h.viewer/10).toFixed(1)}</td><td>{h.critic}%</td><td>{Math.round(h.popularity)}</td><td>{Math.round(h.novelty)}</td></tr>)}</tbody></table></div>:<Empty>No episodes have aired yet.</Empty>}</Card></div>}
    {tab==='episodes'&&<Card className="pad"><SectionTitle title="Episode Inventory"/><div className="episode-grid">{Array.from({length:p.episodes},(_,i)=>{const no=i+1,status=no<=Math.floor(p.pipeline.aired)?'Aired':no<=Math.floor(p.pipeline.ready)?'Ready':no<=Math.floor(p.pipeline.filmed)?'Post':no<=Math.floor(p.pipeline.pre)?'Filming / Pre':'Queued',hist=history.find(h=>h.episode===no);return <div className="episode-tile" key={no}><span>EP {String(no).padStart(2,'0')}</span><b>{status}</b>{hist&&<small>{num(hist.audience)} viewers</small>}</div>})}</div></Card>}
    {tab==='identity'&&<div className="split-layout"><Card className="pad"><SectionTitle title="IP Health"/><StatBar label="Popularity" value={ip?.popularity||0}/><StatBar label="Novelty" value={ip?.novelty||0}/><StatBar label="Fandom" value={ip?.fandom||0}/><StatBar label="Fatigue" value={ip?.fatigue||0}/><StatBar label="Prestige" value={ip?.prestige||0}/></Card><Card className="pad"><SectionTitle title="Property"/><div className="detail-list"><p><span>Origin</span><b>{ip?.origin||'—'}</b></p><p><span>IP value</span><b>{money(ip?.value||0)}</b></p><p><span>Script</span><b>{p.scriptStars?.toFixed(1)} / 5 ★</b></p><p><span>Execution</span><b>{Math.round(p.quality||0)} / 100</b></p><p><span>Momentum</span><b>{(p.momentum||0).toFixed(1)}</b></p></div></Card></div>}
    {tab==='finance'&&<Card className="pad"><SectionTitle title="Program P&L"/><div className="detail-list"><p><span>Program revenue</span><b>{money(pnl.revenue)}</b></p><p><span>Production</span><b>{money(-pnl.production)}</b></p><p><span>Marketing</span><b>{money(-pnl.marketing)}</b></p><p><span>Contribution</span><b className={pnl.contribution>=0?'positive':'negative'}>{money(pnl.contribution)}</b></p></div></Card>}
  </Drawer>
}

export function PersonProfile({state,person,onClose}){
  const [tab,setTab]=useState('overview');if(!person)return null;
  const projects=state.programs.filter(p=>Object.values(p.team||{}).includes(person.id)||(p.cast||[]).includes(person.id));
  return <Drawer open title={person.name} onClose={onClose} wide><div className="person-hero"><div className="person-avatar">{person.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><span className="eyebrow">{person.role} · {person.dept}</span><h1>{person.name}</h1><Pill>OVR {person.overall}</Pill></div></div><Tabs value={tab} onChange={setTab} items={[["overview","Overview"],["skills","Specialties"],["projects","Projects"],["contract","Contract"]]}/>
    {tab==='overview'&&<div className="profile-grid"><Card className="pad"><SectionTitle title="Career"/><div className="detail-list"><p><span>Role</span><b>{person.role}</b></p><p><span>Overall</span><b>{person.overall}</b></p><p><span>Popularity</span><b>{Math.round(person.popularity||0)}</b></p><p><span>Morale</span><b>{Math.round(person.morale||0)}</b></p></div></Card><Card className="pad"><SectionTitle title="Preferences"/>{Object.entries(person.preferences||{}).map(([k,v])=><StatBar key={k} label={k} value={v}/>)}</Card></div>}
    {tab==='skills'&&<Card className="pad"><SectionTitle title="Skills & Specialties"/><div className="skill-grid">{Object.entries(person.skills||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b><StatBar label="" value={v}/></div>)}</div></Card>}
    {tab==='projects'&&<Card className="pad"><SectionTitle title="Project History"/>{projects.length?<div className="table-wrap"><table><thead><tr><th>Year</th><th>Program</th><th>Role</th><th>Viewer</th><th>Critic</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td>{new Date(p.productionStart||state.date).getFullYear()}</td><td>{p.title}</td><td>{(p.cast||[]).includes(person.id)?'Cast':p.team?.showrunner===person.id?'Showrunner':p.team?.director===person.id?'Director':'Writer'}</td><td>{p.premiered?(p.viewer/10).toFixed(1):'—'}</td><td>{p.premiered?`${p.critic}%`:'—'}</td></tr>)}</tbody></table></div>:<Empty>No completed network projects yet.</Empty>}</Card>}
    {tab==='contract'&&<Card className="pad"><SectionTitle title="Contract"/><div className="detail-list"><p><span>Salary</span><b>{money(person.salary||0)}/yr</b></p><p><span>Term</span><b>{person.contractYears||0} years</b></p><p><span>Start</span><b>{person.contractStart||'—'}</b></p><p><span>Backend</span><b>{person.backend||0}%</b></p><p><span>Creative control</span><b>{person.creativeControl||0}%</b></p></div></Card>}
  </Drawer>
}

export function RivalProgramProfile({state,row,onClose}){
  const [tab,setTab]=useState('overview');if(!row)return null;
  const network=state.competitors.find(c=>c.id===row.networkId),program=network?.programs?.find(p=>p.id===row.programId),history=(state.competitorRatings||[]).filter(x=>x.programId===row.programId),latest=history.at(-1),avgAud=history.length?history.reduce((a,x)=>a+x.audience,0)/history.length:row.audience||0;
  return <Drawer open title={row.title} onClose={onClose} wide><div className="rival-profile-hero"><div className="rival-program-art"><span>{row.format}</span><b>{row.title}</b><small>{row.network}</small></div><div><span className="eyebrow">RIVAL PROGRAM · {row.format} · {row.genre}</span><h1>{row.title}</h1><p>{row.network} · {row.band}</p><div className="score-row"><Score label="Viewer" value={row.viewer}/><Score label="Critics" value={row.critic}/></div></div></div><Tabs value={tab} onChange={setTab} items={[["overview","Overview"],["audience","Audience & Scores"],["identity","Popularity / Novelty"]]}/>
    {tab==='overview'&&<div className="profile-grid"><Card className="pad"><SectionTitle title="Performance"/><div className="detail-list"><p><span>Network</span><b>{row.network}</b></p><p><span>Format</span><b>{row.format} / {row.genre}</b></p><p><span>Primary slot</span><b>{row.band}</b></p><p><span>Average national audience</span><b>{num(avgAud)}</b></p></div></Card><Card className="pad"><SectionTitle title="Competitive Identity"/><div className="detail-list"><p><span>Network scope</span><b>{network?.scope||'—'}</b></p><p><span>Network identity</span><b>{network?.identity||'—'}</b></p><p><span>Network prestige</span><b>{Math.round(network?.prestige||0)}</b></p></div></Card></div>}
    {tab==='audience'&&<Card className="pad"><SectionTitle title="Audience Evolution" sub="Tracked daily performance in national, state and your original local market."/>{history.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>National</th><th>State</th><th>Local</th><th>Viewer</th><th>Critic</th></tr></thead><tbody>{history.slice(-60).map((h,i)=><tr key={`${h.date}-${i}`}><td>{h.date}</td><td>{num(h.audience)}</td><td>{num(h.stateAudience)}</td><td>{num(h.localAudience)}</td><td>{Number(h.viewer).toFixed(1)}</td><td>{Math.round(h.critic)}%</td></tr>)}</tbody></table></div>:<Empty>No tracked airings yet.</Empty>}</Card>}
    {tab==='identity'&&<div className="split-layout"><Card className="pad"><SectionTitle title="Program Identity"/><StatBar label="Popularity" value={latest?.popularity??program?.popularity??0}/><StatBar label="Novelty" value={latest?.novelty??program?.novelty??0}/><StatBar label="Base appeal" value={program?.baseAppeal||0}/></Card><Card className="pad"><SectionTitle title="Reception"/><div className="detail-list"><p><span>Viewer score</span><b>{Number(row.viewer||0).toFixed(1)} / 10</b></p><p><span>Critic score</span><b>{Math.round(row.critic||0)}%</b></p><p><span>Tracked airings</span><b>{history.length}</b></p></div></Card></div>}
  </Drawer>
}
